import GYNIProof.Model
import GYNIProof.CertSmall0
import GYNIProof.CertSmall1
import GYNIProof.CertSmall2
import GYNIProof.CertSmall3
import GYNIProof.CertSmall4
import GYNIProof.CertSmall5
import GYNIProof.CertSmall6
import GYNIProof.CertSmall7
import GYNIProof.CertMid0
import GYNIProof.CertMid1
import GYNIProof.CertMid2
import GYNIProof.CertMid3
import GYNIProof.CertMid4
import GYNIProof.CertMid5
import GYNIProof.CertMid6
import GYNIProof.CertMid7
import GYNIProof.CertMid8
import GYNIProof.CertMid9
import GYNIProof.CertMid10
import GYNIProof.CertMid11
import GYNIProof.CertMid12
import GYNIProof.CertMid13
import GYNIProof.CertMid14
import GYNIProof.CertMid15

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Every block `(cA, cB)`, `cA ≤ cB < 26`, of `2^71 W` is positive semidefinite: the kernel checks
`chk_cA_cB` of `CertSmall*`/`CertMid*` (348 blocks) turned into `BlockPSD cA cB` by
`posSemidef_of_chk`. The three `256 × 256` blocks `(0, 0)`, `(0, 13)`, `(13, 13)` (both parties in a
label-diagonal class) enter through the hypothesis `BigBlocksPSD`, discharged in `CertBig_*.lean`
(`Main.lean`). -/

namespace GYNIProof

/-- Positive semidefiniteness of the three `256 × 256` integer blocks `blockA 0 0`,
`blockA 0 13`, `blockA 13 13` of `2^71 W`. -/
def BigBlocksPSD : Prop := BlockPSD 0 0 ∧ BlockPSD 0 13 ∧ BlockPSD 13 13

theorem cert_1_1 : BlockPSD 1 1 :=
  posSemidef_of_chk _ (blockA 1 1) (blockA_symm 1 1) _ _ _ _ alphaW (blockA_bound 1 1)
    cL_1_1 cE_1_1 cPL_1_1 rfl chk_1_1

theorem cert_1_2 : BlockPSD 1 2 :=
  posSemidef_of_chk _ (blockA 1 2) (blockA_symm 1 2) _ _ _ _ alphaW (blockA_bound 1 2)
    cL_1_2 cE_1_2 cPL_1_2 rfl chk_1_2

theorem cert_1_3 : BlockPSD 1 3 :=
  posSemidef_of_chk _ (blockA 1 3) (blockA_symm 1 3) _ _ _ _ alphaW (blockA_bound 1 3)
    cL_1_3 cE_1_3 cPL_1_3 rfl chk_1_3

theorem cert_1_4 : BlockPSD 1 4 :=
  posSemidef_of_chk _ (blockA 1 4) (blockA_symm 1 4) _ _ _ _ alphaW (blockA_bound 1 4)
    cL_1_4 cE_1_4 cPL_1_4 rfl chk_1_4

theorem cert_1_5 : BlockPSD 1 5 :=
  posSemidef_of_chk _ (blockA 1 5) (blockA_symm 1 5) _ _ _ _ alphaW (blockA_bound 1 5)
    cL_1_5 cE_1_5 cPL_1_5 rfl chk_1_5

theorem cert_1_6 : BlockPSD 1 6 :=
  posSemidef_of_chk _ (blockA 1 6) (blockA_symm 1 6) _ _ _ _ alphaW (blockA_bound 1 6)
    cL_1_6 cE_1_6 cPL_1_6 rfl chk_1_6

theorem cert_1_7 : BlockPSD 1 7 :=
  posSemidef_of_chk _ (blockA 1 7) (blockA_symm 1 7) _ _ _ _ alphaW (blockA_bound 1 7)
    cL_1_7 cE_1_7 cPL_1_7 rfl chk_1_7

theorem cert_1_8 : BlockPSD 1 8 :=
  posSemidef_of_chk _ (blockA 1 8) (blockA_symm 1 8) _ _ _ _ alphaW (blockA_bound 1 8)
    cL_1_8 cE_1_8 cPL_1_8 rfl chk_1_8

theorem cert_1_9 : BlockPSD 1 9 :=
  posSemidef_of_chk _ (blockA 1 9) (blockA_symm 1 9) _ _ _ _ alphaW (blockA_bound 1 9)
    cL_1_9 cE_1_9 cPL_1_9 rfl chk_1_9

theorem cert_1_10 : BlockPSD 1 10 :=
  posSemidef_of_chk _ (blockA 1 10) (blockA_symm 1 10) _ _ _ _ alphaW (blockA_bound 1 10)
    cL_1_10 cE_1_10 cPL_1_10 rfl chk_1_10

theorem cert_1_11 : BlockPSD 1 11 :=
  posSemidef_of_chk _ (blockA 1 11) (blockA_symm 1 11) _ _ _ _ alphaW (blockA_bound 1 11)
    cL_1_11 cE_1_11 cPL_1_11 rfl chk_1_11

theorem cert_1_12 : BlockPSD 1 12 :=
  posSemidef_of_chk _ (blockA 1 12) (blockA_symm 1 12) _ _ _ _ alphaW (blockA_bound 1 12)
    cL_1_12 cE_1_12 cPL_1_12 rfl chk_1_12

theorem cert_1_14 : BlockPSD 1 14 :=
  posSemidef_of_chk _ (blockA 1 14) (blockA_symm 1 14) _ _ _ _ alphaW (blockA_bound 1 14)
    cL_1_14 cE_1_14 cPL_1_14 rfl chk_1_14

theorem cert_1_15 : BlockPSD 1 15 :=
  posSemidef_of_chk _ (blockA 1 15) (blockA_symm 1 15) _ _ _ _ alphaW (blockA_bound 1 15)
    cL_1_15 cE_1_15 cPL_1_15 rfl chk_1_15

theorem cert_1_16 : BlockPSD 1 16 :=
  posSemidef_of_chk _ (blockA 1 16) (blockA_symm 1 16) _ _ _ _ alphaW (blockA_bound 1 16)
    cL_1_16 cE_1_16 cPL_1_16 rfl chk_1_16

theorem cert_1_17 : BlockPSD 1 17 :=
  posSemidef_of_chk _ (blockA 1 17) (blockA_symm 1 17) _ _ _ _ alphaW (blockA_bound 1 17)
    cL_1_17 cE_1_17 cPL_1_17 rfl chk_1_17

theorem cert_1_18 : BlockPSD 1 18 :=
  posSemidef_of_chk _ (blockA 1 18) (blockA_symm 1 18) _ _ _ _ alphaW (blockA_bound 1 18)
    cL_1_18 cE_1_18 cPL_1_18 rfl chk_1_18

theorem cert_1_19 : BlockPSD 1 19 :=
  posSemidef_of_chk _ (blockA 1 19) (blockA_symm 1 19) _ _ _ _ alphaW (blockA_bound 1 19)
    cL_1_19 cE_1_19 cPL_1_19 rfl chk_1_19

theorem cert_1_20 : BlockPSD 1 20 :=
  posSemidef_of_chk _ (blockA 1 20) (blockA_symm 1 20) _ _ _ _ alphaW (blockA_bound 1 20)
    cL_1_20 cE_1_20 cPL_1_20 rfl chk_1_20

theorem cert_1_21 : BlockPSD 1 21 :=
  posSemidef_of_chk _ (blockA 1 21) (blockA_symm 1 21) _ _ _ _ alphaW (blockA_bound 1 21)
    cL_1_21 cE_1_21 cPL_1_21 rfl chk_1_21

theorem cert_1_22 : BlockPSD 1 22 :=
  posSemidef_of_chk _ (blockA 1 22) (blockA_symm 1 22) _ _ _ _ alphaW (blockA_bound 1 22)
    cL_1_22 cE_1_22 cPL_1_22 rfl chk_1_22

theorem cert_1_23 : BlockPSD 1 23 :=
  posSemidef_of_chk _ (blockA 1 23) (blockA_symm 1 23) _ _ _ _ alphaW (blockA_bound 1 23)
    cL_1_23 cE_1_23 cPL_1_23 rfl chk_1_23

theorem cert_1_24 : BlockPSD 1 24 :=
  posSemidef_of_chk _ (blockA 1 24) (blockA_symm 1 24) _ _ _ _ alphaW (blockA_bound 1 24)
    cL_1_24 cE_1_24 cPL_1_24 rfl chk_1_24

theorem cert_1_25 : BlockPSD 1 25 :=
  posSemidef_of_chk _ (blockA 1 25) (blockA_symm 1 25) _ _ _ _ alphaW (blockA_bound 1 25)
    cL_1_25 cE_1_25 cPL_1_25 rfl chk_1_25

theorem cert_2_2 : BlockPSD 2 2 :=
  posSemidef_of_chk _ (blockA 2 2) (blockA_symm 2 2) _ _ _ _ alphaW (blockA_bound 2 2)
    cL_2_2 cE_2_2 cPL_2_2 rfl chk_2_2

theorem cert_2_3 : BlockPSD 2 3 :=
  posSemidef_of_chk _ (blockA 2 3) (blockA_symm 2 3) _ _ _ _ alphaW (blockA_bound 2 3)
    cL_2_3 cE_2_3 cPL_2_3 rfl chk_2_3

theorem cert_2_4 : BlockPSD 2 4 :=
  posSemidef_of_chk _ (blockA 2 4) (blockA_symm 2 4) _ _ _ _ alphaW (blockA_bound 2 4)
    cL_2_4 cE_2_4 cPL_2_4 rfl chk_2_4

theorem cert_2_5 : BlockPSD 2 5 :=
  posSemidef_of_chk _ (blockA 2 5) (blockA_symm 2 5) _ _ _ _ alphaW (blockA_bound 2 5)
    cL_2_5 cE_2_5 cPL_2_5 rfl chk_2_5

theorem cert_2_6 : BlockPSD 2 6 :=
  posSemidef_of_chk _ (blockA 2 6) (blockA_symm 2 6) _ _ _ _ alphaW (blockA_bound 2 6)
    cL_2_6 cE_2_6 cPL_2_6 rfl chk_2_6

theorem cert_2_7 : BlockPSD 2 7 :=
  posSemidef_of_chk _ (blockA 2 7) (blockA_symm 2 7) _ _ _ _ alphaW (blockA_bound 2 7)
    cL_2_7 cE_2_7 cPL_2_7 rfl chk_2_7

theorem cert_2_8 : BlockPSD 2 8 :=
  posSemidef_of_chk _ (blockA 2 8) (blockA_symm 2 8) _ _ _ _ alphaW (blockA_bound 2 8)
    cL_2_8 cE_2_8 cPL_2_8 rfl chk_2_8

theorem cert_2_9 : BlockPSD 2 9 :=
  posSemidef_of_chk _ (blockA 2 9) (blockA_symm 2 9) _ _ _ _ alphaW (blockA_bound 2 9)
    cL_2_9 cE_2_9 cPL_2_9 rfl chk_2_9

theorem cert_2_10 : BlockPSD 2 10 :=
  posSemidef_of_chk _ (blockA 2 10) (blockA_symm 2 10) _ _ _ _ alphaW (blockA_bound 2 10)
    cL_2_10 cE_2_10 cPL_2_10 rfl chk_2_10

theorem cert_2_11 : BlockPSD 2 11 :=
  posSemidef_of_chk _ (blockA 2 11) (blockA_symm 2 11) _ _ _ _ alphaW (blockA_bound 2 11)
    cL_2_11 cE_2_11 cPL_2_11 rfl chk_2_11

theorem cert_2_12 : BlockPSD 2 12 :=
  posSemidef_of_chk _ (blockA 2 12) (blockA_symm 2 12) _ _ _ _ alphaW (blockA_bound 2 12)
    cL_2_12 cE_2_12 cPL_2_12 rfl chk_2_12

theorem cert_2_14 : BlockPSD 2 14 :=
  posSemidef_of_chk _ (blockA 2 14) (blockA_symm 2 14) _ _ _ _ alphaW (blockA_bound 2 14)
    cL_2_14 cE_2_14 cPL_2_14 rfl chk_2_14

theorem cert_2_15 : BlockPSD 2 15 :=
  posSemidef_of_chk _ (blockA 2 15) (blockA_symm 2 15) _ _ _ _ alphaW (blockA_bound 2 15)
    cL_2_15 cE_2_15 cPL_2_15 rfl chk_2_15

theorem cert_2_16 : BlockPSD 2 16 :=
  posSemidef_of_chk _ (blockA 2 16) (blockA_symm 2 16) _ _ _ _ alphaW (blockA_bound 2 16)
    cL_2_16 cE_2_16 cPL_2_16 rfl chk_2_16

theorem cert_2_17 : BlockPSD 2 17 :=
  posSemidef_of_chk _ (blockA 2 17) (blockA_symm 2 17) _ _ _ _ alphaW (blockA_bound 2 17)
    cL_2_17 cE_2_17 cPL_2_17 rfl chk_2_17

theorem cert_2_18 : BlockPSD 2 18 :=
  posSemidef_of_chk _ (blockA 2 18) (blockA_symm 2 18) _ _ _ _ alphaW (blockA_bound 2 18)
    cL_2_18 cE_2_18 cPL_2_18 rfl chk_2_18

theorem cert_2_19 : BlockPSD 2 19 :=
  posSemidef_of_chk _ (blockA 2 19) (blockA_symm 2 19) _ _ _ _ alphaW (blockA_bound 2 19)
    cL_2_19 cE_2_19 cPL_2_19 rfl chk_2_19

theorem cert_2_20 : BlockPSD 2 20 :=
  posSemidef_of_chk _ (blockA 2 20) (blockA_symm 2 20) _ _ _ _ alphaW (blockA_bound 2 20)
    cL_2_20 cE_2_20 cPL_2_20 rfl chk_2_20

theorem cert_2_21 : BlockPSD 2 21 :=
  posSemidef_of_chk _ (blockA 2 21) (blockA_symm 2 21) _ _ _ _ alphaW (blockA_bound 2 21)
    cL_2_21 cE_2_21 cPL_2_21 rfl chk_2_21

theorem cert_2_22 : BlockPSD 2 22 :=
  posSemidef_of_chk _ (blockA 2 22) (blockA_symm 2 22) _ _ _ _ alphaW (blockA_bound 2 22)
    cL_2_22 cE_2_22 cPL_2_22 rfl chk_2_22

theorem cert_2_23 : BlockPSD 2 23 :=
  posSemidef_of_chk _ (blockA 2 23) (blockA_symm 2 23) _ _ _ _ alphaW (blockA_bound 2 23)
    cL_2_23 cE_2_23 cPL_2_23 rfl chk_2_23

theorem cert_2_24 : BlockPSD 2 24 :=
  posSemidef_of_chk _ (blockA 2 24) (blockA_symm 2 24) _ _ _ _ alphaW (blockA_bound 2 24)
    cL_2_24 cE_2_24 cPL_2_24 rfl chk_2_24

theorem cert_2_25 : BlockPSD 2 25 :=
  posSemidef_of_chk _ (blockA 2 25) (blockA_symm 2 25) _ _ _ _ alphaW (blockA_bound 2 25)
    cL_2_25 cE_2_25 cPL_2_25 rfl chk_2_25

theorem cert_3_3 : BlockPSD 3 3 :=
  posSemidef_of_chk _ (blockA 3 3) (blockA_symm 3 3) _ _ _ _ alphaW (blockA_bound 3 3)
    cL_3_3 cE_3_3 cPL_3_3 rfl chk_3_3

theorem cert_3_4 : BlockPSD 3 4 :=
  posSemidef_of_chk _ (blockA 3 4) (blockA_symm 3 4) _ _ _ _ alphaW (blockA_bound 3 4)
    cL_3_4 cE_3_4 cPL_3_4 rfl chk_3_4

theorem cert_3_5 : BlockPSD 3 5 :=
  posSemidef_of_chk _ (blockA 3 5) (blockA_symm 3 5) _ _ _ _ alphaW (blockA_bound 3 5)
    cL_3_5 cE_3_5 cPL_3_5 rfl chk_3_5

theorem cert_3_6 : BlockPSD 3 6 :=
  posSemidef_of_chk _ (blockA 3 6) (blockA_symm 3 6) _ _ _ _ alphaW (blockA_bound 3 6)
    cL_3_6 cE_3_6 cPL_3_6 rfl chk_3_6

theorem cert_3_7 : BlockPSD 3 7 :=
  posSemidef_of_chk _ (blockA 3 7) (blockA_symm 3 7) _ _ _ _ alphaW (blockA_bound 3 7)
    cL_3_7 cE_3_7 cPL_3_7 rfl chk_3_7

theorem cert_3_8 : BlockPSD 3 8 :=
  posSemidef_of_chk _ (blockA 3 8) (blockA_symm 3 8) _ _ _ _ alphaW (blockA_bound 3 8)
    cL_3_8 cE_3_8 cPL_3_8 rfl chk_3_8

theorem cert_3_9 : BlockPSD 3 9 :=
  posSemidef_of_chk _ (blockA 3 9) (blockA_symm 3 9) _ _ _ _ alphaW (blockA_bound 3 9)
    cL_3_9 cE_3_9 cPL_3_9 rfl chk_3_9

theorem cert_3_10 : BlockPSD 3 10 :=
  posSemidef_of_chk _ (blockA 3 10) (blockA_symm 3 10) _ _ _ _ alphaW (blockA_bound 3 10)
    cL_3_10 cE_3_10 cPL_3_10 rfl chk_3_10

theorem cert_3_11 : BlockPSD 3 11 :=
  posSemidef_of_chk _ (blockA 3 11) (blockA_symm 3 11) _ _ _ _ alphaW (blockA_bound 3 11)
    cL_3_11 cE_3_11 cPL_3_11 rfl chk_3_11

theorem cert_3_12 : BlockPSD 3 12 :=
  posSemidef_of_chk _ (blockA 3 12) (blockA_symm 3 12) _ _ _ _ alphaW (blockA_bound 3 12)
    cL_3_12 cE_3_12 cPL_3_12 rfl chk_3_12

theorem cert_3_14 : BlockPSD 3 14 :=
  posSemidef_of_chk _ (blockA 3 14) (blockA_symm 3 14) _ _ _ _ alphaW (blockA_bound 3 14)
    cL_3_14 cE_3_14 cPL_3_14 rfl chk_3_14

theorem cert_3_15 : BlockPSD 3 15 :=
  posSemidef_of_chk _ (blockA 3 15) (blockA_symm 3 15) _ _ _ _ alphaW (blockA_bound 3 15)
    cL_3_15 cE_3_15 cPL_3_15 rfl chk_3_15

theorem cert_3_16 : BlockPSD 3 16 :=
  posSemidef_of_chk _ (blockA 3 16) (blockA_symm 3 16) _ _ _ _ alphaW (blockA_bound 3 16)
    cL_3_16 cE_3_16 cPL_3_16 rfl chk_3_16

theorem cert_3_17 : BlockPSD 3 17 :=
  posSemidef_of_chk _ (blockA 3 17) (blockA_symm 3 17) _ _ _ _ alphaW (blockA_bound 3 17)
    cL_3_17 cE_3_17 cPL_3_17 rfl chk_3_17

theorem cert_3_18 : BlockPSD 3 18 :=
  posSemidef_of_chk _ (blockA 3 18) (blockA_symm 3 18) _ _ _ _ alphaW (blockA_bound 3 18)
    cL_3_18 cE_3_18 cPL_3_18 rfl chk_3_18

theorem cert_3_19 : BlockPSD 3 19 :=
  posSemidef_of_chk _ (blockA 3 19) (blockA_symm 3 19) _ _ _ _ alphaW (blockA_bound 3 19)
    cL_3_19 cE_3_19 cPL_3_19 rfl chk_3_19

theorem cert_3_20 : BlockPSD 3 20 :=
  posSemidef_of_chk _ (blockA 3 20) (blockA_symm 3 20) _ _ _ _ alphaW (blockA_bound 3 20)
    cL_3_20 cE_3_20 cPL_3_20 rfl chk_3_20

theorem cert_3_21 : BlockPSD 3 21 :=
  posSemidef_of_chk _ (blockA 3 21) (blockA_symm 3 21) _ _ _ _ alphaW (blockA_bound 3 21)
    cL_3_21 cE_3_21 cPL_3_21 rfl chk_3_21

theorem cert_3_22 : BlockPSD 3 22 :=
  posSemidef_of_chk _ (blockA 3 22) (blockA_symm 3 22) _ _ _ _ alphaW (blockA_bound 3 22)
    cL_3_22 cE_3_22 cPL_3_22 rfl chk_3_22

theorem cert_3_23 : BlockPSD 3 23 :=
  posSemidef_of_chk _ (blockA 3 23) (blockA_symm 3 23) _ _ _ _ alphaW (blockA_bound 3 23)
    cL_3_23 cE_3_23 cPL_3_23 rfl chk_3_23

theorem cert_3_24 : BlockPSD 3 24 :=
  posSemidef_of_chk _ (blockA 3 24) (blockA_symm 3 24) _ _ _ _ alphaW (blockA_bound 3 24)
    cL_3_24 cE_3_24 cPL_3_24 rfl chk_3_24

theorem cert_3_25 : BlockPSD 3 25 :=
  posSemidef_of_chk _ (blockA 3 25) (blockA_symm 3 25) _ _ _ _ alphaW (blockA_bound 3 25)
    cL_3_25 cE_3_25 cPL_3_25 rfl chk_3_25

theorem cert_4_4 : BlockPSD 4 4 :=
  posSemidef_of_chk _ (blockA 4 4) (blockA_symm 4 4) _ _ _ _ alphaW (blockA_bound 4 4)
    cL_4_4 cE_4_4 cPL_4_4 rfl chk_4_4

theorem cert_4_5 : BlockPSD 4 5 :=
  posSemidef_of_chk _ (blockA 4 5) (blockA_symm 4 5) _ _ _ _ alphaW (blockA_bound 4 5)
    cL_4_5 cE_4_5 cPL_4_5 rfl chk_4_5

theorem cert_4_6 : BlockPSD 4 6 :=
  posSemidef_of_chk _ (blockA 4 6) (blockA_symm 4 6) _ _ _ _ alphaW (blockA_bound 4 6)
    cL_4_6 cE_4_6 cPL_4_6 rfl chk_4_6

theorem cert_4_7 : BlockPSD 4 7 :=
  posSemidef_of_chk _ (blockA 4 7) (blockA_symm 4 7) _ _ _ _ alphaW (blockA_bound 4 7)
    cL_4_7 cE_4_7 cPL_4_7 rfl chk_4_7

theorem cert_4_8 : BlockPSD 4 8 :=
  posSemidef_of_chk _ (blockA 4 8) (blockA_symm 4 8) _ _ _ _ alphaW (blockA_bound 4 8)
    cL_4_8 cE_4_8 cPL_4_8 rfl chk_4_8

theorem cert_4_9 : BlockPSD 4 9 :=
  posSemidef_of_chk _ (blockA 4 9) (blockA_symm 4 9) _ _ _ _ alphaW (blockA_bound 4 9)
    cL_4_9 cE_4_9 cPL_4_9 rfl chk_4_9

theorem cert_4_10 : BlockPSD 4 10 :=
  posSemidef_of_chk _ (blockA 4 10) (blockA_symm 4 10) _ _ _ _ alphaW (blockA_bound 4 10)
    cL_4_10 cE_4_10 cPL_4_10 rfl chk_4_10

theorem cert_4_11 : BlockPSD 4 11 :=
  posSemidef_of_chk _ (blockA 4 11) (blockA_symm 4 11) _ _ _ _ alphaW (blockA_bound 4 11)
    cL_4_11 cE_4_11 cPL_4_11 rfl chk_4_11

theorem cert_4_12 : BlockPSD 4 12 :=
  posSemidef_of_chk _ (blockA 4 12) (blockA_symm 4 12) _ _ _ _ alphaW (blockA_bound 4 12)
    cL_4_12 cE_4_12 cPL_4_12 rfl chk_4_12

theorem cert_4_14 : BlockPSD 4 14 :=
  posSemidef_of_chk _ (blockA 4 14) (blockA_symm 4 14) _ _ _ _ alphaW (blockA_bound 4 14)
    cL_4_14 cE_4_14 cPL_4_14 rfl chk_4_14

theorem cert_4_15 : BlockPSD 4 15 :=
  posSemidef_of_chk _ (blockA 4 15) (blockA_symm 4 15) _ _ _ _ alphaW (blockA_bound 4 15)
    cL_4_15 cE_4_15 cPL_4_15 rfl chk_4_15

theorem cert_4_16 : BlockPSD 4 16 :=
  posSemidef_of_chk _ (blockA 4 16) (blockA_symm 4 16) _ _ _ _ alphaW (blockA_bound 4 16)
    cL_4_16 cE_4_16 cPL_4_16 rfl chk_4_16

theorem cert_4_17 : BlockPSD 4 17 :=
  posSemidef_of_chk _ (blockA 4 17) (blockA_symm 4 17) _ _ _ _ alphaW (blockA_bound 4 17)
    cL_4_17 cE_4_17 cPL_4_17 rfl chk_4_17

theorem cert_4_18 : BlockPSD 4 18 :=
  posSemidef_of_chk _ (blockA 4 18) (blockA_symm 4 18) _ _ _ _ alphaW (blockA_bound 4 18)
    cL_4_18 cE_4_18 cPL_4_18 rfl chk_4_18

theorem cert_4_19 : BlockPSD 4 19 :=
  posSemidef_of_chk _ (blockA 4 19) (blockA_symm 4 19) _ _ _ _ alphaW (blockA_bound 4 19)
    cL_4_19 cE_4_19 cPL_4_19 rfl chk_4_19

theorem cert_4_20 : BlockPSD 4 20 :=
  posSemidef_of_chk _ (blockA 4 20) (blockA_symm 4 20) _ _ _ _ alphaW (blockA_bound 4 20)
    cL_4_20 cE_4_20 cPL_4_20 rfl chk_4_20

theorem cert_4_21 : BlockPSD 4 21 :=
  posSemidef_of_chk _ (blockA 4 21) (blockA_symm 4 21) _ _ _ _ alphaW (blockA_bound 4 21)
    cL_4_21 cE_4_21 cPL_4_21 rfl chk_4_21

theorem cert_4_22 : BlockPSD 4 22 :=
  posSemidef_of_chk _ (blockA 4 22) (blockA_symm 4 22) _ _ _ _ alphaW (blockA_bound 4 22)
    cL_4_22 cE_4_22 cPL_4_22 rfl chk_4_22

theorem cert_4_23 : BlockPSD 4 23 :=
  posSemidef_of_chk _ (blockA 4 23) (blockA_symm 4 23) _ _ _ _ alphaW (blockA_bound 4 23)
    cL_4_23 cE_4_23 cPL_4_23 rfl chk_4_23

theorem cert_4_24 : BlockPSD 4 24 :=
  posSemidef_of_chk _ (blockA 4 24) (blockA_symm 4 24) _ _ _ _ alphaW (blockA_bound 4 24)
    cL_4_24 cE_4_24 cPL_4_24 rfl chk_4_24

theorem cert_4_25 : BlockPSD 4 25 :=
  posSemidef_of_chk _ (blockA 4 25) (blockA_symm 4 25) _ _ _ _ alphaW (blockA_bound 4 25)
    cL_4_25 cE_4_25 cPL_4_25 rfl chk_4_25

theorem cert_5_5 : BlockPSD 5 5 :=
  posSemidef_of_chk _ (blockA 5 5) (blockA_symm 5 5) _ _ _ _ alphaW (blockA_bound 5 5)
    cL_5_5 cE_5_5 cPL_5_5 rfl chk_5_5

theorem cert_5_6 : BlockPSD 5 6 :=
  posSemidef_of_chk _ (blockA 5 6) (blockA_symm 5 6) _ _ _ _ alphaW (blockA_bound 5 6)
    cL_5_6 cE_5_6 cPL_5_6 rfl chk_5_6

theorem cert_5_7 : BlockPSD 5 7 :=
  posSemidef_of_chk _ (blockA 5 7) (blockA_symm 5 7) _ _ _ _ alphaW (blockA_bound 5 7)
    cL_5_7 cE_5_7 cPL_5_7 rfl chk_5_7

theorem cert_5_8 : BlockPSD 5 8 :=
  posSemidef_of_chk _ (blockA 5 8) (blockA_symm 5 8) _ _ _ _ alphaW (blockA_bound 5 8)
    cL_5_8 cE_5_8 cPL_5_8 rfl chk_5_8

theorem cert_5_9 : BlockPSD 5 9 :=
  posSemidef_of_chk _ (blockA 5 9) (blockA_symm 5 9) _ _ _ _ alphaW (blockA_bound 5 9)
    cL_5_9 cE_5_9 cPL_5_9 rfl chk_5_9

theorem cert_5_10 : BlockPSD 5 10 :=
  posSemidef_of_chk _ (blockA 5 10) (blockA_symm 5 10) _ _ _ _ alphaW (blockA_bound 5 10)
    cL_5_10 cE_5_10 cPL_5_10 rfl chk_5_10

theorem cert_5_11 : BlockPSD 5 11 :=
  posSemidef_of_chk _ (blockA 5 11) (blockA_symm 5 11) _ _ _ _ alphaW (blockA_bound 5 11)
    cL_5_11 cE_5_11 cPL_5_11 rfl chk_5_11

theorem cert_5_12 : BlockPSD 5 12 :=
  posSemidef_of_chk _ (blockA 5 12) (blockA_symm 5 12) _ _ _ _ alphaW (blockA_bound 5 12)
    cL_5_12 cE_5_12 cPL_5_12 rfl chk_5_12

theorem cert_5_14 : BlockPSD 5 14 :=
  posSemidef_of_chk _ (blockA 5 14) (blockA_symm 5 14) _ _ _ _ alphaW (blockA_bound 5 14)
    cL_5_14 cE_5_14 cPL_5_14 rfl chk_5_14

theorem cert_5_15 : BlockPSD 5 15 :=
  posSemidef_of_chk _ (blockA 5 15) (blockA_symm 5 15) _ _ _ _ alphaW (blockA_bound 5 15)
    cL_5_15 cE_5_15 cPL_5_15 rfl chk_5_15

theorem cert_5_16 : BlockPSD 5 16 :=
  posSemidef_of_chk _ (blockA 5 16) (blockA_symm 5 16) _ _ _ _ alphaW (blockA_bound 5 16)
    cL_5_16 cE_5_16 cPL_5_16 rfl chk_5_16

theorem cert_5_17 : BlockPSD 5 17 :=
  posSemidef_of_chk _ (blockA 5 17) (blockA_symm 5 17) _ _ _ _ alphaW (blockA_bound 5 17)
    cL_5_17 cE_5_17 cPL_5_17 rfl chk_5_17

theorem cert_5_18 : BlockPSD 5 18 :=
  posSemidef_of_chk _ (blockA 5 18) (blockA_symm 5 18) _ _ _ _ alphaW (blockA_bound 5 18)
    cL_5_18 cE_5_18 cPL_5_18 rfl chk_5_18

theorem cert_5_19 : BlockPSD 5 19 :=
  posSemidef_of_chk _ (blockA 5 19) (blockA_symm 5 19) _ _ _ _ alphaW (blockA_bound 5 19)
    cL_5_19 cE_5_19 cPL_5_19 rfl chk_5_19

theorem cert_5_20 : BlockPSD 5 20 :=
  posSemidef_of_chk _ (blockA 5 20) (blockA_symm 5 20) _ _ _ _ alphaW (blockA_bound 5 20)
    cL_5_20 cE_5_20 cPL_5_20 rfl chk_5_20

theorem cert_5_21 : BlockPSD 5 21 :=
  posSemidef_of_chk _ (blockA 5 21) (blockA_symm 5 21) _ _ _ _ alphaW (blockA_bound 5 21)
    cL_5_21 cE_5_21 cPL_5_21 rfl chk_5_21

theorem cert_5_22 : BlockPSD 5 22 :=
  posSemidef_of_chk _ (blockA 5 22) (blockA_symm 5 22) _ _ _ _ alphaW (blockA_bound 5 22)
    cL_5_22 cE_5_22 cPL_5_22 rfl chk_5_22

theorem cert_5_23 : BlockPSD 5 23 :=
  posSemidef_of_chk _ (blockA 5 23) (blockA_symm 5 23) _ _ _ _ alphaW (blockA_bound 5 23)
    cL_5_23 cE_5_23 cPL_5_23 rfl chk_5_23

theorem cert_5_24 : BlockPSD 5 24 :=
  posSemidef_of_chk _ (blockA 5 24) (blockA_symm 5 24) _ _ _ _ alphaW (blockA_bound 5 24)
    cL_5_24 cE_5_24 cPL_5_24 rfl chk_5_24

theorem cert_5_25 : BlockPSD 5 25 :=
  posSemidef_of_chk _ (blockA 5 25) (blockA_symm 5 25) _ _ _ _ alphaW (blockA_bound 5 25)
    cL_5_25 cE_5_25 cPL_5_25 rfl chk_5_25

theorem cert_6_6 : BlockPSD 6 6 :=
  posSemidef_of_chk _ (blockA 6 6) (blockA_symm 6 6) _ _ _ _ alphaW (blockA_bound 6 6)
    cL_6_6 cE_6_6 cPL_6_6 rfl chk_6_6

theorem cert_6_7 : BlockPSD 6 7 :=
  posSemidef_of_chk _ (blockA 6 7) (blockA_symm 6 7) _ _ _ _ alphaW (blockA_bound 6 7)
    cL_6_7 cE_6_7 cPL_6_7 rfl chk_6_7

theorem cert_6_8 : BlockPSD 6 8 :=
  posSemidef_of_chk _ (blockA 6 8) (blockA_symm 6 8) _ _ _ _ alphaW (blockA_bound 6 8)
    cL_6_8 cE_6_8 cPL_6_8 rfl chk_6_8

theorem cert_6_9 : BlockPSD 6 9 :=
  posSemidef_of_chk _ (blockA 6 9) (blockA_symm 6 9) _ _ _ _ alphaW (blockA_bound 6 9)
    cL_6_9 cE_6_9 cPL_6_9 rfl chk_6_9

theorem cert_6_10 : BlockPSD 6 10 :=
  posSemidef_of_chk _ (blockA 6 10) (blockA_symm 6 10) _ _ _ _ alphaW (blockA_bound 6 10)
    cL_6_10 cE_6_10 cPL_6_10 rfl chk_6_10

theorem cert_6_11 : BlockPSD 6 11 :=
  posSemidef_of_chk _ (blockA 6 11) (blockA_symm 6 11) _ _ _ _ alphaW (blockA_bound 6 11)
    cL_6_11 cE_6_11 cPL_6_11 rfl chk_6_11

theorem cert_6_12 : BlockPSD 6 12 :=
  posSemidef_of_chk _ (blockA 6 12) (blockA_symm 6 12) _ _ _ _ alphaW (blockA_bound 6 12)
    cL_6_12 cE_6_12 cPL_6_12 rfl chk_6_12

theorem cert_6_14 : BlockPSD 6 14 :=
  posSemidef_of_chk _ (blockA 6 14) (blockA_symm 6 14) _ _ _ _ alphaW (blockA_bound 6 14)
    cL_6_14 cE_6_14 cPL_6_14 rfl chk_6_14

theorem cert_6_15 : BlockPSD 6 15 :=
  posSemidef_of_chk _ (blockA 6 15) (blockA_symm 6 15) _ _ _ _ alphaW (blockA_bound 6 15)
    cL_6_15 cE_6_15 cPL_6_15 rfl chk_6_15

theorem cert_6_16 : BlockPSD 6 16 :=
  posSemidef_of_chk _ (blockA 6 16) (blockA_symm 6 16) _ _ _ _ alphaW (blockA_bound 6 16)
    cL_6_16 cE_6_16 cPL_6_16 rfl chk_6_16

theorem cert_6_17 : BlockPSD 6 17 :=
  posSemidef_of_chk _ (blockA 6 17) (blockA_symm 6 17) _ _ _ _ alphaW (blockA_bound 6 17)
    cL_6_17 cE_6_17 cPL_6_17 rfl chk_6_17

theorem cert_6_18 : BlockPSD 6 18 :=
  posSemidef_of_chk _ (blockA 6 18) (blockA_symm 6 18) _ _ _ _ alphaW (blockA_bound 6 18)
    cL_6_18 cE_6_18 cPL_6_18 rfl chk_6_18

theorem cert_6_19 : BlockPSD 6 19 :=
  posSemidef_of_chk _ (blockA 6 19) (blockA_symm 6 19) _ _ _ _ alphaW (blockA_bound 6 19)
    cL_6_19 cE_6_19 cPL_6_19 rfl chk_6_19

theorem cert_6_20 : BlockPSD 6 20 :=
  posSemidef_of_chk _ (blockA 6 20) (blockA_symm 6 20) _ _ _ _ alphaW (blockA_bound 6 20)
    cL_6_20 cE_6_20 cPL_6_20 rfl chk_6_20

theorem cert_6_21 : BlockPSD 6 21 :=
  posSemidef_of_chk _ (blockA 6 21) (blockA_symm 6 21) _ _ _ _ alphaW (blockA_bound 6 21)
    cL_6_21 cE_6_21 cPL_6_21 rfl chk_6_21

theorem cert_6_22 : BlockPSD 6 22 :=
  posSemidef_of_chk _ (blockA 6 22) (blockA_symm 6 22) _ _ _ _ alphaW (blockA_bound 6 22)
    cL_6_22 cE_6_22 cPL_6_22 rfl chk_6_22

theorem cert_6_23 : BlockPSD 6 23 :=
  posSemidef_of_chk _ (blockA 6 23) (blockA_symm 6 23) _ _ _ _ alphaW (blockA_bound 6 23)
    cL_6_23 cE_6_23 cPL_6_23 rfl chk_6_23

theorem cert_6_24 : BlockPSD 6 24 :=
  posSemidef_of_chk _ (blockA 6 24) (blockA_symm 6 24) _ _ _ _ alphaW (blockA_bound 6 24)
    cL_6_24 cE_6_24 cPL_6_24 rfl chk_6_24

theorem cert_6_25 : BlockPSD 6 25 :=
  posSemidef_of_chk _ (blockA 6 25) (blockA_symm 6 25) _ _ _ _ alphaW (blockA_bound 6 25)
    cL_6_25 cE_6_25 cPL_6_25 rfl chk_6_25

theorem cert_7_7 : BlockPSD 7 7 :=
  posSemidef_of_chk _ (blockA 7 7) (blockA_symm 7 7) _ _ _ _ alphaW (blockA_bound 7 7)
    cL_7_7 cE_7_7 cPL_7_7 rfl chk_7_7

theorem cert_7_8 : BlockPSD 7 8 :=
  posSemidef_of_chk _ (blockA 7 8) (blockA_symm 7 8) _ _ _ _ alphaW (blockA_bound 7 8)
    cL_7_8 cE_7_8 cPL_7_8 rfl chk_7_8

theorem cert_7_9 : BlockPSD 7 9 :=
  posSemidef_of_chk _ (blockA 7 9) (blockA_symm 7 9) _ _ _ _ alphaW (blockA_bound 7 9)
    cL_7_9 cE_7_9 cPL_7_9 rfl chk_7_9

theorem cert_7_10 : BlockPSD 7 10 :=
  posSemidef_of_chk _ (blockA 7 10) (blockA_symm 7 10) _ _ _ _ alphaW (blockA_bound 7 10)
    cL_7_10 cE_7_10 cPL_7_10 rfl chk_7_10

theorem cert_7_11 : BlockPSD 7 11 :=
  posSemidef_of_chk _ (blockA 7 11) (blockA_symm 7 11) _ _ _ _ alphaW (blockA_bound 7 11)
    cL_7_11 cE_7_11 cPL_7_11 rfl chk_7_11

theorem cert_7_12 : BlockPSD 7 12 :=
  posSemidef_of_chk _ (blockA 7 12) (blockA_symm 7 12) _ _ _ _ alphaW (blockA_bound 7 12)
    cL_7_12 cE_7_12 cPL_7_12 rfl chk_7_12

theorem cert_7_14 : BlockPSD 7 14 :=
  posSemidef_of_chk _ (blockA 7 14) (blockA_symm 7 14) _ _ _ _ alphaW (blockA_bound 7 14)
    cL_7_14 cE_7_14 cPL_7_14 rfl chk_7_14

theorem cert_7_15 : BlockPSD 7 15 :=
  posSemidef_of_chk _ (blockA 7 15) (blockA_symm 7 15) _ _ _ _ alphaW (blockA_bound 7 15)
    cL_7_15 cE_7_15 cPL_7_15 rfl chk_7_15

theorem cert_7_16 : BlockPSD 7 16 :=
  posSemidef_of_chk _ (blockA 7 16) (blockA_symm 7 16) _ _ _ _ alphaW (blockA_bound 7 16)
    cL_7_16 cE_7_16 cPL_7_16 rfl chk_7_16

theorem cert_7_17 : BlockPSD 7 17 :=
  posSemidef_of_chk _ (blockA 7 17) (blockA_symm 7 17) _ _ _ _ alphaW (blockA_bound 7 17)
    cL_7_17 cE_7_17 cPL_7_17 rfl chk_7_17

theorem cert_7_18 : BlockPSD 7 18 :=
  posSemidef_of_chk _ (blockA 7 18) (blockA_symm 7 18) _ _ _ _ alphaW (blockA_bound 7 18)
    cL_7_18 cE_7_18 cPL_7_18 rfl chk_7_18

theorem cert_7_19 : BlockPSD 7 19 :=
  posSemidef_of_chk _ (blockA 7 19) (blockA_symm 7 19) _ _ _ _ alphaW (blockA_bound 7 19)
    cL_7_19 cE_7_19 cPL_7_19 rfl chk_7_19

theorem cert_7_20 : BlockPSD 7 20 :=
  posSemidef_of_chk _ (blockA 7 20) (blockA_symm 7 20) _ _ _ _ alphaW (blockA_bound 7 20)
    cL_7_20 cE_7_20 cPL_7_20 rfl chk_7_20

theorem cert_7_21 : BlockPSD 7 21 :=
  posSemidef_of_chk _ (blockA 7 21) (blockA_symm 7 21) _ _ _ _ alphaW (blockA_bound 7 21)
    cL_7_21 cE_7_21 cPL_7_21 rfl chk_7_21

theorem cert_7_22 : BlockPSD 7 22 :=
  posSemidef_of_chk _ (blockA 7 22) (blockA_symm 7 22) _ _ _ _ alphaW (blockA_bound 7 22)
    cL_7_22 cE_7_22 cPL_7_22 rfl chk_7_22

theorem cert_7_23 : BlockPSD 7 23 :=
  posSemidef_of_chk _ (blockA 7 23) (blockA_symm 7 23) _ _ _ _ alphaW (blockA_bound 7 23)
    cL_7_23 cE_7_23 cPL_7_23 rfl chk_7_23

theorem cert_7_24 : BlockPSD 7 24 :=
  posSemidef_of_chk _ (blockA 7 24) (blockA_symm 7 24) _ _ _ _ alphaW (blockA_bound 7 24)
    cL_7_24 cE_7_24 cPL_7_24 rfl chk_7_24

theorem cert_7_25 : BlockPSD 7 25 :=
  posSemidef_of_chk _ (blockA 7 25) (blockA_symm 7 25) _ _ _ _ alphaW (blockA_bound 7 25)
    cL_7_25 cE_7_25 cPL_7_25 rfl chk_7_25

theorem cert_8_8 : BlockPSD 8 8 :=
  posSemidef_of_chk _ (blockA 8 8) (blockA_symm 8 8) _ _ _ _ alphaW (blockA_bound 8 8)
    cL_8_8 cE_8_8 cPL_8_8 rfl chk_8_8

theorem cert_8_9 : BlockPSD 8 9 :=
  posSemidef_of_chk _ (blockA 8 9) (blockA_symm 8 9) _ _ _ _ alphaW (blockA_bound 8 9)
    cL_8_9 cE_8_9 cPL_8_9 rfl chk_8_9

theorem cert_8_10 : BlockPSD 8 10 :=
  posSemidef_of_chk _ (blockA 8 10) (blockA_symm 8 10) _ _ _ _ alphaW (blockA_bound 8 10)
    cL_8_10 cE_8_10 cPL_8_10 rfl chk_8_10

theorem cert_8_11 : BlockPSD 8 11 :=
  posSemidef_of_chk _ (blockA 8 11) (blockA_symm 8 11) _ _ _ _ alphaW (blockA_bound 8 11)
    cL_8_11 cE_8_11 cPL_8_11 rfl chk_8_11

theorem cert_8_12 : BlockPSD 8 12 :=
  posSemidef_of_chk _ (blockA 8 12) (blockA_symm 8 12) _ _ _ _ alphaW (blockA_bound 8 12)
    cL_8_12 cE_8_12 cPL_8_12 rfl chk_8_12

theorem cert_8_14 : BlockPSD 8 14 :=
  posSemidef_of_chk _ (blockA 8 14) (blockA_symm 8 14) _ _ _ _ alphaW (blockA_bound 8 14)
    cL_8_14 cE_8_14 cPL_8_14 rfl chk_8_14

theorem cert_8_15 : BlockPSD 8 15 :=
  posSemidef_of_chk _ (blockA 8 15) (blockA_symm 8 15) _ _ _ _ alphaW (blockA_bound 8 15)
    cL_8_15 cE_8_15 cPL_8_15 rfl chk_8_15

theorem cert_8_16 : BlockPSD 8 16 :=
  posSemidef_of_chk _ (blockA 8 16) (blockA_symm 8 16) _ _ _ _ alphaW (blockA_bound 8 16)
    cL_8_16 cE_8_16 cPL_8_16 rfl chk_8_16

theorem cert_8_17 : BlockPSD 8 17 :=
  posSemidef_of_chk _ (blockA 8 17) (blockA_symm 8 17) _ _ _ _ alphaW (blockA_bound 8 17)
    cL_8_17 cE_8_17 cPL_8_17 rfl chk_8_17

theorem cert_8_18 : BlockPSD 8 18 :=
  posSemidef_of_chk _ (blockA 8 18) (blockA_symm 8 18) _ _ _ _ alphaW (blockA_bound 8 18)
    cL_8_18 cE_8_18 cPL_8_18 rfl chk_8_18

theorem cert_8_19 : BlockPSD 8 19 :=
  posSemidef_of_chk _ (blockA 8 19) (blockA_symm 8 19) _ _ _ _ alphaW (blockA_bound 8 19)
    cL_8_19 cE_8_19 cPL_8_19 rfl chk_8_19

theorem cert_8_20 : BlockPSD 8 20 :=
  posSemidef_of_chk _ (blockA 8 20) (blockA_symm 8 20) _ _ _ _ alphaW (blockA_bound 8 20)
    cL_8_20 cE_8_20 cPL_8_20 rfl chk_8_20

theorem cert_8_21 : BlockPSD 8 21 :=
  posSemidef_of_chk _ (blockA 8 21) (blockA_symm 8 21) _ _ _ _ alphaW (blockA_bound 8 21)
    cL_8_21 cE_8_21 cPL_8_21 rfl chk_8_21

theorem cert_8_22 : BlockPSD 8 22 :=
  posSemidef_of_chk _ (blockA 8 22) (blockA_symm 8 22) _ _ _ _ alphaW (blockA_bound 8 22)
    cL_8_22 cE_8_22 cPL_8_22 rfl chk_8_22

theorem cert_8_23 : BlockPSD 8 23 :=
  posSemidef_of_chk _ (blockA 8 23) (blockA_symm 8 23) _ _ _ _ alphaW (blockA_bound 8 23)
    cL_8_23 cE_8_23 cPL_8_23 rfl chk_8_23

theorem cert_8_24 : BlockPSD 8 24 :=
  posSemidef_of_chk _ (blockA 8 24) (blockA_symm 8 24) _ _ _ _ alphaW (blockA_bound 8 24)
    cL_8_24 cE_8_24 cPL_8_24 rfl chk_8_24

theorem cert_8_25 : BlockPSD 8 25 :=
  posSemidef_of_chk _ (blockA 8 25) (blockA_symm 8 25) _ _ _ _ alphaW (blockA_bound 8 25)
    cL_8_25 cE_8_25 cPL_8_25 rfl chk_8_25

theorem cert_9_9 : BlockPSD 9 9 :=
  posSemidef_of_chk _ (blockA 9 9) (blockA_symm 9 9) _ _ _ _ alphaW (blockA_bound 9 9)
    cL_9_9 cE_9_9 cPL_9_9 rfl chk_9_9

theorem cert_9_10 : BlockPSD 9 10 :=
  posSemidef_of_chk _ (blockA 9 10) (blockA_symm 9 10) _ _ _ _ alphaW (blockA_bound 9 10)
    cL_9_10 cE_9_10 cPL_9_10 rfl chk_9_10

theorem cert_9_11 : BlockPSD 9 11 :=
  posSemidef_of_chk _ (blockA 9 11) (blockA_symm 9 11) _ _ _ _ alphaW (blockA_bound 9 11)
    cL_9_11 cE_9_11 cPL_9_11 rfl chk_9_11

theorem cert_9_12 : BlockPSD 9 12 :=
  posSemidef_of_chk _ (blockA 9 12) (blockA_symm 9 12) _ _ _ _ alphaW (blockA_bound 9 12)
    cL_9_12 cE_9_12 cPL_9_12 rfl chk_9_12

theorem cert_9_14 : BlockPSD 9 14 :=
  posSemidef_of_chk _ (blockA 9 14) (blockA_symm 9 14) _ _ _ _ alphaW (blockA_bound 9 14)
    cL_9_14 cE_9_14 cPL_9_14 rfl chk_9_14

theorem cert_9_15 : BlockPSD 9 15 :=
  posSemidef_of_chk _ (blockA 9 15) (blockA_symm 9 15) _ _ _ _ alphaW (blockA_bound 9 15)
    cL_9_15 cE_9_15 cPL_9_15 rfl chk_9_15

theorem cert_9_16 : BlockPSD 9 16 :=
  posSemidef_of_chk _ (blockA 9 16) (blockA_symm 9 16) _ _ _ _ alphaW (blockA_bound 9 16)
    cL_9_16 cE_9_16 cPL_9_16 rfl chk_9_16

theorem cert_9_17 : BlockPSD 9 17 :=
  posSemidef_of_chk _ (blockA 9 17) (blockA_symm 9 17) _ _ _ _ alphaW (blockA_bound 9 17)
    cL_9_17 cE_9_17 cPL_9_17 rfl chk_9_17

theorem cert_9_18 : BlockPSD 9 18 :=
  posSemidef_of_chk _ (blockA 9 18) (blockA_symm 9 18) _ _ _ _ alphaW (blockA_bound 9 18)
    cL_9_18 cE_9_18 cPL_9_18 rfl chk_9_18

theorem cert_9_19 : BlockPSD 9 19 :=
  posSemidef_of_chk _ (blockA 9 19) (blockA_symm 9 19) _ _ _ _ alphaW (blockA_bound 9 19)
    cL_9_19 cE_9_19 cPL_9_19 rfl chk_9_19

theorem cert_9_20 : BlockPSD 9 20 :=
  posSemidef_of_chk _ (blockA 9 20) (blockA_symm 9 20) _ _ _ _ alphaW (blockA_bound 9 20)
    cL_9_20 cE_9_20 cPL_9_20 rfl chk_9_20

theorem cert_9_21 : BlockPSD 9 21 :=
  posSemidef_of_chk _ (blockA 9 21) (blockA_symm 9 21) _ _ _ _ alphaW (blockA_bound 9 21)
    cL_9_21 cE_9_21 cPL_9_21 rfl chk_9_21

theorem cert_9_22 : BlockPSD 9 22 :=
  posSemidef_of_chk _ (blockA 9 22) (blockA_symm 9 22) _ _ _ _ alphaW (blockA_bound 9 22)
    cL_9_22 cE_9_22 cPL_9_22 rfl chk_9_22

theorem cert_9_23 : BlockPSD 9 23 :=
  posSemidef_of_chk _ (blockA 9 23) (blockA_symm 9 23) _ _ _ _ alphaW (blockA_bound 9 23)
    cL_9_23 cE_9_23 cPL_9_23 rfl chk_9_23

theorem cert_9_24 : BlockPSD 9 24 :=
  posSemidef_of_chk _ (blockA 9 24) (blockA_symm 9 24) _ _ _ _ alphaW (blockA_bound 9 24)
    cL_9_24 cE_9_24 cPL_9_24 rfl chk_9_24

theorem cert_9_25 : BlockPSD 9 25 :=
  posSemidef_of_chk _ (blockA 9 25) (blockA_symm 9 25) _ _ _ _ alphaW (blockA_bound 9 25)
    cL_9_25 cE_9_25 cPL_9_25 rfl chk_9_25

theorem cert_10_10 : BlockPSD 10 10 :=
  posSemidef_of_chk _ (blockA 10 10) (blockA_symm 10 10) _ _ _ _ alphaW (blockA_bound 10 10)
    cL_10_10 cE_10_10 cPL_10_10 rfl chk_10_10

theorem cert_10_11 : BlockPSD 10 11 :=
  posSemidef_of_chk _ (blockA 10 11) (blockA_symm 10 11) _ _ _ _ alphaW (blockA_bound 10 11)
    cL_10_11 cE_10_11 cPL_10_11 rfl chk_10_11

theorem cert_10_12 : BlockPSD 10 12 :=
  posSemidef_of_chk _ (blockA 10 12) (blockA_symm 10 12) _ _ _ _ alphaW (blockA_bound 10 12)
    cL_10_12 cE_10_12 cPL_10_12 rfl chk_10_12

theorem cert_10_14 : BlockPSD 10 14 :=
  posSemidef_of_chk _ (blockA 10 14) (blockA_symm 10 14) _ _ _ _ alphaW (blockA_bound 10 14)
    cL_10_14 cE_10_14 cPL_10_14 rfl chk_10_14

theorem cert_10_15 : BlockPSD 10 15 :=
  posSemidef_of_chk _ (blockA 10 15) (blockA_symm 10 15) _ _ _ _ alphaW (blockA_bound 10 15)
    cL_10_15 cE_10_15 cPL_10_15 rfl chk_10_15

theorem cert_10_16 : BlockPSD 10 16 :=
  posSemidef_of_chk _ (blockA 10 16) (blockA_symm 10 16) _ _ _ _ alphaW (blockA_bound 10 16)
    cL_10_16 cE_10_16 cPL_10_16 rfl chk_10_16

theorem cert_10_17 : BlockPSD 10 17 :=
  posSemidef_of_chk _ (blockA 10 17) (blockA_symm 10 17) _ _ _ _ alphaW (blockA_bound 10 17)
    cL_10_17 cE_10_17 cPL_10_17 rfl chk_10_17

theorem cert_10_18 : BlockPSD 10 18 :=
  posSemidef_of_chk _ (blockA 10 18) (blockA_symm 10 18) _ _ _ _ alphaW (blockA_bound 10 18)
    cL_10_18 cE_10_18 cPL_10_18 rfl chk_10_18

theorem cert_10_19 : BlockPSD 10 19 :=
  posSemidef_of_chk _ (blockA 10 19) (blockA_symm 10 19) _ _ _ _ alphaW (blockA_bound 10 19)
    cL_10_19 cE_10_19 cPL_10_19 rfl chk_10_19

theorem cert_10_20 : BlockPSD 10 20 :=
  posSemidef_of_chk _ (blockA 10 20) (blockA_symm 10 20) _ _ _ _ alphaW (blockA_bound 10 20)
    cL_10_20 cE_10_20 cPL_10_20 rfl chk_10_20

theorem cert_10_21 : BlockPSD 10 21 :=
  posSemidef_of_chk _ (blockA 10 21) (blockA_symm 10 21) _ _ _ _ alphaW (blockA_bound 10 21)
    cL_10_21 cE_10_21 cPL_10_21 rfl chk_10_21

theorem cert_10_22 : BlockPSD 10 22 :=
  posSemidef_of_chk _ (blockA 10 22) (blockA_symm 10 22) _ _ _ _ alphaW (blockA_bound 10 22)
    cL_10_22 cE_10_22 cPL_10_22 rfl chk_10_22

theorem cert_10_23 : BlockPSD 10 23 :=
  posSemidef_of_chk _ (blockA 10 23) (blockA_symm 10 23) _ _ _ _ alphaW (blockA_bound 10 23)
    cL_10_23 cE_10_23 cPL_10_23 rfl chk_10_23

theorem cert_10_24 : BlockPSD 10 24 :=
  posSemidef_of_chk _ (blockA 10 24) (blockA_symm 10 24) _ _ _ _ alphaW (blockA_bound 10 24)
    cL_10_24 cE_10_24 cPL_10_24 rfl chk_10_24

theorem cert_10_25 : BlockPSD 10 25 :=
  posSemidef_of_chk _ (blockA 10 25) (blockA_symm 10 25) _ _ _ _ alphaW (blockA_bound 10 25)
    cL_10_25 cE_10_25 cPL_10_25 rfl chk_10_25

theorem cert_11_11 : BlockPSD 11 11 :=
  posSemidef_of_chk _ (blockA 11 11) (blockA_symm 11 11) _ _ _ _ alphaW (blockA_bound 11 11)
    cL_11_11 cE_11_11 cPL_11_11 rfl chk_11_11

theorem cert_11_12 : BlockPSD 11 12 :=
  posSemidef_of_chk _ (blockA 11 12) (blockA_symm 11 12) _ _ _ _ alphaW (blockA_bound 11 12)
    cL_11_12 cE_11_12 cPL_11_12 rfl chk_11_12

theorem cert_11_14 : BlockPSD 11 14 :=
  posSemidef_of_chk _ (blockA 11 14) (blockA_symm 11 14) _ _ _ _ alphaW (blockA_bound 11 14)
    cL_11_14 cE_11_14 cPL_11_14 rfl chk_11_14

theorem cert_11_15 : BlockPSD 11 15 :=
  posSemidef_of_chk _ (blockA 11 15) (blockA_symm 11 15) _ _ _ _ alphaW (blockA_bound 11 15)
    cL_11_15 cE_11_15 cPL_11_15 rfl chk_11_15

theorem cert_11_16 : BlockPSD 11 16 :=
  posSemidef_of_chk _ (blockA 11 16) (blockA_symm 11 16) _ _ _ _ alphaW (blockA_bound 11 16)
    cL_11_16 cE_11_16 cPL_11_16 rfl chk_11_16

theorem cert_11_17 : BlockPSD 11 17 :=
  posSemidef_of_chk _ (blockA 11 17) (blockA_symm 11 17) _ _ _ _ alphaW (blockA_bound 11 17)
    cL_11_17 cE_11_17 cPL_11_17 rfl chk_11_17

theorem cert_11_18 : BlockPSD 11 18 :=
  posSemidef_of_chk _ (blockA 11 18) (blockA_symm 11 18) _ _ _ _ alphaW (blockA_bound 11 18)
    cL_11_18 cE_11_18 cPL_11_18 rfl chk_11_18

theorem cert_11_19 : BlockPSD 11 19 :=
  posSemidef_of_chk _ (blockA 11 19) (blockA_symm 11 19) _ _ _ _ alphaW (blockA_bound 11 19)
    cL_11_19 cE_11_19 cPL_11_19 rfl chk_11_19

theorem cert_11_20 : BlockPSD 11 20 :=
  posSemidef_of_chk _ (blockA 11 20) (blockA_symm 11 20) _ _ _ _ alphaW (blockA_bound 11 20)
    cL_11_20 cE_11_20 cPL_11_20 rfl chk_11_20

theorem cert_11_21 : BlockPSD 11 21 :=
  posSemidef_of_chk _ (blockA 11 21) (blockA_symm 11 21) _ _ _ _ alphaW (blockA_bound 11 21)
    cL_11_21 cE_11_21 cPL_11_21 rfl chk_11_21

theorem cert_11_22 : BlockPSD 11 22 :=
  posSemidef_of_chk _ (blockA 11 22) (blockA_symm 11 22) _ _ _ _ alphaW (blockA_bound 11 22)
    cL_11_22 cE_11_22 cPL_11_22 rfl chk_11_22

theorem cert_11_23 : BlockPSD 11 23 :=
  posSemidef_of_chk _ (blockA 11 23) (blockA_symm 11 23) _ _ _ _ alphaW (blockA_bound 11 23)
    cL_11_23 cE_11_23 cPL_11_23 rfl chk_11_23

theorem cert_11_24 : BlockPSD 11 24 :=
  posSemidef_of_chk _ (blockA 11 24) (blockA_symm 11 24) _ _ _ _ alphaW (blockA_bound 11 24)
    cL_11_24 cE_11_24 cPL_11_24 rfl chk_11_24

theorem cert_11_25 : BlockPSD 11 25 :=
  posSemidef_of_chk _ (blockA 11 25) (blockA_symm 11 25) _ _ _ _ alphaW (blockA_bound 11 25)
    cL_11_25 cE_11_25 cPL_11_25 rfl chk_11_25

theorem cert_12_12 : BlockPSD 12 12 :=
  posSemidef_of_chk _ (blockA 12 12) (blockA_symm 12 12) _ _ _ _ alphaW (blockA_bound 12 12)
    cL_12_12 cE_12_12 cPL_12_12 rfl chk_12_12

theorem cert_12_14 : BlockPSD 12 14 :=
  posSemidef_of_chk _ (blockA 12 14) (blockA_symm 12 14) _ _ _ _ alphaW (blockA_bound 12 14)
    cL_12_14 cE_12_14 cPL_12_14 rfl chk_12_14

theorem cert_12_15 : BlockPSD 12 15 :=
  posSemidef_of_chk _ (blockA 12 15) (blockA_symm 12 15) _ _ _ _ alphaW (blockA_bound 12 15)
    cL_12_15 cE_12_15 cPL_12_15 rfl chk_12_15

theorem cert_12_16 : BlockPSD 12 16 :=
  posSemidef_of_chk _ (blockA 12 16) (blockA_symm 12 16) _ _ _ _ alphaW (blockA_bound 12 16)
    cL_12_16 cE_12_16 cPL_12_16 rfl chk_12_16

theorem cert_12_17 : BlockPSD 12 17 :=
  posSemidef_of_chk _ (blockA 12 17) (blockA_symm 12 17) _ _ _ _ alphaW (blockA_bound 12 17)
    cL_12_17 cE_12_17 cPL_12_17 rfl chk_12_17

theorem cert_12_18 : BlockPSD 12 18 :=
  posSemidef_of_chk _ (blockA 12 18) (blockA_symm 12 18) _ _ _ _ alphaW (blockA_bound 12 18)
    cL_12_18 cE_12_18 cPL_12_18 rfl chk_12_18

theorem cert_12_19 : BlockPSD 12 19 :=
  posSemidef_of_chk _ (blockA 12 19) (blockA_symm 12 19) _ _ _ _ alphaW (blockA_bound 12 19)
    cL_12_19 cE_12_19 cPL_12_19 rfl chk_12_19

theorem cert_12_20 : BlockPSD 12 20 :=
  posSemidef_of_chk _ (blockA 12 20) (blockA_symm 12 20) _ _ _ _ alphaW (blockA_bound 12 20)
    cL_12_20 cE_12_20 cPL_12_20 rfl chk_12_20

theorem cert_12_21 : BlockPSD 12 21 :=
  posSemidef_of_chk _ (blockA 12 21) (blockA_symm 12 21) _ _ _ _ alphaW (blockA_bound 12 21)
    cL_12_21 cE_12_21 cPL_12_21 rfl chk_12_21

theorem cert_12_22 : BlockPSD 12 22 :=
  posSemidef_of_chk _ (blockA 12 22) (blockA_symm 12 22) _ _ _ _ alphaW (blockA_bound 12 22)
    cL_12_22 cE_12_22 cPL_12_22 rfl chk_12_22

theorem cert_12_23 : BlockPSD 12 23 :=
  posSemidef_of_chk _ (blockA 12 23) (blockA_symm 12 23) _ _ _ _ alphaW (blockA_bound 12 23)
    cL_12_23 cE_12_23 cPL_12_23 rfl chk_12_23

theorem cert_12_24 : BlockPSD 12 24 :=
  posSemidef_of_chk _ (blockA 12 24) (blockA_symm 12 24) _ _ _ _ alphaW (blockA_bound 12 24)
    cL_12_24 cE_12_24 cPL_12_24 rfl chk_12_24

theorem cert_12_25 : BlockPSD 12 25 :=
  posSemidef_of_chk _ (blockA 12 25) (blockA_symm 12 25) _ _ _ _ alphaW (blockA_bound 12 25)
    cL_12_25 cE_12_25 cPL_12_25 rfl chk_12_25

theorem cert_14_14 : BlockPSD 14 14 :=
  posSemidef_of_chk _ (blockA 14 14) (blockA_symm 14 14) _ _ _ _ alphaW (blockA_bound 14 14)
    cL_14_14 cE_14_14 cPL_14_14 rfl chk_14_14

theorem cert_14_15 : BlockPSD 14 15 :=
  posSemidef_of_chk _ (blockA 14 15) (blockA_symm 14 15) _ _ _ _ alphaW (blockA_bound 14 15)
    cL_14_15 cE_14_15 cPL_14_15 rfl chk_14_15

theorem cert_14_16 : BlockPSD 14 16 :=
  posSemidef_of_chk _ (blockA 14 16) (blockA_symm 14 16) _ _ _ _ alphaW (blockA_bound 14 16)
    cL_14_16 cE_14_16 cPL_14_16 rfl chk_14_16

theorem cert_14_17 : BlockPSD 14 17 :=
  posSemidef_of_chk _ (blockA 14 17) (blockA_symm 14 17) _ _ _ _ alphaW (blockA_bound 14 17)
    cL_14_17 cE_14_17 cPL_14_17 rfl chk_14_17

theorem cert_14_18 : BlockPSD 14 18 :=
  posSemidef_of_chk _ (blockA 14 18) (blockA_symm 14 18) _ _ _ _ alphaW (blockA_bound 14 18)
    cL_14_18 cE_14_18 cPL_14_18 rfl chk_14_18

theorem cert_14_19 : BlockPSD 14 19 :=
  posSemidef_of_chk _ (blockA 14 19) (blockA_symm 14 19) _ _ _ _ alphaW (blockA_bound 14 19)
    cL_14_19 cE_14_19 cPL_14_19 rfl chk_14_19

theorem cert_14_20 : BlockPSD 14 20 :=
  posSemidef_of_chk _ (blockA 14 20) (blockA_symm 14 20) _ _ _ _ alphaW (blockA_bound 14 20)
    cL_14_20 cE_14_20 cPL_14_20 rfl chk_14_20

theorem cert_14_21 : BlockPSD 14 21 :=
  posSemidef_of_chk _ (blockA 14 21) (blockA_symm 14 21) _ _ _ _ alphaW (blockA_bound 14 21)
    cL_14_21 cE_14_21 cPL_14_21 rfl chk_14_21

theorem cert_14_22 : BlockPSD 14 22 :=
  posSemidef_of_chk _ (blockA 14 22) (blockA_symm 14 22) _ _ _ _ alphaW (blockA_bound 14 22)
    cL_14_22 cE_14_22 cPL_14_22 rfl chk_14_22

theorem cert_14_23 : BlockPSD 14 23 :=
  posSemidef_of_chk _ (blockA 14 23) (blockA_symm 14 23) _ _ _ _ alphaW (blockA_bound 14 23)
    cL_14_23 cE_14_23 cPL_14_23 rfl chk_14_23

theorem cert_14_24 : BlockPSD 14 24 :=
  posSemidef_of_chk _ (blockA 14 24) (blockA_symm 14 24) _ _ _ _ alphaW (blockA_bound 14 24)
    cL_14_24 cE_14_24 cPL_14_24 rfl chk_14_24

theorem cert_14_25 : BlockPSD 14 25 :=
  posSemidef_of_chk _ (blockA 14 25) (blockA_symm 14 25) _ _ _ _ alphaW (blockA_bound 14 25)
    cL_14_25 cE_14_25 cPL_14_25 rfl chk_14_25

theorem cert_15_15 : BlockPSD 15 15 :=
  posSemidef_of_chk _ (blockA 15 15) (blockA_symm 15 15) _ _ _ _ alphaW (blockA_bound 15 15)
    cL_15_15 cE_15_15 cPL_15_15 rfl chk_15_15

theorem cert_15_16 : BlockPSD 15 16 :=
  posSemidef_of_chk _ (blockA 15 16) (blockA_symm 15 16) _ _ _ _ alphaW (blockA_bound 15 16)
    cL_15_16 cE_15_16 cPL_15_16 rfl chk_15_16

theorem cert_15_17 : BlockPSD 15 17 :=
  posSemidef_of_chk _ (blockA 15 17) (blockA_symm 15 17) _ _ _ _ alphaW (blockA_bound 15 17)
    cL_15_17 cE_15_17 cPL_15_17 rfl chk_15_17

theorem cert_15_18 : BlockPSD 15 18 :=
  posSemidef_of_chk _ (blockA 15 18) (blockA_symm 15 18) _ _ _ _ alphaW (blockA_bound 15 18)
    cL_15_18 cE_15_18 cPL_15_18 rfl chk_15_18

theorem cert_15_19 : BlockPSD 15 19 :=
  posSemidef_of_chk _ (blockA 15 19) (blockA_symm 15 19) _ _ _ _ alphaW (blockA_bound 15 19)
    cL_15_19 cE_15_19 cPL_15_19 rfl chk_15_19

theorem cert_15_20 : BlockPSD 15 20 :=
  posSemidef_of_chk _ (blockA 15 20) (blockA_symm 15 20) _ _ _ _ alphaW (blockA_bound 15 20)
    cL_15_20 cE_15_20 cPL_15_20 rfl chk_15_20

theorem cert_15_21 : BlockPSD 15 21 :=
  posSemidef_of_chk _ (blockA 15 21) (blockA_symm 15 21) _ _ _ _ alphaW (blockA_bound 15 21)
    cL_15_21 cE_15_21 cPL_15_21 rfl chk_15_21

theorem cert_15_22 : BlockPSD 15 22 :=
  posSemidef_of_chk _ (blockA 15 22) (blockA_symm 15 22) _ _ _ _ alphaW (blockA_bound 15 22)
    cL_15_22 cE_15_22 cPL_15_22 rfl chk_15_22

theorem cert_15_23 : BlockPSD 15 23 :=
  posSemidef_of_chk _ (blockA 15 23) (blockA_symm 15 23) _ _ _ _ alphaW (blockA_bound 15 23)
    cL_15_23 cE_15_23 cPL_15_23 rfl chk_15_23

theorem cert_15_24 : BlockPSD 15 24 :=
  posSemidef_of_chk _ (blockA 15 24) (blockA_symm 15 24) _ _ _ _ alphaW (blockA_bound 15 24)
    cL_15_24 cE_15_24 cPL_15_24 rfl chk_15_24

theorem cert_15_25 : BlockPSD 15 25 :=
  posSemidef_of_chk _ (blockA 15 25) (blockA_symm 15 25) _ _ _ _ alphaW (blockA_bound 15 25)
    cL_15_25 cE_15_25 cPL_15_25 rfl chk_15_25

theorem cert_16_16 : BlockPSD 16 16 :=
  posSemidef_of_chk _ (blockA 16 16) (blockA_symm 16 16) _ _ _ _ alphaW (blockA_bound 16 16)
    cL_16_16 cE_16_16 cPL_16_16 rfl chk_16_16

theorem cert_16_17 : BlockPSD 16 17 :=
  posSemidef_of_chk _ (blockA 16 17) (blockA_symm 16 17) _ _ _ _ alphaW (blockA_bound 16 17)
    cL_16_17 cE_16_17 cPL_16_17 rfl chk_16_17

theorem cert_16_18 : BlockPSD 16 18 :=
  posSemidef_of_chk _ (blockA 16 18) (blockA_symm 16 18) _ _ _ _ alphaW (blockA_bound 16 18)
    cL_16_18 cE_16_18 cPL_16_18 rfl chk_16_18

theorem cert_16_19 : BlockPSD 16 19 :=
  posSemidef_of_chk _ (blockA 16 19) (blockA_symm 16 19) _ _ _ _ alphaW (blockA_bound 16 19)
    cL_16_19 cE_16_19 cPL_16_19 rfl chk_16_19

theorem cert_16_20 : BlockPSD 16 20 :=
  posSemidef_of_chk _ (blockA 16 20) (blockA_symm 16 20) _ _ _ _ alphaW (blockA_bound 16 20)
    cL_16_20 cE_16_20 cPL_16_20 rfl chk_16_20

theorem cert_16_21 : BlockPSD 16 21 :=
  posSemidef_of_chk _ (blockA 16 21) (blockA_symm 16 21) _ _ _ _ alphaW (blockA_bound 16 21)
    cL_16_21 cE_16_21 cPL_16_21 rfl chk_16_21

theorem cert_16_22 : BlockPSD 16 22 :=
  posSemidef_of_chk _ (blockA 16 22) (blockA_symm 16 22) _ _ _ _ alphaW (blockA_bound 16 22)
    cL_16_22 cE_16_22 cPL_16_22 rfl chk_16_22

theorem cert_16_23 : BlockPSD 16 23 :=
  posSemidef_of_chk _ (blockA 16 23) (blockA_symm 16 23) _ _ _ _ alphaW (blockA_bound 16 23)
    cL_16_23 cE_16_23 cPL_16_23 rfl chk_16_23

theorem cert_16_24 : BlockPSD 16 24 :=
  posSemidef_of_chk _ (blockA 16 24) (blockA_symm 16 24) _ _ _ _ alphaW (blockA_bound 16 24)
    cL_16_24 cE_16_24 cPL_16_24 rfl chk_16_24

theorem cert_16_25 : BlockPSD 16 25 :=
  posSemidef_of_chk _ (blockA 16 25) (blockA_symm 16 25) _ _ _ _ alphaW (blockA_bound 16 25)
    cL_16_25 cE_16_25 cPL_16_25 rfl chk_16_25

theorem cert_17_17 : BlockPSD 17 17 :=
  posSemidef_of_chk _ (blockA 17 17) (blockA_symm 17 17) _ _ _ _ alphaW (blockA_bound 17 17)
    cL_17_17 cE_17_17 cPL_17_17 rfl chk_17_17

theorem cert_17_18 : BlockPSD 17 18 :=
  posSemidef_of_chk _ (blockA 17 18) (blockA_symm 17 18) _ _ _ _ alphaW (blockA_bound 17 18)
    cL_17_18 cE_17_18 cPL_17_18 rfl chk_17_18

theorem cert_17_19 : BlockPSD 17 19 :=
  posSemidef_of_chk _ (blockA 17 19) (blockA_symm 17 19) _ _ _ _ alphaW (blockA_bound 17 19)
    cL_17_19 cE_17_19 cPL_17_19 rfl chk_17_19

theorem cert_17_20 : BlockPSD 17 20 :=
  posSemidef_of_chk _ (blockA 17 20) (blockA_symm 17 20) _ _ _ _ alphaW (blockA_bound 17 20)
    cL_17_20 cE_17_20 cPL_17_20 rfl chk_17_20

theorem cert_17_21 : BlockPSD 17 21 :=
  posSemidef_of_chk _ (blockA 17 21) (blockA_symm 17 21) _ _ _ _ alphaW (blockA_bound 17 21)
    cL_17_21 cE_17_21 cPL_17_21 rfl chk_17_21

theorem cert_17_22 : BlockPSD 17 22 :=
  posSemidef_of_chk _ (blockA 17 22) (blockA_symm 17 22) _ _ _ _ alphaW (blockA_bound 17 22)
    cL_17_22 cE_17_22 cPL_17_22 rfl chk_17_22

theorem cert_17_23 : BlockPSD 17 23 :=
  posSemidef_of_chk _ (blockA 17 23) (blockA_symm 17 23) _ _ _ _ alphaW (blockA_bound 17 23)
    cL_17_23 cE_17_23 cPL_17_23 rfl chk_17_23

theorem cert_17_24 : BlockPSD 17 24 :=
  posSemidef_of_chk _ (blockA 17 24) (blockA_symm 17 24) _ _ _ _ alphaW (blockA_bound 17 24)
    cL_17_24 cE_17_24 cPL_17_24 rfl chk_17_24

theorem cert_17_25 : BlockPSD 17 25 :=
  posSemidef_of_chk _ (blockA 17 25) (blockA_symm 17 25) _ _ _ _ alphaW (blockA_bound 17 25)
    cL_17_25 cE_17_25 cPL_17_25 rfl chk_17_25

theorem cert_18_18 : BlockPSD 18 18 :=
  posSemidef_of_chk _ (blockA 18 18) (blockA_symm 18 18) _ _ _ _ alphaW (blockA_bound 18 18)
    cL_18_18 cE_18_18 cPL_18_18 rfl chk_18_18

theorem cert_18_19 : BlockPSD 18 19 :=
  posSemidef_of_chk _ (blockA 18 19) (blockA_symm 18 19) _ _ _ _ alphaW (blockA_bound 18 19)
    cL_18_19 cE_18_19 cPL_18_19 rfl chk_18_19

theorem cert_18_20 : BlockPSD 18 20 :=
  posSemidef_of_chk _ (blockA 18 20) (blockA_symm 18 20) _ _ _ _ alphaW (blockA_bound 18 20)
    cL_18_20 cE_18_20 cPL_18_20 rfl chk_18_20

theorem cert_18_21 : BlockPSD 18 21 :=
  posSemidef_of_chk _ (blockA 18 21) (blockA_symm 18 21) _ _ _ _ alphaW (blockA_bound 18 21)
    cL_18_21 cE_18_21 cPL_18_21 rfl chk_18_21

theorem cert_18_22 : BlockPSD 18 22 :=
  posSemidef_of_chk _ (blockA 18 22) (blockA_symm 18 22) _ _ _ _ alphaW (blockA_bound 18 22)
    cL_18_22 cE_18_22 cPL_18_22 rfl chk_18_22

theorem cert_18_23 : BlockPSD 18 23 :=
  posSemidef_of_chk _ (blockA 18 23) (blockA_symm 18 23) _ _ _ _ alphaW (blockA_bound 18 23)
    cL_18_23 cE_18_23 cPL_18_23 rfl chk_18_23

theorem cert_18_24 : BlockPSD 18 24 :=
  posSemidef_of_chk _ (blockA 18 24) (blockA_symm 18 24) _ _ _ _ alphaW (blockA_bound 18 24)
    cL_18_24 cE_18_24 cPL_18_24 rfl chk_18_24

theorem cert_18_25 : BlockPSD 18 25 :=
  posSemidef_of_chk _ (blockA 18 25) (blockA_symm 18 25) _ _ _ _ alphaW (blockA_bound 18 25)
    cL_18_25 cE_18_25 cPL_18_25 rfl chk_18_25

theorem cert_19_19 : BlockPSD 19 19 :=
  posSemidef_of_chk _ (blockA 19 19) (blockA_symm 19 19) _ _ _ _ alphaW (blockA_bound 19 19)
    cL_19_19 cE_19_19 cPL_19_19 rfl chk_19_19

theorem cert_19_20 : BlockPSD 19 20 :=
  posSemidef_of_chk _ (blockA 19 20) (blockA_symm 19 20) _ _ _ _ alphaW (blockA_bound 19 20)
    cL_19_20 cE_19_20 cPL_19_20 rfl chk_19_20

theorem cert_19_21 : BlockPSD 19 21 :=
  posSemidef_of_chk _ (blockA 19 21) (blockA_symm 19 21) _ _ _ _ alphaW (blockA_bound 19 21)
    cL_19_21 cE_19_21 cPL_19_21 rfl chk_19_21

theorem cert_19_22 : BlockPSD 19 22 :=
  posSemidef_of_chk _ (blockA 19 22) (blockA_symm 19 22) _ _ _ _ alphaW (blockA_bound 19 22)
    cL_19_22 cE_19_22 cPL_19_22 rfl chk_19_22

theorem cert_19_23 : BlockPSD 19 23 :=
  posSemidef_of_chk _ (blockA 19 23) (blockA_symm 19 23) _ _ _ _ alphaW (blockA_bound 19 23)
    cL_19_23 cE_19_23 cPL_19_23 rfl chk_19_23

theorem cert_19_24 : BlockPSD 19 24 :=
  posSemidef_of_chk _ (blockA 19 24) (blockA_symm 19 24) _ _ _ _ alphaW (blockA_bound 19 24)
    cL_19_24 cE_19_24 cPL_19_24 rfl chk_19_24

theorem cert_19_25 : BlockPSD 19 25 :=
  posSemidef_of_chk _ (blockA 19 25) (blockA_symm 19 25) _ _ _ _ alphaW (blockA_bound 19 25)
    cL_19_25 cE_19_25 cPL_19_25 rfl chk_19_25

theorem cert_20_20 : BlockPSD 20 20 :=
  posSemidef_of_chk _ (blockA 20 20) (blockA_symm 20 20) _ _ _ _ alphaW (blockA_bound 20 20)
    cL_20_20 cE_20_20 cPL_20_20 rfl chk_20_20

theorem cert_20_21 : BlockPSD 20 21 :=
  posSemidef_of_chk _ (blockA 20 21) (blockA_symm 20 21) _ _ _ _ alphaW (blockA_bound 20 21)
    cL_20_21 cE_20_21 cPL_20_21 rfl chk_20_21

theorem cert_20_22 : BlockPSD 20 22 :=
  posSemidef_of_chk _ (blockA 20 22) (blockA_symm 20 22) _ _ _ _ alphaW (blockA_bound 20 22)
    cL_20_22 cE_20_22 cPL_20_22 rfl chk_20_22

theorem cert_20_23 : BlockPSD 20 23 :=
  posSemidef_of_chk _ (blockA 20 23) (blockA_symm 20 23) _ _ _ _ alphaW (blockA_bound 20 23)
    cL_20_23 cE_20_23 cPL_20_23 rfl chk_20_23

theorem cert_20_24 : BlockPSD 20 24 :=
  posSemidef_of_chk _ (blockA 20 24) (blockA_symm 20 24) _ _ _ _ alphaW (blockA_bound 20 24)
    cL_20_24 cE_20_24 cPL_20_24 rfl chk_20_24

theorem cert_20_25 : BlockPSD 20 25 :=
  posSemidef_of_chk _ (blockA 20 25) (blockA_symm 20 25) _ _ _ _ alphaW (blockA_bound 20 25)
    cL_20_25 cE_20_25 cPL_20_25 rfl chk_20_25

theorem cert_21_21 : BlockPSD 21 21 :=
  posSemidef_of_chk _ (blockA 21 21) (blockA_symm 21 21) _ _ _ _ alphaW (blockA_bound 21 21)
    cL_21_21 cE_21_21 cPL_21_21 rfl chk_21_21

theorem cert_21_22 : BlockPSD 21 22 :=
  posSemidef_of_chk _ (blockA 21 22) (blockA_symm 21 22) _ _ _ _ alphaW (blockA_bound 21 22)
    cL_21_22 cE_21_22 cPL_21_22 rfl chk_21_22

theorem cert_21_23 : BlockPSD 21 23 :=
  posSemidef_of_chk _ (blockA 21 23) (blockA_symm 21 23) _ _ _ _ alphaW (blockA_bound 21 23)
    cL_21_23 cE_21_23 cPL_21_23 rfl chk_21_23

theorem cert_21_24 : BlockPSD 21 24 :=
  posSemidef_of_chk _ (blockA 21 24) (blockA_symm 21 24) _ _ _ _ alphaW (blockA_bound 21 24)
    cL_21_24 cE_21_24 cPL_21_24 rfl chk_21_24

theorem cert_21_25 : BlockPSD 21 25 :=
  posSemidef_of_chk _ (blockA 21 25) (blockA_symm 21 25) _ _ _ _ alphaW (blockA_bound 21 25)
    cL_21_25 cE_21_25 cPL_21_25 rfl chk_21_25

theorem cert_22_22 : BlockPSD 22 22 :=
  posSemidef_of_chk _ (blockA 22 22) (blockA_symm 22 22) _ _ _ _ alphaW (blockA_bound 22 22)
    cL_22_22 cE_22_22 cPL_22_22 rfl chk_22_22

theorem cert_22_23 : BlockPSD 22 23 :=
  posSemidef_of_chk _ (blockA 22 23) (blockA_symm 22 23) _ _ _ _ alphaW (blockA_bound 22 23)
    cL_22_23 cE_22_23 cPL_22_23 rfl chk_22_23

theorem cert_22_24 : BlockPSD 22 24 :=
  posSemidef_of_chk _ (blockA 22 24) (blockA_symm 22 24) _ _ _ _ alphaW (blockA_bound 22 24)
    cL_22_24 cE_22_24 cPL_22_24 rfl chk_22_24

theorem cert_22_25 : BlockPSD 22 25 :=
  posSemidef_of_chk _ (blockA 22 25) (blockA_symm 22 25) _ _ _ _ alphaW (blockA_bound 22 25)
    cL_22_25 cE_22_25 cPL_22_25 rfl chk_22_25

theorem cert_23_23 : BlockPSD 23 23 :=
  posSemidef_of_chk _ (blockA 23 23) (blockA_symm 23 23) _ _ _ _ alphaW (blockA_bound 23 23)
    cL_23_23 cE_23_23 cPL_23_23 rfl chk_23_23

theorem cert_23_24 : BlockPSD 23 24 :=
  posSemidef_of_chk _ (blockA 23 24) (blockA_symm 23 24) _ _ _ _ alphaW (blockA_bound 23 24)
    cL_23_24 cE_23_24 cPL_23_24 rfl chk_23_24

theorem cert_23_25 : BlockPSD 23 25 :=
  posSemidef_of_chk _ (blockA 23 25) (blockA_symm 23 25) _ _ _ _ alphaW (blockA_bound 23 25)
    cL_23_25 cE_23_25 cPL_23_25 rfl chk_23_25

theorem cert_24_24 : BlockPSD 24 24 :=
  posSemidef_of_chk _ (blockA 24 24) (blockA_symm 24 24) _ _ _ _ alphaW (blockA_bound 24 24)
    cL_24_24 cE_24_24 cPL_24_24 rfl chk_24_24

theorem cert_24_25 : BlockPSD 24 25 :=
  posSemidef_of_chk _ (blockA 24 25) (blockA_symm 24 25) _ _ _ _ alphaW (blockA_bound 24 25)
    cL_24_25 cE_24_25 cPL_24_25 rfl chk_24_25

theorem cert_25_25 : BlockPSD 25 25 :=
  posSemidef_of_chk _ (blockA 25 25) (blockA_symm 25 25) _ _ _ _ alphaW (blockA_bound 25 25)
    cL_25_25 cE_25_25 cPL_25_25 rfl chk_25_25

theorem cert_0_1 : BlockPSD 0 1 :=
  posSemidef_of_chk _ (blockA 0 1) (blockA_symm 0 1) _ _ _ _ alphaW (blockA_bound 0 1)
    cL_0_1 cE_0_1 cPL_0_1 rfl chk_0_1

theorem cert_0_2 : BlockPSD 0 2 :=
  posSemidef_of_chk _ (blockA 0 2) (blockA_symm 0 2) _ _ _ _ alphaW (blockA_bound 0 2)
    cL_0_2 cE_0_2 cPL_0_2 rfl chk_0_2

theorem cert_0_3 : BlockPSD 0 3 :=
  posSemidef_of_chk _ (blockA 0 3) (blockA_symm 0 3) _ _ _ _ alphaW (blockA_bound 0 3)
    cL_0_3 cE_0_3 cPL_0_3 rfl chk_0_3

theorem cert_0_4 : BlockPSD 0 4 :=
  posSemidef_of_chk _ (blockA 0 4) (blockA_symm 0 4) _ _ _ _ alphaW (blockA_bound 0 4)
    cL_0_4 cE_0_4 cPL_0_4 rfl chk_0_4

theorem cert_0_5 : BlockPSD 0 5 :=
  posSemidef_of_chk _ (blockA 0 5) (blockA_symm 0 5) _ _ _ _ alphaW (blockA_bound 0 5)
    cL_0_5 cE_0_5 cPL_0_5 rfl chk_0_5

theorem cert_0_6 : BlockPSD 0 6 :=
  posSemidef_of_chk _ (blockA 0 6) (blockA_symm 0 6) _ _ _ _ alphaW (blockA_bound 0 6)
    cL_0_6 cE_0_6 cPL_0_6 rfl chk_0_6

theorem cert_0_7 : BlockPSD 0 7 :=
  posSemidef_of_chk _ (blockA 0 7) (blockA_symm 0 7) _ _ _ _ alphaW (blockA_bound 0 7)
    cL_0_7 cE_0_7 cPL_0_7 rfl chk_0_7

theorem cert_0_8 : BlockPSD 0 8 :=
  posSemidef_of_chk _ (blockA 0 8) (blockA_symm 0 8) _ _ _ _ alphaW (blockA_bound 0 8)
    cL_0_8 cE_0_8 cPL_0_8 rfl chk_0_8

theorem cert_0_9 : BlockPSD 0 9 :=
  posSemidef_of_chk _ (blockA 0 9) (blockA_symm 0 9) _ _ _ _ alphaW (blockA_bound 0 9)
    cL_0_9 cE_0_9 cPL_0_9 rfl chk_0_9

theorem cert_0_10 : BlockPSD 0 10 :=
  posSemidef_of_chk _ (blockA 0 10) (blockA_symm 0 10) _ _ _ _ alphaW (blockA_bound 0 10)
    cL_0_10 cE_0_10 cPL_0_10 rfl chk_0_10

theorem cert_0_11 : BlockPSD 0 11 :=
  posSemidef_of_chk _ (blockA 0 11) (blockA_symm 0 11) _ _ _ _ alphaW (blockA_bound 0 11)
    cL_0_11 cE_0_11 cPL_0_11 rfl chk_0_11

theorem cert_0_12 : BlockPSD 0 12 :=
  posSemidef_of_chk _ (blockA 0 12) (blockA_symm 0 12) _ _ _ _ alphaW (blockA_bound 0 12)
    cL_0_12 cE_0_12 cPL_0_12 rfl chk_0_12

theorem cert_0_14 : BlockPSD 0 14 :=
  posSemidef_of_chk _ (blockA 0 14) (blockA_symm 0 14) _ _ _ _ alphaW (blockA_bound 0 14)
    cL_0_14 cE_0_14 cPL_0_14 rfl chk_0_14

theorem cert_0_15 : BlockPSD 0 15 :=
  posSemidef_of_chk _ (blockA 0 15) (blockA_symm 0 15) _ _ _ _ alphaW (blockA_bound 0 15)
    cL_0_15 cE_0_15 cPL_0_15 rfl chk_0_15

theorem cert_0_16 : BlockPSD 0 16 :=
  posSemidef_of_chk _ (blockA 0 16) (blockA_symm 0 16) _ _ _ _ alphaW (blockA_bound 0 16)
    cL_0_16 cE_0_16 cPL_0_16 rfl chk_0_16

theorem cert_0_17 : BlockPSD 0 17 :=
  posSemidef_of_chk _ (blockA 0 17) (blockA_symm 0 17) _ _ _ _ alphaW (blockA_bound 0 17)
    cL_0_17 cE_0_17 cPL_0_17 rfl chk_0_17

theorem cert_0_18 : BlockPSD 0 18 :=
  posSemidef_of_chk _ (blockA 0 18) (blockA_symm 0 18) _ _ _ _ alphaW (blockA_bound 0 18)
    cL_0_18 cE_0_18 cPL_0_18 rfl chk_0_18

theorem cert_0_19 : BlockPSD 0 19 :=
  posSemidef_of_chk _ (blockA 0 19) (blockA_symm 0 19) _ _ _ _ alphaW (blockA_bound 0 19)
    cL_0_19 cE_0_19 cPL_0_19 rfl chk_0_19

theorem cert_0_20 : BlockPSD 0 20 :=
  posSemidef_of_chk _ (blockA 0 20) (blockA_symm 0 20) _ _ _ _ alphaW (blockA_bound 0 20)
    cL_0_20 cE_0_20 cPL_0_20 rfl chk_0_20

theorem cert_0_21 : BlockPSD 0 21 :=
  posSemidef_of_chk _ (blockA 0 21) (blockA_symm 0 21) _ _ _ _ alphaW (blockA_bound 0 21)
    cL_0_21 cE_0_21 cPL_0_21 rfl chk_0_21

theorem cert_0_22 : BlockPSD 0 22 :=
  posSemidef_of_chk _ (blockA 0 22) (blockA_symm 0 22) _ _ _ _ alphaW (blockA_bound 0 22)
    cL_0_22 cE_0_22 cPL_0_22 rfl chk_0_22

theorem cert_0_23 : BlockPSD 0 23 :=
  posSemidef_of_chk _ (blockA 0 23) (blockA_symm 0 23) _ _ _ _ alphaW (blockA_bound 0 23)
    cL_0_23 cE_0_23 cPL_0_23 rfl chk_0_23

theorem cert_0_24 : BlockPSD 0 24 :=
  posSemidef_of_chk _ (blockA 0 24) (blockA_symm 0 24) _ _ _ _ alphaW (blockA_bound 0 24)
    cL_0_24 cE_0_24 cPL_0_24 rfl chk_0_24

theorem cert_0_25 : BlockPSD 0 25 :=
  posSemidef_of_chk _ (blockA 0 25) (blockA_symm 0 25) _ _ _ _ alphaW (blockA_bound 0 25)
    cL_0_25 cE_0_25 cPL_0_25 rfl chk_0_25

theorem cert_1_13 : BlockPSD 1 13 :=
  posSemidef_of_chk _ (blockA 1 13) (blockA_symm 1 13) _ _ _ _ alphaW (blockA_bound 1 13)
    cL_1_13 cE_1_13 cPL_1_13 rfl chk_1_13

theorem cert_2_13 : BlockPSD 2 13 :=
  posSemidef_of_chk _ (blockA 2 13) (blockA_symm 2 13) _ _ _ _ alphaW (blockA_bound 2 13)
    cL_2_13 cE_2_13 cPL_2_13 rfl chk_2_13

theorem cert_3_13 : BlockPSD 3 13 :=
  posSemidef_of_chk _ (blockA 3 13) (blockA_symm 3 13) _ _ _ _ alphaW (blockA_bound 3 13)
    cL_3_13 cE_3_13 cPL_3_13 rfl chk_3_13

theorem cert_4_13 : BlockPSD 4 13 :=
  posSemidef_of_chk _ (blockA 4 13) (blockA_symm 4 13) _ _ _ _ alphaW (blockA_bound 4 13)
    cL_4_13 cE_4_13 cPL_4_13 rfl chk_4_13

theorem cert_5_13 : BlockPSD 5 13 :=
  posSemidef_of_chk _ (blockA 5 13) (blockA_symm 5 13) _ _ _ _ alphaW (blockA_bound 5 13)
    cL_5_13 cE_5_13 cPL_5_13 rfl chk_5_13

theorem cert_6_13 : BlockPSD 6 13 :=
  posSemidef_of_chk _ (blockA 6 13) (blockA_symm 6 13) _ _ _ _ alphaW (blockA_bound 6 13)
    cL_6_13 cE_6_13 cPL_6_13 rfl chk_6_13

theorem cert_7_13 : BlockPSD 7 13 :=
  posSemidef_of_chk _ (blockA 7 13) (blockA_symm 7 13) _ _ _ _ alphaW (blockA_bound 7 13)
    cL_7_13 cE_7_13 cPL_7_13 rfl chk_7_13

theorem cert_8_13 : BlockPSD 8 13 :=
  posSemidef_of_chk _ (blockA 8 13) (blockA_symm 8 13) _ _ _ _ alphaW (blockA_bound 8 13)
    cL_8_13 cE_8_13 cPL_8_13 rfl chk_8_13

theorem cert_9_13 : BlockPSD 9 13 :=
  posSemidef_of_chk _ (blockA 9 13) (blockA_symm 9 13) _ _ _ _ alphaW (blockA_bound 9 13)
    cL_9_13 cE_9_13 cPL_9_13 rfl chk_9_13

theorem cert_10_13 : BlockPSD 10 13 :=
  posSemidef_of_chk _ (blockA 10 13) (blockA_symm 10 13) _ _ _ _ alphaW (blockA_bound 10 13)
    cL_10_13 cE_10_13 cPL_10_13 rfl chk_10_13

theorem cert_11_13 : BlockPSD 11 13 :=
  posSemidef_of_chk _ (blockA 11 13) (blockA_symm 11 13) _ _ _ _ alphaW (blockA_bound 11 13)
    cL_11_13 cE_11_13 cPL_11_13 rfl chk_11_13

theorem cert_12_13 : BlockPSD 12 13 :=
  posSemidef_of_chk _ (blockA 12 13) (blockA_symm 12 13) _ _ _ _ alphaW (blockA_bound 12 13)
    cL_12_13 cE_12_13 cPL_12_13 rfl chk_12_13

theorem cert_13_14 : BlockPSD 13 14 :=
  posSemidef_of_chk _ (blockA 13 14) (blockA_symm 13 14) _ _ _ _ alphaW (blockA_bound 13 14)
    cL_13_14 cE_13_14 cPL_13_14 rfl chk_13_14

theorem cert_13_15 : BlockPSD 13 15 :=
  posSemidef_of_chk _ (blockA 13 15) (blockA_symm 13 15) _ _ _ _ alphaW (blockA_bound 13 15)
    cL_13_15 cE_13_15 cPL_13_15 rfl chk_13_15

theorem cert_13_16 : BlockPSD 13 16 :=
  posSemidef_of_chk _ (blockA 13 16) (blockA_symm 13 16) _ _ _ _ alphaW (blockA_bound 13 16)
    cL_13_16 cE_13_16 cPL_13_16 rfl chk_13_16

theorem cert_13_17 : BlockPSD 13 17 :=
  posSemidef_of_chk _ (blockA 13 17) (blockA_symm 13 17) _ _ _ _ alphaW (blockA_bound 13 17)
    cL_13_17 cE_13_17 cPL_13_17 rfl chk_13_17

theorem cert_13_18 : BlockPSD 13 18 :=
  posSemidef_of_chk _ (blockA 13 18) (blockA_symm 13 18) _ _ _ _ alphaW (blockA_bound 13 18)
    cL_13_18 cE_13_18 cPL_13_18 rfl chk_13_18

theorem cert_13_19 : BlockPSD 13 19 :=
  posSemidef_of_chk _ (blockA 13 19) (blockA_symm 13 19) _ _ _ _ alphaW (blockA_bound 13 19)
    cL_13_19 cE_13_19 cPL_13_19 rfl chk_13_19

theorem cert_13_20 : BlockPSD 13 20 :=
  posSemidef_of_chk _ (blockA 13 20) (blockA_symm 13 20) _ _ _ _ alphaW (blockA_bound 13 20)
    cL_13_20 cE_13_20 cPL_13_20 rfl chk_13_20

theorem cert_13_21 : BlockPSD 13 21 :=
  posSemidef_of_chk _ (blockA 13 21) (blockA_symm 13 21) _ _ _ _ alphaW (blockA_bound 13 21)
    cL_13_21 cE_13_21 cPL_13_21 rfl chk_13_21

theorem cert_13_22 : BlockPSD 13 22 :=
  posSemidef_of_chk _ (blockA 13 22) (blockA_symm 13 22) _ _ _ _ alphaW (blockA_bound 13 22)
    cL_13_22 cE_13_22 cPL_13_22 rfl chk_13_22

theorem cert_13_23 : BlockPSD 13 23 :=
  posSemidef_of_chk _ (blockA 13 23) (blockA_symm 13 23) _ _ _ _ alphaW (blockA_bound 13 23)
    cL_13_23 cE_13_23 cPL_13_23 rfl chk_13_23

theorem cert_13_24 : BlockPSD 13 24 :=
  posSemidef_of_chk _ (blockA 13 24) (blockA_symm 13 24) _ _ _ _ alphaW (blockA_bound 13 24)
    cL_13_24 cE_13_24 cPL_13_24 rfl chk_13_24

theorem cert_13_25 : BlockPSD 13 25 :=
  posSemidef_of_chk _ (blockA 13 25) (blockA_symm 13 25) _ _ _ _ alphaW (blockA_bound 13 25)
    cL_13_25 cE_13_25 cPL_13_25 rfl chk_13_25

theorem blockPSD_row_0 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 0 ≤ cB → cB < 26 → BlockPSD 0 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [hbig.1, cert_0_1, cert_0_2, cert_0_3, cert_0_4, cert_0_5, cert_0_6, cert_0_7, cert_0_8, cert_0_9, cert_0_10, cert_0_11, cert_0_12, hbig.2.1, cert_0_14, cert_0_15, cert_0_16, cert_0_17, cert_0_18, cert_0_19, cert_0_20, cert_0_21, cert_0_22, cert_0_23, cert_0_24, cert_0_25]

theorem blockPSD_row_1 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 1 ≤ cB → cB < 26 → BlockPSD 1 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_1_1, cert_1_2, cert_1_3, cert_1_4, cert_1_5, cert_1_6, cert_1_7, cert_1_8, cert_1_9, cert_1_10, cert_1_11, cert_1_12, cert_1_13, cert_1_14, cert_1_15, cert_1_16, cert_1_17, cert_1_18, cert_1_19, cert_1_20, cert_1_21, cert_1_22, cert_1_23, cert_1_24, cert_1_25]

theorem blockPSD_row_2 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 2 ≤ cB → cB < 26 → BlockPSD 2 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_2_2, cert_2_3, cert_2_4, cert_2_5, cert_2_6, cert_2_7, cert_2_8, cert_2_9, cert_2_10, cert_2_11, cert_2_12, cert_2_13, cert_2_14, cert_2_15, cert_2_16, cert_2_17, cert_2_18, cert_2_19, cert_2_20, cert_2_21, cert_2_22, cert_2_23, cert_2_24, cert_2_25]

theorem blockPSD_row_3 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 3 ≤ cB → cB < 26 → BlockPSD 3 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_3_3, cert_3_4, cert_3_5, cert_3_6, cert_3_7, cert_3_8, cert_3_9, cert_3_10, cert_3_11, cert_3_12, cert_3_13, cert_3_14, cert_3_15, cert_3_16, cert_3_17, cert_3_18, cert_3_19, cert_3_20, cert_3_21, cert_3_22, cert_3_23, cert_3_24, cert_3_25]

theorem blockPSD_row_4 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 4 ≤ cB → cB < 26 → BlockPSD 4 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_4_4, cert_4_5, cert_4_6, cert_4_7, cert_4_8, cert_4_9, cert_4_10, cert_4_11, cert_4_12, cert_4_13, cert_4_14, cert_4_15, cert_4_16, cert_4_17, cert_4_18, cert_4_19, cert_4_20, cert_4_21, cert_4_22, cert_4_23, cert_4_24, cert_4_25]

theorem blockPSD_row_5 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 5 ≤ cB → cB < 26 → BlockPSD 5 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_5_5, cert_5_6, cert_5_7, cert_5_8, cert_5_9, cert_5_10, cert_5_11, cert_5_12, cert_5_13, cert_5_14, cert_5_15, cert_5_16, cert_5_17, cert_5_18, cert_5_19, cert_5_20, cert_5_21, cert_5_22, cert_5_23, cert_5_24, cert_5_25]

theorem blockPSD_row_6 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 6 ≤ cB → cB < 26 → BlockPSD 6 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_6_6, cert_6_7, cert_6_8, cert_6_9, cert_6_10, cert_6_11, cert_6_12, cert_6_13, cert_6_14, cert_6_15, cert_6_16, cert_6_17, cert_6_18, cert_6_19, cert_6_20, cert_6_21, cert_6_22, cert_6_23, cert_6_24, cert_6_25]

theorem blockPSD_row_7 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 7 ≤ cB → cB < 26 → BlockPSD 7 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_7_7, cert_7_8, cert_7_9, cert_7_10, cert_7_11, cert_7_12, cert_7_13, cert_7_14, cert_7_15, cert_7_16, cert_7_17, cert_7_18, cert_7_19, cert_7_20, cert_7_21, cert_7_22, cert_7_23, cert_7_24, cert_7_25]

theorem blockPSD_row_8 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 8 ≤ cB → cB < 26 → BlockPSD 8 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_8_8, cert_8_9, cert_8_10, cert_8_11, cert_8_12, cert_8_13, cert_8_14, cert_8_15, cert_8_16, cert_8_17, cert_8_18, cert_8_19, cert_8_20, cert_8_21, cert_8_22, cert_8_23, cert_8_24, cert_8_25]

theorem blockPSD_row_9 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 9 ≤ cB → cB < 26 → BlockPSD 9 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_9_9, cert_9_10, cert_9_11, cert_9_12, cert_9_13, cert_9_14, cert_9_15, cert_9_16, cert_9_17, cert_9_18, cert_9_19, cert_9_20, cert_9_21, cert_9_22, cert_9_23, cert_9_24, cert_9_25]

theorem blockPSD_row_10 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 10 ≤ cB → cB < 26 → BlockPSD 10 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_10_10, cert_10_11, cert_10_12, cert_10_13, cert_10_14, cert_10_15, cert_10_16, cert_10_17, cert_10_18, cert_10_19, cert_10_20, cert_10_21, cert_10_22, cert_10_23, cert_10_24, cert_10_25]

theorem blockPSD_row_11 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 11 ≤ cB → cB < 26 → BlockPSD 11 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_11_11, cert_11_12, cert_11_13, cert_11_14, cert_11_15, cert_11_16, cert_11_17, cert_11_18, cert_11_19, cert_11_20, cert_11_21, cert_11_22, cert_11_23, cert_11_24, cert_11_25]

theorem blockPSD_row_12 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 12 ≤ cB → cB < 26 → BlockPSD 12 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_12_12, cert_12_13, cert_12_14, cert_12_15, cert_12_16, cert_12_17, cert_12_18, cert_12_19, cert_12_20, cert_12_21, cert_12_22, cert_12_23, cert_12_24, cert_12_25]

theorem blockPSD_row_13 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 13 ≤ cB → cB < 26 → BlockPSD 13 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [hbig.2.2, cert_13_14, cert_13_15, cert_13_16, cert_13_17, cert_13_18, cert_13_19, cert_13_20, cert_13_21, cert_13_22, cert_13_23, cert_13_24, cert_13_25]

theorem blockPSD_row_14 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 14 ≤ cB → cB < 26 → BlockPSD 14 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_14_14, cert_14_15, cert_14_16, cert_14_17, cert_14_18, cert_14_19, cert_14_20, cert_14_21, cert_14_22, cert_14_23, cert_14_24, cert_14_25]

theorem blockPSD_row_15 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 15 ≤ cB → cB < 26 → BlockPSD 15 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_15_15, cert_15_16, cert_15_17, cert_15_18, cert_15_19, cert_15_20, cert_15_21, cert_15_22, cert_15_23, cert_15_24, cert_15_25]

theorem blockPSD_row_16 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 16 ≤ cB → cB < 26 → BlockPSD 16 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_16_16, cert_16_17, cert_16_18, cert_16_19, cert_16_20, cert_16_21, cert_16_22, cert_16_23, cert_16_24, cert_16_25]

theorem blockPSD_row_17 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 17 ≤ cB → cB < 26 → BlockPSD 17 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_17_17, cert_17_18, cert_17_19, cert_17_20, cert_17_21, cert_17_22, cert_17_23, cert_17_24, cert_17_25]

theorem blockPSD_row_18 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 18 ≤ cB → cB < 26 → BlockPSD 18 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_18_18, cert_18_19, cert_18_20, cert_18_21, cert_18_22, cert_18_23, cert_18_24, cert_18_25]

theorem blockPSD_row_19 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 19 ≤ cB → cB < 26 → BlockPSD 19 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_19_19, cert_19_20, cert_19_21, cert_19_22, cert_19_23, cert_19_24, cert_19_25]

theorem blockPSD_row_20 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 20 ≤ cB → cB < 26 → BlockPSD 20 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_20_20, cert_20_21, cert_20_22, cert_20_23, cert_20_24, cert_20_25]

theorem blockPSD_row_21 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 21 ≤ cB → cB < 26 → BlockPSD 21 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_21_21, cert_21_22, cert_21_23, cert_21_24, cert_21_25]

theorem blockPSD_row_22 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 22 ≤ cB → cB < 26 → BlockPSD 22 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_22_22, cert_22_23, cert_22_24, cert_22_25]

theorem blockPSD_row_23 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 23 ≤ cB → cB < 26 → BlockPSD 23 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_23_23, cert_23_24, cert_23_25]

theorem blockPSD_row_24 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 24 ≤ cB → cB < 26 → BlockPSD 24 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_24_24, cert_24_25]

theorem blockPSD_row_25 (hbig : BigBlocksPSD) :
    ∀ cB : ℕ, 25 ≤ cB → cB < 26 → BlockPSD 25 cB := by
  intro cB h1 h2
  interval_cases cB
  exacts [cert_25_25]

theorem blockPSD_le (hbig : BigBlocksPSD) :
    ∀ cA cB : ℕ, cA ≤ cB → cB < 26 → BlockPSD cA cB := by
  intro cA cB h1 h2
  have h3 : cA < 26 := by omega
  interval_cases cA
  exacts [blockPSD_row_0 hbig cB h1 h2, blockPSD_row_1 hbig cB h1 h2, blockPSD_row_2 hbig cB h1 h2, blockPSD_row_3 hbig cB h1 h2, blockPSD_row_4 hbig cB h1 h2, blockPSD_row_5 hbig cB h1 h2, blockPSD_row_6 hbig cB h1 h2, blockPSD_row_7 hbig cB h1 h2, blockPSD_row_8 hbig cB h1 h2, blockPSD_row_9 hbig cB h1 h2, blockPSD_row_10 hbig cB h1 h2, blockPSD_row_11 hbig cB h1 h2, blockPSD_row_12 hbig cB h1 h2, blockPSD_row_13 hbig cB h1 h2, blockPSD_row_14 hbig cB h1 h2, blockPSD_row_15 hbig cB h1 h2, blockPSD_row_16 hbig cB h1 h2, blockPSD_row_17 hbig cB h1 h2, blockPSD_row_18 hbig cB h1 h2, blockPSD_row_19 hbig cB h1 h2, blockPSD_row_20 hbig cB h1 h2, blockPSD_row_21 hbig cB h1 h2, blockPSD_row_22 hbig cB h1 h2, blockPSD_row_23 hbig cB h1 h2, blockPSD_row_24 hbig cB h1 h2, blockPSD_row_25 hbig cB h1 h2]

end GYNIProof
