import GYNIProof.Core
import GYNIProof.Big.D_0_13_0
import GYNIProof.Big.D_0_13_1
import GYNIProof.Big.D_0_13_2
import GYNIProof.Big.D_0_13_3
import GYNIProof.Big.D_0_13_4
import GYNIProof.Big.D_0_13_5
import GYNIProof.Big.D_0_13_6
import GYNIProof.Big.D_0_13_7
import GYNIProof.Big.D_0_13_8
import GYNIProof.Big.D_0_13_9
import GYNIProof.Big.D_0_13_10
import GYNIProof.Big.D_0_13_11
import GYNIProof.Big.D_0_13_12
import GYNIProof.Big.D_0_13_13
import GYNIProof.Big.D_0_13_14
import GYNIProof.Big.D_0_13_15
import GYNIProof.Big.P_0_13

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 13)` (256 × 256): parameters, shapes and entry bounds, chunk lengths.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def cL_0_13 : List (List Int) := List.flatten [bL_0_13_0, bL_0_13_1, bL_0_13_2, bL_0_13_3, bL_0_13_4, bL_0_13_5, bL_0_13_6, bL_0_13_7, bL_0_13_8, bL_0_13_9, bL_0_13_10, bL_0_13_11, bL_0_13_12, bL_0_13_13, bL_0_13_14, bL_0_13_15]

def cE_0_13 : List (List Int) := List.flatten [bE_0_13_0, bE_0_13_1, bE_0_13_2, bE_0_13_3, bE_0_13_4, bE_0_13_5, bE_0_13_6, bE_0_13_7, bE_0_13_8, bE_0_13_9, bE_0_13_10, bE_0_13_11, bE_0_13_12, bE_0_13_13, bE_0_13_14, bE_0_13_15]

theorem params_0_13 : paramsOK (szN 0 * szN 13) 1099511627776 83076749736557242056487941267521536 9958913449868872 10440810096782080917964 alphaW = true := by
  decide +kernel

theorem bLok_0_13_0 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_0 = true := by
  decide +kernel

theorem bEok_0_13_0 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_0 = true := by
  decide +kernel

theorem bLok_0_13_1 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_1 = true := by
  decide +kernel

theorem bEok_0_13_1 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_1 = true := by
  decide +kernel

theorem bLok_0_13_2 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_2 = true := by
  decide +kernel

theorem bEok_0_13_2 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_2 = true := by
  decide +kernel

theorem bLok_0_13_3 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_3 = true := by
  decide +kernel

theorem bEok_0_13_3 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_3 = true := by
  decide +kernel

theorem bLok_0_13_4 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_4 = true := by
  decide +kernel

theorem bEok_0_13_4 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_4 = true := by
  decide +kernel

theorem bLok_0_13_5 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_5 = true := by
  decide +kernel

theorem bEok_0_13_5 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_5 = true := by
  decide +kernel

theorem bLok_0_13_6 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_6 = true := by
  decide +kernel

theorem bEok_0_13_6 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_6 = true := by
  decide +kernel

theorem bLok_0_13_7 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_7 = true := by
  decide +kernel

theorem bEok_0_13_7 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_7 = true := by
  decide +kernel

theorem bLok_0_13_8 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_8 = true := by
  decide +kernel

theorem bEok_0_13_8 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_8 = true := by
  decide +kernel

theorem bLok_0_13_9 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_9 = true := by
  decide +kernel

theorem bEok_0_13_9 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_9 = true := by
  decide +kernel

theorem bLok_0_13_10 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_10 = true := by
  decide +kernel

theorem bEok_0_13_10 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_10 = true := by
  decide +kernel

theorem bLok_0_13_11 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_11 = true := by
  decide +kernel

theorem bEok_0_13_11 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_11 = true := by
  decide +kernel

theorem bLok_0_13_12 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_12 = true := by
  decide +kernel

theorem bEok_0_13_12 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_12 = true := by
  decide +kernel

theorem bLok_0_13_13 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_13 = true := by
  decide +kernel

theorem bEok_0_13_13 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_13 = true := by
  decide +kernel

theorem bLok_0_13_14 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_14 = true := by
  decide +kernel

theorem bEok_0_13_14 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_14 = true := by
  decide +kernel

theorem bLok_0_13_15 : rowsBoundOK (szN 0 * szN 13) 9958913449868872 bL_0_13_15 = true := by
  decide +kernel

theorem bEok_0_13_15 : rowsBoundOK (szN 0 * szN 13) 10440810096782080917964 bE_0_13_15 = true := by
  decide +kernel

theorem shape_0_13 : shapeOK (szN 0 * szN 13) 9958913449868872 10440810096782080917964 cL_0_13 cE_0_13 bPL_0_13 = true := by
  refine shapeOK_of_chunks (by decide +kernel) (by decide +kernel) (by decide +kernel) ?_ ?_
  · simp only [cL_0_13, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bLok_0_13_0, bLok_0_13_1, bLok_0_13_2, bLok_0_13_3, bLok_0_13_4, bLok_0_13_5, bLok_0_13_6, bLok_0_13_7, bLok_0_13_8, bLok_0_13_9, bLok_0_13_10, bLok_0_13_11, bLok_0_13_12, bLok_0_13_13, bLok_0_13_14, bLok_0_13_15, Bool.and_self]
  · simp only [cE_0_13, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bEok_0_13_0, bEok_0_13_1, bEok_0_13_2, bEok_0_13_3, bEok_0_13_4, bEok_0_13_5, bEok_0_13_6, bEok_0_13_7, bEok_0_13_8, bEok_0_13_9, bEok_0_13_10, bEok_0_13_11, bEok_0_13_12, bEok_0_13_13, bEok_0_13_14, bEok_0_13_15, Bool.and_self]

theorem chunks_0_13 : ∀ l ∈ [bL_0_13_0, bL_0_13_1, bL_0_13_2, bL_0_13_3, bL_0_13_4, bL_0_13_5, bL_0_13_6, bL_0_13_7, bL_0_13_8, bL_0_13_9, bL_0_13_10, bL_0_13_11, bL_0_13_12, bL_0_13_13, bL_0_13_14, bL_0_13_15], l.length = 16 ∧ ∀ r ∈ l, r.length = (szN 0 * szN 13) := by
  decide +kernel

end GYNIProof
