import GYNIProof.Core
import GYNIProof.Big.D_0_13_9
import GYNIProof.Big.P_0_13

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 13)` (256 × 256): rows 144..159 of the packed-row identities.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows_0_13_9 : rowsOK (szN 0 * szN 13) (blockA 0 13) 1099511627776 83076749736557242056487941267521536 bPL_0_13 144
    bL_0_13_9 bE_0_13_9 = true := by
  decide +kernel

end GYNIProof
