import GYNIProof.Core
import GYNIProof.Big.D_0_0_10

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 0)` (256 × 256): packed columns of rows 160..175.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem colc_0_0_10 : packCols 83076749736557242056487941267521536 (szN 0 * szN 0) bL_0_0_10 = bPLc_0_0_10 := by
  decide +kernel

end GYNIProof
