import GYNIProof.Model
import GYNIProof.CertBigShape_0_13
import GYNIProof.CertBigCols_0_13_0
import GYNIProof.CertBigCols_0_13_1
import GYNIProof.CertBigCols_0_13_2
import GYNIProof.CertBigCols_0_13_3
import GYNIProof.CertBigCols_0_13_4
import GYNIProof.CertBigCols_0_13_5
import GYNIProof.CertBigCols_0_13_6
import GYNIProof.CertBigCols_0_13_7
import GYNIProof.CertBigCols_0_13_8
import GYNIProof.CertBigCols_0_13_9
import GYNIProof.CertBigCols_0_13_10
import GYNIProof.CertBigCols_0_13_11
import GYNIProof.CertBigCols_0_13_12
import GYNIProof.CertBigCols_0_13_13
import GYNIProof.CertBigCols_0_13_14
import GYNIProof.CertBigCols_0_13_15
import GYNIProof.CertBigComb_0_13
import GYNIProof.CertBigRows_0_13_0
import GYNIProof.CertBigRows_0_13_1
import GYNIProof.CertBigRows_0_13_2
import GYNIProof.CertBigRows_0_13_3
import GYNIProof.CertBigRows_0_13_4
import GYNIProof.CertBigRows_0_13_5
import GYNIProof.CertBigRows_0_13_6
import GYNIProof.CertBigRows_0_13_7
import GYNIProof.CertBigRows_0_13_8
import GYNIProof.CertBigRows_0_13_9
import GYNIProof.CertBigRows_0_13_10
import GYNIProof.CertBigRows_0_13_11
import GYNIProof.CertBigRows_0_13_12
import GYNIProof.CertBigRows_0_13_13
import GYNIProof.CertBigRows_0_13_14
import GYNIProof.CertBigRows_0_13_15

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 13)` (256 × 256) of `2^71 W` is positive semidefinite: assembly of the
kernel checks of `CertBigShape_0_13` and `CertBigRows_0_13_*` with `packCols_flatten` and
`posSemidef_of_cert`. -/

namespace GYNIProof

theorem cols_0_13 : packCols 83076749736557242056487941267521536 (szN 0 * szN 13) cL_0_13 = bPL_0_13 := by
  unfold cL_0_13
  rw [packCols_flatten _ _ 16 _ chunks_0_13]
  simp only [List.map_cons, List.map_nil, colc_0_13_0, colc_0_13_1, colc_0_13_2, colc_0_13_3, colc_0_13_4, colc_0_13_5, colc_0_13_6, colc_0_13_7, colc_0_13_8, colc_0_13_9, colc_0_13_10, colc_0_13_11, colc_0_13_12, colc_0_13_13, colc_0_13_14, colc_0_13_15]
  rw [show (83076749736557242056487941267521536 : ℤ) ^ 16 = 5148396096422391593693210985222689424575005282213296071655104164476572739631099228161281473378140200867014462091313754559770129599777987619078360817109726631408021465198022633853290201484467517254546983876930815720308649330475055891564430659129037097735228607981843261092469845862172555291591327620036527203133607737436305275456546467854421442630307204742014599120541028722230009317555919882603333939040716401071881068550646151042155300738685084368882435784187259732769690034514690345650083715716347735355293911309377516344880570376602323151670492827207335936 by norm_num]
  exact comb_0_13

theorem rows_0_13 : rowsOK (szN 0 * szN 13) (blockA 0 13) 1099511627776 83076749736557242056487941267521536 bPL_0_13 0 cL_0_13 cE_0_13 = true := by
  unfold cL_0_13 cE_0_13
  simp only [List.flatten_cons, List.flatten_nil, List.append_nil]
  refine rowsOK_append' _ _ _ _ _ 0 16 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_0 ?_
  refine rowsOK_append' _ _ _ _ _ 16 32 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_1 ?_
  refine rowsOK_append' _ _ _ _ _ 32 48 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_2 ?_
  refine rowsOK_append' _ _ _ _ _ 48 64 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_3 ?_
  refine rowsOK_append' _ _ _ _ _ 64 80 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_4 ?_
  refine rowsOK_append' _ _ _ _ _ 80 96 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_5 ?_
  refine rowsOK_append' _ _ _ _ _ 96 112 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_6 ?_
  refine rowsOK_append' _ _ _ _ _ 112 128 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_7 ?_
  refine rowsOK_append' _ _ _ _ _ 128 144 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_8 ?_
  refine rowsOK_append' _ _ _ _ _ 144 160 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_9 ?_
  refine rowsOK_append' _ _ _ _ _ 160 176 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_10 ?_
  refine rowsOK_append' _ _ _ _ _ 176 192 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_11 ?_
  refine rowsOK_append' _ _ _ _ _ 192 208 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_12 ?_
  refine rowsOK_append' _ _ _ _ _ 208 224 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_13 ?_
  refine rowsOK_append' _ _ _ _ _ 224 240 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_13_14 ?_
  exact rows_0_13_15

theorem cert_0_13 : BlockPSD 0 13 :=
  posSemidef_of_cert _ (blockA 0 13) (blockA_symm 0 13) _ _ _ _ alphaW (blockA_bound 0 13)
    _ _ _ params_0_13 shape_0_13 cols_0_13 rows_0_13

end GYNIProof
