import GYNIProof.Model
import GYNIProof.CertBigShape_0_0
import GYNIProof.CertBigCols_0_0_0
import GYNIProof.CertBigCols_0_0_1
import GYNIProof.CertBigCols_0_0_2
import GYNIProof.CertBigCols_0_0_3
import GYNIProof.CertBigCols_0_0_4
import GYNIProof.CertBigCols_0_0_5
import GYNIProof.CertBigCols_0_0_6
import GYNIProof.CertBigCols_0_0_7
import GYNIProof.CertBigCols_0_0_8
import GYNIProof.CertBigCols_0_0_9
import GYNIProof.CertBigCols_0_0_10
import GYNIProof.CertBigCols_0_0_11
import GYNIProof.CertBigCols_0_0_12
import GYNIProof.CertBigCols_0_0_13
import GYNIProof.CertBigCols_0_0_14
import GYNIProof.CertBigCols_0_0_15
import GYNIProof.CertBigComb_0_0
import GYNIProof.CertBigRows_0_0_0
import GYNIProof.CertBigRows_0_0_1
import GYNIProof.CertBigRows_0_0_2
import GYNIProof.CertBigRows_0_0_3
import GYNIProof.CertBigRows_0_0_4
import GYNIProof.CertBigRows_0_0_5
import GYNIProof.CertBigRows_0_0_6
import GYNIProof.CertBigRows_0_0_7
import GYNIProof.CertBigRows_0_0_8
import GYNIProof.CertBigRows_0_0_9
import GYNIProof.CertBigRows_0_0_10
import GYNIProof.CertBigRows_0_0_11
import GYNIProof.CertBigRows_0_0_12
import GYNIProof.CertBigRows_0_0_13
import GYNIProof.CertBigRows_0_0_14
import GYNIProof.CertBigRows_0_0_15

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 0)` (256 × 256) of `2^71 W` is positive semidefinite: assembly of the
kernel checks of `CertBigShape_0_0` and `CertBigRows_0_0_*` with `packCols_flatten` and
`posSemidef_of_cert`. -/

namespace GYNIProof

theorem cols_0_0 : packCols 83076749736557242056487941267521536 (szN 0 * szN 0) cL_0_0 = bPL_0_0 := by
  unfold cL_0_0
  rw [packCols_flatten _ _ 16 _ chunks_0_0]
  simp only [List.map_cons, List.map_nil, colc_0_0_0, colc_0_0_1, colc_0_0_2, colc_0_0_3, colc_0_0_4, colc_0_0_5, colc_0_0_6, colc_0_0_7, colc_0_0_8, colc_0_0_9, colc_0_0_10, colc_0_0_11, colc_0_0_12, colc_0_0_13, colc_0_0_14, colc_0_0_15]
  rw [show (83076749736557242056487941267521536 : ℤ) ^ 16 = 5148396096422391593693210985222689424575005282213296071655104164476572739631099228161281473378140200867014462091313754559770129599777987619078360817109726631408021465198022633853290201484467517254546983876930815720308649330475055891564430659129037097735228607981843261092469845862172555291591327620036527203133607737436305275456546467854421442630307204742014599120541028722230009317555919882603333939040716401071881068550646151042155300738685084368882435784187259732769690034514690345650083715716347735355293911309377516344880570376602323151670492827207335936 by norm_num]
  exact comb_0_0

theorem rows_0_0 : rowsOK (szN 0 * szN 0) (blockA 0 0) 1099511627776 83076749736557242056487941267521536 bPL_0_0 0 cL_0_0 cE_0_0 = true := by
  unfold cL_0_0 cE_0_0
  simp only [List.flatten_cons, List.flatten_nil, List.append_nil]
  refine rowsOK_append' _ _ _ _ _ 0 16 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_0 ?_
  refine rowsOK_append' _ _ _ _ _ 16 32 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_1 ?_
  refine rowsOK_append' _ _ _ _ _ 32 48 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_2 ?_
  refine rowsOK_append' _ _ _ _ _ 48 64 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_3 ?_
  refine rowsOK_append' _ _ _ _ _ 64 80 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_4 ?_
  refine rowsOK_append' _ _ _ _ _ 80 96 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_5 ?_
  refine rowsOK_append' _ _ _ _ _ 96 112 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_6 ?_
  refine rowsOK_append' _ _ _ _ _ 112 128 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_7 ?_
  refine rowsOK_append' _ _ _ _ _ 128 144 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_8 ?_
  refine rowsOK_append' _ _ _ _ _ 144 160 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_9 ?_
  refine rowsOK_append' _ _ _ _ _ 160 176 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_10 ?_
  refine rowsOK_append' _ _ _ _ _ 176 192 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_11 ?_
  refine rowsOK_append' _ _ _ _ _ 192 208 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_12 ?_
  refine rowsOK_append' _ _ _ _ _ 208 224 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_13 ?_
  refine rowsOK_append' _ _ _ _ _ 224 240 _ _ _ _ (by decide +kernel) (by decide +kernel)
    rows_0_0_14 ?_
  exact rows_0_0_15

theorem cert_0_0 : BlockPSD 0 0 :=
  posSemidef_of_cert _ (blockA 0 0) (blockA_symm 0 0) _ _ _ _ alphaW (blockA_bound 0 0)
    _ _ _ params_0_0 shape_0_0 cols_0_0 rows_0_0

end GYNIProof
