import GYNIProof.Core
import GYNIProof.Big.D_13_13_5
import GYNIProof.Big.P_13_13

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(13, 13)` (256 × 256): rows 80..95 of the packed-row identities.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows_13_13_5 : rowsOK (szN 13 * szN 13) (blockA 13 13) 1099511627776 83076749736557242056487941267521536 bPL_13_13 80
    bL_13_13_5 bE_13_13_5 = true := by
  decide +kernel

end GYNIProof
