import GYNIProof.Core
import GYNIProof.Big.D_0_13_14

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 13)` (256 × 256): packed columns of rows 224..239.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem colc_0_13_14 : packCols 83076749736557242056487941267521536 (szN 0 * szN 13) bL_0_13_14 = bPLc_0_13_14 := by
  decide +kernel

end GYNIProof
