import GYNIProof.Core
import GYNIProof.Big.D_13_13_0
import GYNIProof.Big.D_13_13_1
import GYNIProof.Big.D_13_13_2
import GYNIProof.Big.D_13_13_3
import GYNIProof.Big.D_13_13_4
import GYNIProof.Big.D_13_13_5
import GYNIProof.Big.D_13_13_6
import GYNIProof.Big.D_13_13_7
import GYNIProof.Big.D_13_13_8
import GYNIProof.Big.D_13_13_9
import GYNIProof.Big.D_13_13_10
import GYNIProof.Big.D_13_13_11
import GYNIProof.Big.D_13_13_12
import GYNIProof.Big.D_13_13_13
import GYNIProof.Big.D_13_13_14
import GYNIProof.Big.D_13_13_15
import GYNIProof.Big.P_13_13

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(13, 13)` (256 × 256): parameters, shapes and entry bounds, chunk lengths.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def cL_13_13 : List (List Int) := List.flatten [bL_13_13_0, bL_13_13_1, bL_13_13_2, bL_13_13_3, bL_13_13_4, bL_13_13_5, bL_13_13_6, bL_13_13_7, bL_13_13_8, bL_13_13_9, bL_13_13_10, bL_13_13_11, bL_13_13_12, bL_13_13_13, bL_13_13_14, bL_13_13_15]

def cE_13_13 : List (List Int) := List.flatten [bE_13_13_0, bE_13_13_1, bE_13_13_2, bE_13_13_3, bE_13_13_4, bE_13_13_5, bE_13_13_6, bE_13_13_7, bE_13_13_8, bE_13_13_9, bE_13_13_10, bE_13_13_11, bE_13_13_12, bE_13_13_13, bE_13_13_14, bE_13_13_15]

theorem params_13_13 : paramsOK (szN 13 * szN 13) 1099511627776 83076749736557242056487941267521536 9632296650911122 10440774451537762399357 alphaW = true := by
  decide +kernel

theorem bLok_13_13_0 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_0 = true := by
  decide +kernel

theorem bEok_13_13_0 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_0 = true := by
  decide +kernel

theorem bLok_13_13_1 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_1 = true := by
  decide +kernel

theorem bEok_13_13_1 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_1 = true := by
  decide +kernel

theorem bLok_13_13_2 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_2 = true := by
  decide +kernel

theorem bEok_13_13_2 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_2 = true := by
  decide +kernel

theorem bLok_13_13_3 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_3 = true := by
  decide +kernel

theorem bEok_13_13_3 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_3 = true := by
  decide +kernel

theorem bLok_13_13_4 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_4 = true := by
  decide +kernel

theorem bEok_13_13_4 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_4 = true := by
  decide +kernel

theorem bLok_13_13_5 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_5 = true := by
  decide +kernel

theorem bEok_13_13_5 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_5 = true := by
  decide +kernel

theorem bLok_13_13_6 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_6 = true := by
  decide +kernel

theorem bEok_13_13_6 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_6 = true := by
  decide +kernel

theorem bLok_13_13_7 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_7 = true := by
  decide +kernel

theorem bEok_13_13_7 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_7 = true := by
  decide +kernel

theorem bLok_13_13_8 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_8 = true := by
  decide +kernel

theorem bEok_13_13_8 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_8 = true := by
  decide +kernel

theorem bLok_13_13_9 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_9 = true := by
  decide +kernel

theorem bEok_13_13_9 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_9 = true := by
  decide +kernel

theorem bLok_13_13_10 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_10 = true := by
  decide +kernel

theorem bEok_13_13_10 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_10 = true := by
  decide +kernel

theorem bLok_13_13_11 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_11 = true := by
  decide +kernel

theorem bEok_13_13_11 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_11 = true := by
  decide +kernel

theorem bLok_13_13_12 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_12 = true := by
  decide +kernel

theorem bEok_13_13_12 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_12 = true := by
  decide +kernel

theorem bLok_13_13_13 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_13 = true := by
  decide +kernel

theorem bEok_13_13_13 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_13 = true := by
  decide +kernel

theorem bLok_13_13_14 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_14 = true := by
  decide +kernel

theorem bEok_13_13_14 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_14 = true := by
  decide +kernel

theorem bLok_13_13_15 : rowsBoundOK (szN 13 * szN 13) 9632296650911122 bL_13_13_15 = true := by
  decide +kernel

theorem bEok_13_13_15 : rowsBoundOK (szN 13 * szN 13) 10440774451537762399357 bE_13_13_15 = true := by
  decide +kernel

theorem shape_13_13 : shapeOK (szN 13 * szN 13) 9632296650911122 10440774451537762399357 cL_13_13 cE_13_13 bPL_13_13 = true := by
  refine shapeOK_of_chunks (by decide +kernel) (by decide +kernel) (by decide +kernel) ?_ ?_
  · simp only [cL_13_13, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bLok_13_13_0, bLok_13_13_1, bLok_13_13_2, bLok_13_13_3, bLok_13_13_4, bLok_13_13_5, bLok_13_13_6, bLok_13_13_7, bLok_13_13_8, bLok_13_13_9, bLok_13_13_10, bLok_13_13_11, bLok_13_13_12, bLok_13_13_13, bLok_13_13_14, bLok_13_13_15, Bool.and_self]
  · simp only [cE_13_13, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bEok_13_13_0, bEok_13_13_1, bEok_13_13_2, bEok_13_13_3, bEok_13_13_4, bEok_13_13_5, bEok_13_13_6, bEok_13_13_7, bEok_13_13_8, bEok_13_13_9, bEok_13_13_10, bEok_13_13_11, bEok_13_13_12, bEok_13_13_13, bEok_13_13_14, bEok_13_13_15, Bool.and_self]

theorem chunks_13_13 : ∀ l ∈ [bL_13_13_0, bL_13_13_1, bL_13_13_2, bL_13_13_3, bL_13_13_4, bL_13_13_5, bL_13_13_6, bL_13_13_7, bL_13_13_8, bL_13_13_9, bL_13_13_10, bL_13_13_11, bL_13_13_12, bL_13_13_13, bL_13_13_14, bL_13_13_15], l.length = 16 ∧ ∀ r ∈ l, r.length = (szN 13 * szN 13) := by
  decide +kernel

end GYNIProof
