import GYNIProof.Core
import GYNIProof.Big.D_0_0_0
import GYNIProof.Big.D_0_0_1
import GYNIProof.Big.D_0_0_2
import GYNIProof.Big.D_0_0_3
import GYNIProof.Big.D_0_0_4
import GYNIProof.Big.D_0_0_5
import GYNIProof.Big.D_0_0_6
import GYNIProof.Big.D_0_0_7
import GYNIProof.Big.D_0_0_8
import GYNIProof.Big.D_0_0_9
import GYNIProof.Big.D_0_0_10
import GYNIProof.Big.D_0_0_11
import GYNIProof.Big.D_0_0_12
import GYNIProof.Big.D_0_0_13
import GYNIProof.Big.D_0_0_14
import GYNIProof.Big.D_0_0_15
import GYNIProof.Big.P_0_0

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 0)` (256 × 256): parameters, shapes and entry bounds, chunk lengths.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def cL_0_0 : List (List Int) := List.flatten [bL_0_0_0, bL_0_0_1, bL_0_0_2, bL_0_0_3, bL_0_0_4, bL_0_0_5, bL_0_0_6, bL_0_0_7, bL_0_0_8, bL_0_0_9, bL_0_0_10, bL_0_0_11, bL_0_0_12, bL_0_0_13, bL_0_0_14, bL_0_0_15]

def cE_0_0 : List (List Int) := List.flatten [bE_0_0_0, bE_0_0_1, bE_0_0_2, bE_0_0_3, bE_0_0_4, bE_0_0_5, bE_0_0_6, bE_0_0_7, bE_0_0_8, bE_0_0_9, bE_0_0_10, bE_0_0_11, bE_0_0_12, bE_0_0_13, bE_0_0_14, bE_0_0_15]

theorem params_0_0 : paramsOK (szN 0 * szN 0) 1099511627776 83076749736557242056487941267521536 10271066458076326 10440773717303269043407 alphaW = true := by
  decide +kernel

theorem bLok_0_0_0 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_0 = true := by
  decide +kernel

theorem bEok_0_0_0 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_0 = true := by
  decide +kernel

theorem bLok_0_0_1 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_1 = true := by
  decide +kernel

theorem bEok_0_0_1 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_1 = true := by
  decide +kernel

theorem bLok_0_0_2 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_2 = true := by
  decide +kernel

theorem bEok_0_0_2 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_2 = true := by
  decide +kernel

theorem bLok_0_0_3 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_3 = true := by
  decide +kernel

theorem bEok_0_0_3 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_3 = true := by
  decide +kernel

theorem bLok_0_0_4 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_4 = true := by
  decide +kernel

theorem bEok_0_0_4 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_4 = true := by
  decide +kernel

theorem bLok_0_0_5 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_5 = true := by
  decide +kernel

theorem bEok_0_0_5 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_5 = true := by
  decide +kernel

theorem bLok_0_0_6 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_6 = true := by
  decide +kernel

theorem bEok_0_0_6 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_6 = true := by
  decide +kernel

theorem bLok_0_0_7 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_7 = true := by
  decide +kernel

theorem bEok_0_0_7 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_7 = true := by
  decide +kernel

theorem bLok_0_0_8 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_8 = true := by
  decide +kernel

theorem bEok_0_0_8 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_8 = true := by
  decide +kernel

theorem bLok_0_0_9 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_9 = true := by
  decide +kernel

theorem bEok_0_0_9 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_9 = true := by
  decide +kernel

theorem bLok_0_0_10 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_10 = true := by
  decide +kernel

theorem bEok_0_0_10 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_10 = true := by
  decide +kernel

theorem bLok_0_0_11 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_11 = true := by
  decide +kernel

theorem bEok_0_0_11 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_11 = true := by
  decide +kernel

theorem bLok_0_0_12 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_12 = true := by
  decide +kernel

theorem bEok_0_0_12 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_12 = true := by
  decide +kernel

theorem bLok_0_0_13 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_13 = true := by
  decide +kernel

theorem bEok_0_0_13 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_13 = true := by
  decide +kernel

theorem bLok_0_0_14 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_14 = true := by
  decide +kernel

theorem bEok_0_0_14 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_14 = true := by
  decide +kernel

theorem bLok_0_0_15 : rowsBoundOK (szN 0 * szN 0) 10271066458076326 bL_0_0_15 = true := by
  decide +kernel

theorem bEok_0_0_15 : rowsBoundOK (szN 0 * szN 0) 10440773717303269043407 bE_0_0_15 = true := by
  decide +kernel

theorem shape_0_0 : shapeOK (szN 0 * szN 0) 10271066458076326 10440773717303269043407 cL_0_0 cE_0_0 bPL_0_0 = true := by
  refine shapeOK_of_chunks (by decide +kernel) (by decide +kernel) (by decide +kernel) ?_ ?_
  · simp only [cL_0_0, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bLok_0_0_0, bLok_0_0_1, bLok_0_0_2, bLok_0_0_3, bLok_0_0_4, bLok_0_0_5, bLok_0_0_6, bLok_0_0_7, bLok_0_0_8, bLok_0_0_9, bLok_0_0_10, bLok_0_0_11, bLok_0_0_12, bLok_0_0_13, bLok_0_0_14, bLok_0_0_15, Bool.and_self]
  · simp only [cE_0_0, List.flatten_cons, List.flatten_nil, List.append_nil, rowsBoundOK_append, bEok_0_0_0, bEok_0_0_1, bEok_0_0_2, bEok_0_0_3, bEok_0_0_4, bEok_0_0_5, bEok_0_0_6, bEok_0_0_7, bEok_0_0_8, bEok_0_0_9, bEok_0_0_10, bEok_0_0_11, bEok_0_0_12, bEok_0_0_13, bEok_0_0_14, bEok_0_0_15, Bool.and_self]

theorem chunks_0_0 : ∀ l ∈ [bL_0_0_0, bL_0_0_1, bL_0_0_2, bL_0_0_3, bL_0_0_4, bL_0_0_5, bL_0_0_6, bL_0_0_7, bL_0_0_8, bL_0_0_9, bL_0_0_10, bL_0_0_11, bL_0_0_12, bL_0_0_13, bL_0_0_14, bL_0_0_15], l.length = 16 ∧ ∀ r ∈ l, r.length = (szN 0 * szN 0) := by
  decide +kernel

end GYNIProof
