import GYNIProof.Core
import GYNIProof.Big.D_13_13_6

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(13, 13)` (256 × 256): packed columns of rows 96..111.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem colc_13_13_6 : packCols 83076749736557242056487941267521536 (szN 13 * szN 13) bL_13_13_6 = bPLc_13_13_6 := by
  decide +kernel

end GYNIProof
