import GYNIProof.Core
import GYNIProof.Big.D_0_0_2
import GYNIProof.Big.P_0_0

/-! Generated by `GYNIProof/gen_gyni_lean.py` from `iqoqi/programs/gyni/GYNI_J4_strategy_cert.npz`.
Block `(0, 0)` (256 × 256): rows 32..47 of the packed-row identities.
Checked by the Lean kernel (`decide +kernel`), one declaration at a time; no Mathlib import. -/

namespace GYNIProof

set_option Elab.async false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows_0_0_2 : rowsOK (szN 0 * szN 0) (blockA 0 0) 1099511627776 83076749736557242056487941267521536 bPL_0_0 32
    bL_0_0_2 bE_0_0_2 = true := by
  decide +kernel

end GYNIProof
