#!/usr/bin/env bash
# GYNIProof, conditional build: everything except the kernel checks of the three 256 x 256 blocks
# (their positive semidefiniteness is the explicit hypothesis `BigBlocksPSD`; see check_big.sh).
#
# Run from anywhere (Windows, Git Bash, Lean toolchain in %USERPROFILE%\.elan\bin):
#   bash GYNIProof/check.sh 2>&1 | tee GYNIProof/logs/check_conditional.log
#
# Every file is elaborated by `lake env lean` (one process at a time; the .olean goes to the
# git-ignored .lake/build/lib/lean/GYNIProof/). Before each Lean process, tools/lean_step.ps1 waits
# (polling every 60 s) until no other lean.exe runs and Available MBytes >= expected peak working
# set + 1.5 GB (the second argument of `build` is the expected peak working set in MB, measured);
# afterwards it prints wall time, peak working set and peak private bytes. A process that dies
# without a Lean error (out-of-memory guard) is retried once after 2 minutes.
# Data/certificate files are generated by `python GYNIProof/gen_gyni_lean.py`.
set -euo pipefail
cd "$(dirname "$0")/.."
STEP="powershell -NoProfile -ExecutionPolicy Bypass -File GYNIProof/tools/lean_step.ps1"
t0=$(date +%s)
build() { # $1 = module (path below GYNIProof/, without .lean), $2 = expected peak working set (MB)
  echo "== GYNIProof/$1.lean  (start $(date +%H:%M:%S))"
  $STEP -File "GYNIProof/$1.lean" -Olean ".lake/build/lib/lean/GYNIProof/$1.olean" -PeakMB "$2"
}
# 1. Mathlib-free: data, computable core, certificate checks of the 348 blocks of size 16 and 64
for f in IntLit Data Core ValueData ValueTabs ValueCore ValueQ; do build "$f" 1000; done
for g in 0 1 2 3 4 5 6 7; do build "CertSmall$g" 900; done
for g in $(seq 0 15); do build "CertMid$g" 2100; done
# 2. Mathlib: definitions, general lemmas, the model, value, PSD assembly, conditional theorems
for f in Defs Structure BlockPSD Model Value BlockCerts PSD LowerBound; do build "$f" 3500; done
# 3. axioms
echo "== GYNIProof/Axioms.lean  (start $(date +%H:%M:%S))"
$STEP -File "GYNIProof/Axioms.lean" -PeakMB 3500
echo "== forbidden keywords (sorry/admit/axiom/native_decide) in GYNIProof/**/*.lean:"
grep -rnE '\b(sorry|admit|native_decide)\b|^\s*axiom\b' GYNIProof --include=*.lean || echo "none"
echo "== check.sh done: $(( $(date +%s) - t0 )) s"
