"""From a dihedral-basis certificate of the GYNI repository (cert3_L*.pkl: multipliers lam_int / D for the rows of
mc3.build(L, sym=True)) to a symmetry-free dual certificate, checked exactly.

Notation. Words: reduced words of length <= L in Z2*Z2, indexed by their position m in [-L, L] on the Cayley line
(m >= 0: 1010... of length m; m < 0: 0101... of length |m|); index a = m + L, n = 2L+1.
Block (r, s), entry ((a, b), (a', b')) <-> Gamma[((w_a, r), (w_b, s)), ((w_a', r), (w_b', s))].

1. Y_k (the four dual blocks, exactly as in certify2.verify_exact, scaled to integers by 16 D) from the multipliers.
2. Average over the group GG generated by fx, fy, sw (signed permutations of the index set):
   Y' = (1/|GG|) sum_g g.Y.  Integers scaled by den = 16 D |GG|.
3. Phi := o + Y' (o = objective tensor, full form, entries +-1/64 on the support).
   Checks (exact integers):
   (PD)  every block of Y' is positive definite (fraction-free LDL / Bareiss);
   (CA)  for every Bob pair q and every Alice class t != e: sum over Alice pairs p of class t of Phi[p, q] = 0;
   (CB)  the same with the roles exchanged;
   (SYM) Phi[x, y] = Phi[y, x];
   beta = sum of the diagonal entries of Phi over all four blocks (divided by den) equals lam . b.
Then for every Lueders-form strategy: gyni = o(Gamma) = <Phi, Gamma> - <Y', Gamma> <= <Phi, Gamma> = beta.
"""
import os, sys, pickle, time
sys.dont_write_bytecode = True  # never write caches into the source repository
from fractions import Fraction
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(HERE, "..", "..", "..", "publish", "GYNI-Causal-Problem", "src"))
sys.path.insert(0, SRC)
import mc3
from certify2 import exact_coef, bareiss_leading_minors


def red(w):
    out = []
    for c in w:
        if out and out[-1] == c:
            out.pop()
        else:
            out.append(c)
    return tuple(out)


def word_at(m):
    """word at position m on the Cayley line"""
    if m >= 0:
        return tuple((1 + i) % 2 for i in range(m))      # 1,0,1,...
    return tuple(i % 2 for i in range(-m))                 # 0,1,0,...


def cls(w, wp):
    return red(tuple(reversed(w)) + tuple(wp))


def load_cert(path):
    with open(path, "rb") as f:
        return pickle.load(f)


def dual_blocks(C, verbose=True):
    """exact integer blocks Yint = 16 D Y_k in mc3 indexing, as in certify2.verify_exact"""
    L = C['L']; D = C['D']; lam_int = C['lam_int']
    t0 = time.time()
    M, rows, obj = mc3.build(L, sym=True, verbose=False)
    assert len(rows) == len(lam_int)
    n = M.nvar
    SC = 8
    Sv = [0] * n
    beta_num = 0
    for li, (row, b_) in zip(lam_int, rows):
        if li == 0:
            continue
        bf = exact_coef(b_)
        beta_num += int(li * bf * SC)
        for v, c in row.items():
            val = li * exact_coef(c) * SC
            assert val.denominator == 1
            Sv[v] += int(val)
    OF = [0] * n
    for v, c in obj.items():
        f = exact_coef(c) * SC * D
        assert f.denominator == 1
        OF[v] = int(f)
    blocks = {}
    for (rA, rB, nsz, off) in M.blocks:
        Y = [[0] * nsz for _ in range(nsz)]
        for j in range(nsz):
            for i in range(j + 1):
                v = off + j * (j + 1) // 2 + i
                val = Sv[v] - OF[v]
                if i == j:
                    Y[i][i] = 2 * val
                else:
                    Y[i][j] = Y[j][i] = val
        blocks[(rA, rB)] = Y
    beta = Fraction(beta_num, SC * D)
    if verbose:
        print(f"  dual blocks from multipliers: {time.time()-t0:.1f}s, lam.b = {beta} = {float(beta):.15f}", flush=True)
    return M, blocks, beta


def to_full(M, blocks, L):
    """dict (r, s) -> dict over my indices ((a,b),(a',b')) of the integers 16 D Y"""
    n = 2 * L + 1
    A, B = M.A, M.B
    words = [word_at(m) for m in range(-L, L + 1)]
    Yf = {}
    for (r, s), Y in blocks.items():
        ks = A.reg_members[r]; ls = B.reg_members[s]
        nl = len(ls)
        # mc3 local index i = posA * nl + posB ; posA = position of word in the register list
        posA = {A.basis[k][0]: t for t, k in enumerate(ks)}
        posB = {B.basis[l][0]: t for t, l in enumerate(ls)}
        idx = [posA[words[a]] * nl + posB[words[b]] for a in range(n) for b in range(n)]
        Yf[(r, s)] = [[Y[idx[i]][idx[j]] for j in range(n * n)] for i in range(n * n)]
    return Yf, words


def group_elements(L):
    """signed permutations of the full index set x = (r, s, a, b) (block (r,s), row (a,b));
    each element: function x -> (x', sign). Generated by fx, fy, sw (acting on Gamma as in (S))."""
    n = 2 * L + 1
    words = [word_at(m) for m in range(-L, L + 1)]
    index = {w: a for a, w in enumerate(words)}
    sig = [index[tuple(1 - c for c in w)] for w in words]           # letter exchange
    par = [(-1) ** len(w) for w in words]

    def fx(x):
        r, s, a, b = x
        return (1 - r, s, sig[a], b), par[b]

    def fy(x):
        r, s, a, b = x
        return (r, 1 - s, a, sig[b]), par[a]

    def sw(x):
        r, s, a, b = x
        return (s, r, b, a), 1

    X = [(r, s, a, b) for r in (0, 1) for s in (0, 1) for a in range(n) for b in range(n)]

    def table(f):
        return tuple(f(x) for x in X)

    pos = {x: i for i, x in enumerate(X)}

    def as_perm(f):
        return tuple((pos[f(x)[0]], f(x)[1]) for x in X)

    gens = [as_perm(fx), as_perm(fy), as_perm(sw)]
    ident = tuple((i, 1) for i in range(len(X)))

    def compose(g, h):   # (g o h)(x) = g(h(x)) with signs multiplied
        return tuple((g[h[i][0]][0], g[h[i][0]][1] * h[i][1]) for i in range(len(X)))

    group = {ident}
    frontier = [ident]
    while frontier:
        nxt = []
        for g in frontier:
            for h in gens:
                k = compose(h, g)
                if k not in group:
                    group.add(k)
                    nxt.append(k)
        frontier = nxt
    return X, pos, sorted(group)


def average(Yf, L, verbose=True):
    n = 2 * L + 1
    N = n * n
    X, pos, G = group_elements(L)
    if verbose:
        print(f"  group of order {len(G)}", flush=True)

    def ent(x, y):
        # x, y in the same block
        r, s, a, b = X[x]
        r2, s2, a2, b2 = X[y]
        assert (r, s) == (r2, s2)
        return Yf[(r, s)][a * n + b][a2 * n + b2]

    Yavg = {}
    for (r, s) in Yf:
        blk = [[0] * N for _ in range(N)]
        for i in range(N):
            x = pos[(r, s, i // n, i % n)]
            for j in range(N):
                y = pos[(r, s, j // n, j % n)]
                tot = 0
                for g in G:
                    gx, sx = g[x]
                    gy, sy = g[y]
                    tot += sx * sy * ent(gx, gy)
                blk[i][j] = tot
        Yavg[(r, s)] = blk
    return Yavg, len(G)


def objective_full(L, den):
    """o_full[(r,s)][i][j] * den (integers); o = 1/4 sum_{x,y} (u_{y|x} (x) u_{x|y})(u_{y|x} (x) u_{x|y})^T,
    u_{c|x} = 1/2 e_{((),x)} + 1/2 (-1)^c e_{((x),x)}"""
    n = 2 * L + 1
    N = n * n
    words = [word_at(m) for m in range(-L, L + 1)]
    index = {w: a for a, w in enumerate(words)}
    o = {(r, s): [[Fraction(0)] * N for _ in range(N)] for r in (0, 1) for s in (0, 1)}
    for x in (0, 1):
        for y in (0, 1):
            ua = {index[()]: Fraction(1, 2), index[(x,)]: Fraction((-1) ** y, 2)}   # Alice outcome a = y, setting x
            ub = {index[()]: Fraction(1, 2), index[(y,)]: Fraction((-1) ** x, 2)}   # Bob outcome b = x, setting y
            for a, ca in ua.items():
                for b, cb in ub.items():
                    for a2, ca2 in ua.items():
                        for b2, cb2 in ub.items():
                            o[(x, y)][a * n + b][a2 * n + b2] += Fraction(1, 4) * ca * cb * ca2 * cb2
    out = {}
    for k, blk in o.items():
        rows = []
        for row in blk:
            rr = []
            for v in row:
                w = v * den
                assert w.denominator == 1
                rr.append(int(w))
            rows.append(rr)
        out[k] = rows
    return out


def check_classes(Phi, L, verbose=True):
    """(CA), (CB): class sums vanish for classes != e"""
    n = 2 * L + 1
    words = [word_at(m) for m in range(-L, L + 1)]
    cl = [[cls(words[a], words[a2]) for a2 in range(n)] for a in range(n)]
    classes = sorted({c for row in cl for c in row}, key=lambda w: (len(w), w))
    bad = 0
    # (CA): for s, b, b', class t != e: sum_{r, a, a' : cl[a][a'] = t} Phi_{rs}[(a,b),(a',b')]
    for s in (0, 1):
        for b in range(n):
            for b2 in range(n):
                acc = {}
                for r in (0, 1):
                    blk = Phi[(r, s)]
                    for a in range(n):
                        for a2 in range(n):
                            t = cl[a][a2]
                            acc[t] = acc.get(t, 0) + blk[a * n + b][a2 * n + b2]
                for t, v in acc.items():
                    if t != () and v != 0:
                        bad += 1
    badB = 0
    for r in (0, 1):
        for a in range(n):
            for a2 in range(n):
                acc = {}
                for s in (0, 1):
                    blk = Phi[(r, s)]
                    for b in range(n):
                        for b2 in range(n):
                            t = cl[b][b2]
                            acc[t] = acc.get(t, 0) + blk[a * n + b][a2 * n + b2]
                for t, v in acc.items():
                    if t != () and v != 0:
                        badB += 1
    if verbose:
        print(f"  classes: {len(classes)}; (CA) violations {bad}; (CB) violations {badB}", flush=True)
    return bad == 0 and badB == 0, classes


def ldl_pd(Mint):
    """exact positive definiteness via Bareiss leading minors"""
    minors = bareiss_leading_minors(Mint)
    return len(minors) == len(Mint) and all(m > 0 for m in minors)


def build_averaged(cert_path, check_pd=True, verbose=True):
    C = load_cert(cert_path)
    L = C['L']; D = C['D']
    n = 2 * L + 1
    M, blocks, beta = dual_blocks(C, verbose)
    Yf, words = to_full(M, blocks, L)
    Yavg, order = average(Yf, L, verbose)
    den = 16 * D * order                         # Yavg = den * Y'
    o = objective_full(L, den)
    Phi = {k: [[Yavg[k][i][j] + o[k][i][j] for j in range(n * n)] for i in range(n * n)] for k in Yavg}
    sym = all(Phi[k][i][j] == Phi[k][j][i] for k in Phi for i in range(n * n) for j in range(n * n))
    ok_cls, classes = check_classes(Phi, L, verbose)
    tr = sum(Phi[k][i][i] for k in Phi for i in range(n * n))
    beta2 = Fraction(tr, den)
    pd = None
    if check_pd:
        pd = all(ldl_pd(Yavg[k]) for k in Yavg)
    if verbose:
        print(f"  L={L}: symmetric {sym}; classes ok {ok_cls}; trace/den = {beta2} ({float(beta2):.15f}); "
              f"equals lam.b: {beta2 == beta}; PD {pd}", flush=True)
    return dict(L=L, D=D, den=den, order=order, Yavg=Yavg, o=o, Phi=Phi, beta=beta, beta_trace=beta2,
                sym=sym, classes_ok=ok_cls, pd=pd, words=words, classes=classes)


def save_averaged(cert_path, out_path, check_pd=False):
    R = build_averaged(cert_path, check_pd=check_pd)
    keep = {k: R[k] for k in ("L", "D", "den", "order", "Yavg", "o", "Phi", "beta", "beta_trace", "sym",
                              "classes_ok", "pd", "words", "classes")}
    with open(out_path, "wb") as f:
        pickle.dump(keep, f)
    print("saved", out_path, flush=True)
    return R


if __name__ == "__main__":
    # usage: averaged_cert.py cert.pkl [out.pkl] [--pd]
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) > 1:
        save_averaged(args[0], args[1], check_pd="--pd" in sys.argv)
    else:
        build_averaged(args[0], check_pd=True)
