import GYNIUpper.L2.Params
import GYNIUpper.L2.Fac00
import GYNIUpper.L2.Col00

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: packed columns of the factor of block `(0, 0)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len00 : fac00.length = nN := by decide +kernel

theorem col_len00 : col00.length = nN := by decide +kernel

theorem col_ok00_0 : colOK bL oL bX fac00 col00 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
