import GYNIUpper.L2.Params
import GYNIUpper.L2.Fac01
import GYNIUpper.L2.Col01

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: packed columns of the factor of block `(0, 1)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len01 : fac01.length = nN := by decide +kernel

theorem col_len01 : col01.length = nN := by decide +kernel

theorem col_ok01_0 : colOK bL oL bX fac01 col01 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
