import GYNIUpper.L2.Params
import GYNIUpper.L2.Fac10
import GYNIUpper.L2.Col10

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: packed columns of the factor of block `(1, 0)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len10 : fac10.length = nN := by decide +kernel

theorem col_len10 : col10.length = nN := by decide +kernel

theorem col_ok10_0 : colOK bL oL bX fac10 col10 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
