import GYNIUpper.L2.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel checks: class sums (CB), register 1 (one theorem per word chunk). -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem cb_1_0 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 1 w) 0 5 = true := by
  decide +kernel

end GYNIUpperBound.L2
