import GYNIUpper.L2.Params
import GYNIUpper.L2.Fac11
import GYNIUpper.L2.Col11

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: packed columns of the factor of block `(1, 1)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len11 : fac11.length = nN := by decide +kernel

theorem col_len11 : col11.length = nN := by decide +kernel

theorem col_ok11_0 : colOK bL oL bX fac11 col11 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
