import GYNIUpper.L2.Params
import GYNIUpper.L2.Phi00
import GYNIUpper.L2.Fac00
import GYNIUpper.L2.Col00

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel checks: rows 0..24 of `c A = L Lᵀ + E`, block `(0, 0)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows00_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
