import GYNIUpper.L2.Params
import GYNIUpper.L2.Phi11
import GYNIUpper.L2.Fac11
import GYNIUpper.L2.Col11

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel checks: rows 0..24 of `c A = L Lᵀ + E`, block `(1, 1)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows11_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
