import GYNIUpper.L2.Params
import GYNIUpper.L2.Phi01
import GYNIUpper.L2.Fac01
import GYNIUpper.L2.Col01

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel checks: rows 0..24 of `c A = L Lᵀ + E`, block `(0, 1)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows01_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 0 25 = true := by decide +kernel

end GYNIUpperBound.L2
