import GYNIUpper.L2.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: symmetry of block `(0, 1)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem sym01 : symOK bA (blk 0 1) [] 0 = true := by decide +kernel

end GYNIUpperBound.L2
