import GYNIUpper.L2.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel check: symmetry of block `(1, 0)`. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem sym10 : symOK bA (blk 1 0) [] 0 = true := by decide +kernel

end GYNIUpperBound.L2
