import GYNIUpper.L2.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Kernel checks: class table, parameters, lengths, trace. -/

namespace GYNIUpperBound.L2

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem tab_ok : tabOK (wordAt lev) nW cw tab = true := by decide +kernel

theorem cover_ok : coverOK (wordAt lev) nW cw = true := by decide +kernel

theorem cw_len : cw.length = nC := by decide +kernel

theorem cw_te : cw.getD tE [] = [] := by decide +kernel

theorem te_lt : tE < nC := by decide +kernel

theorem tab_shape : tabShapeOK nW nC tE tab = true := by decide +kernel

theorem ones_ok : onesX = packZ (pw bX 1) (List.replicate nN 1) := by decide +kernel

theorem params_ok : 0 < cS ∧ 0 ≤ eB ∧ 2 * hX = pw bX 1 ∧ 2 * oA = 2 ^ bA ∧ 2 * oL = 2 ^ bL ∧
    0 < od ∧ 64 * od = den ∧
    2 * (cS * ((oA : Int) + od) + (nN : Int) * ((oL : Int) * (oL : Int)) + eB) < pw bX 1 := by
  decide +kernel

theorem words_ok : wordAt lev lev = [] ∧ wordAt lev (i1 0) = [0] ∧ wordAt lev (i1 1) = [1] ∧
    lev < nW ∧ i1 0 < nW ∧ i1 1 < nW ∧ nN = nW * nW := by decide +kernel

theorem len00 : (blk 0 0).length = nN := by decide +kernel

theorem len01 : (blk 0 1).length = nN := by decide +kernel

theorem len10 : (blk 1 0).length = nN := by decide +kernel

theorem len11 : (blk 1 1).length = nN := by decide +kernel

theorem trace_ok : (traceSum bA (blk 0 0) 0 + traceSum bA (blk 0 1) 0 + traceSum bA (blk 1 0) 0
    + traceSum bA (blk 1 1) 0 : Int) = betaNum + 4 * nN * oA := by decide +kernel

end GYNIUpperBound.L2
