import GYNIUpper.UBLevelMain
import GYNIUpper.UBBridge
import GYNIUpper.L2.ChkTab
import GYNIUpper.L2.ChkCA_0
import GYNIUpper.L2.ChkCA_1
import GYNIUpper.L2.ChkCB_0
import GYNIUpper.L2.ChkCB_1
import GYNIUpper.L2.ChkSym00
import GYNIUpper.L2.ChkCol00
import GYNIUpper.L2.ChkRows00_0
import GYNIUpper.L2.ChkSym01
import GYNIUpper.L2.ChkCol01
import GYNIUpper.L2.ChkRows01_0
import GYNIUpper.L2.ChkSym10
import GYNIUpper.L2.ChkCol10
import GYNIUpper.L2.ChkRows10_0
import GYNIUpper.L2.ChkSym11
import GYNIUpper.L2.ChkCol11
import GYNIUpper.L2.ChkRows11_0

/-!
# The level-2 bound

Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. The certificate gives

  `I_GYNI ≤ 724501749922913 / 2^50 = 0.643486819316508…`

for every Lüders-form strategy (`gyni_le_lueders`) and, with Lemma 1
(`GYNIUpper.lueders_normal_form`), for every strategy (`gyni_upper_bound`).
-/

namespace GYNIUpperBound.L2

open GYNIProof GYNIUpperBound

set_option maxRecDepth 100000

-- the elaborator must never evaluate the checks (only the kernel does, in the check files)
attribute [local irreducible] rowsChk colOK

/-- The factor rows of block `(r, s)`. -/
noncomputable def facF (r s : ℕ) : List ℕ :=
  if r = 0 then (if s = 0 then fac00 else fac01) else (if s = 0 then fac10 else fac11)

/-- The packed factor columns of block `(r, s)`. -/
noncomputable def colF (r s : ℕ) : List ℤ :=
  if r = 0 then (if s = 0 then col00 else col01) else (if s = 0 then col10 else col11)

theorem blocks4 {p : ℕ → ℕ → Prop} (h00 : p 0 0) (h01 : p 0 1) (h10 : p 1 0) (h11 : p 1 1) :
    ∀ r < 2, ∀ s < 2, p r s := by
  intro r hr s hs
  interval_cases r <;> interval_cases s <;> assumption

theorem caok_all : caOK bA oA nW nC tE tab blk = true := by
  have hn : nW = 5 := rfl
  refine allLT_of_forall fun x hx => allLT_of_forall fun w hw => ?_
  interval_cases x
  · exact allFrom_true ca_0_0 w (Nat.zero_le w) (by omega)
  · exact allFrom_true ca_1_0 w (Nat.zero_le w) (by omega)

theorem cbok_all : cbOK bA oA nW nC tE tab blk = true := by
  have hn : nW = 5 := rfl
  refine allLT_of_forall fun x hx => allLT_of_forall fun w hw => ?_
  interval_cases x
  · exact allFrom_true cb_0_0 w (Nat.zero_le w) (by omega)
  · exact allFrom_true cb_1_0 w (Nat.zero_le w) (by omega)

theorem rows00 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 0 nN = true := by
  exact rows00_0

theorem col_ok00 : colOK bL oL bX fac00 col00 0 nN = true := by
  exact col_ok00_0

theorem rows01 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 0 nN = true := by
  exact rows01_0

theorem col_ok01 : colOK bL oL bX fac01 col01 0 nN = true := by
  exact col_ok01_0

theorem rows10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 0 nN = true := by
  exact rows10_0

theorem col_ok10 : colOK bL oL bX fac10 col10 0 nN = true := by
  exact col_ok10_0

theorem rows11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 0 nN = true := by
  exact rows11_0

theorem col_ok11 : colOK bL oL bX fac11 col11 0 nN = true := by
  exact col_ok11_0

/-- The level-2 bound for Lüders-form strategies. -/
theorem gyni_le_lueders {HA HB : Type*} [Fintype HA] [DecidableEq HA] [Fintype HB]
    [DecidableEq HB]
    {W : Matrix ((HA × (HA × Fin 2)) × (HB × (HB × Fin 2)))
      ((HA × (HA × Fin 2)) × (HB × (HB × Fin 2))) ℂ}
    (hW : IsProcess W) {P : Fin 2 → Fin 2 → Matrix HA HA ℂ} {Q : Fin 2 → Fin 2 → Matrix HB HB ℂ}
    (hP : IsProjMeas P) (hQ : IsProjMeas Q) :
    gyniValue W (lChoi P) (lChoi Q) ≤ 724501749922913 / 2 ^ 50 := by
  obtain ⟨hw0, hw1, hw2, hL, hi10, hi11, hN⟩ := words_ok
  have h := gyni_le_level (L := lev) (n := nW) (N := nN) (blk := blk) (fac := facF) (col := colF)
    hN tab_ok cover_ok cw_len cw_te te_lt tab_shape caok_all cbok_all
    (blocks4 len00 len01 len10 len11) (blocks4 sym00 sym01 sym10 sym11) trace_ok params_ok
    ones_ok ⟨hw0, hw1, hw2, hL, hi10, hi11⟩
    (blocks4 fac_len00 fac_len01 fac_len10 fac_len11)
    (blocks4 col_len00 col_len01 col_len10 col_len11)
    (blocks4 col_ok00 col_ok01 col_ok10 col_ok11)
    (blocks4 rows00 rows01 rows10 rows11) hW hP hQ
  have hval : ((betaNum : ℤ) : ℝ) / (den : ℕ) = 724501749922913 / 2 ^ 50 := by
    norm_num [betaNum, den]
  rwa [hval] at h

/-- **The level-2 upper bound on GYNI** for every strategy (finite-dimensional process `W`
and instruments `M`, `N`). -/
theorem gyni_upper_bound {AI AO BI BO : Type*} [Fintype AI] [Fintype AO] [Fintype BI]
    [Fintype BO] [DecidableEq AI] [DecidableEq BI]
    (W : Matrix ((AI × AO) × (BI × BO)) ((AI × AO) × (BI × BO)) ℂ) (hW : IsProcess W)
    (M : Fin 2 → Fin 2 → Matrix (AI × AO) (AI × AO) ℂ) (hM : IsInstrument M)
    (N : Fin 2 → Fin 2 → Matrix (BI × BO) (BI × BO) ℂ) (hN : IsInstrument N) :
    gyniValue W M N ≤ 724501749922913 / 2 ^ 50 := by
  obtain ⟨nA, nB, P, Q, W', hP, hQ, hW', hval⟩ := exists_lueders_form W hW M hM N hN
  rw [← hval]
  exact gyni_le_lueders hW' hP hQ

/-- Decimal form (rounded up) of the level-2 bound. -/
theorem gyni_upper_bound_decimal {AI AO BI BO : Type*} [Fintype AI] [Fintype AO] [Fintype BI]
    [Fintype BO] [DecidableEq AI] [DecidableEq BI]
    (W : Matrix ((AI × AO) × (BI × BO)) ((AI × AO) × (BI × BO)) ℂ) (hW : IsProcess W)
    (M : Fin 2 → Fin 2 → Matrix (AI × AO) (AI × AO) ℂ) (hM : IsInstrument M)
    (N : Fin 2 → Fin 2 → Matrix (BI × BO) (BI × BO) ℂ) (hN : IsInstrument N) :
    gyniValue W M N ≤ 0.643486819317 := by
  refine (gyni_upper_bound W hW M hM N hN).trans ?_
  norm_num

end GYNIUpperBound.L2
