import GYNIUpper.UBCheck

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L2.pkl`. Parameters, class words and class table. -/

namespace GYNIUpperBound.L2

/-- Level. -/
def lev : Nat := 2
/-- Number of words `2 lev + 1`. -/
def nW : Nat := 5
/-- Block size `nW ^ 2`. -/
def nN : Nat := 25
/-- Number of classes. -/
def nC : Nat := 9
/-- Slot of the empty class. -/
def tE : Nat := 0
/-- Digit bits of the data rows. -/
def bA : Nat := 54
/-- Offset of the data digits. -/
def oA : Nat := 9007199254740992
/-- Digit bits of the factor rows. -/
def bL : Nat := 51
/-- Offset of the factor digits. -/
def oL : Nat := 1125899906842624
/-- Bits of the packing base `X = 2 ^ bX`. -/
def bX : Nat := 107
/-- Scale `c = 2 ^ (2 F)`. -/
def cS : Int := 281474976710656
/-- Bound on the remainder entries. -/
def eB : Int := 507350838420152729035140
/-- Half base `2 ^ (bX - 1)`. -/
def hX : Int := 81129638414606681695789005144064
/-- `∑_(j < nN) X ^ j`. -/
def onesX : Int := 110924853830381255501116345086754099083666312490936285869404249232103721370270800043384282676291190628850927724187186587425355013123741743598594253357406232187703468815179621389703182651376044164497908223685937819186227260569797701572557128117083741053430558582685819450359308483404575467509797201289736173996695260750777016479487472443979886685143678175987908583118112518062291068340070041024879307959882435099151786985621234898228218912917568016173689715650253253056980088315972211829144646050621473462429936703332237435327211301951931513886334030396904284312348854827895590799412178887345628189928390072148526295811081207204217554101313950232531816186003067803237003920987828831869799874704774862105384675628194567239624207447173137988234437790105698988120844534514974721
/-- Denominator of the data. -/
def den : Nat := 144115188075855872
/-- `den / 64`. -/
def od : Int := 2251799813685248
/-- Numerator of the bound: `β = betaNum / den`. -/
def betaNum : Int := 92736223990132864
/-- Index of the word `[x]`. -/
def i1 (x : Nat) : Nat := if x = 0 then 1 else 3
/-- The class words (slots). -/
def cw : List (List (Fin 2)) := [[], [0], [1], [0, 1], [1, 0], [0, 1, 0], [1, 0, 1], [0, 1, 0, 1], [1, 0, 1, 0]]
/-- Class table by slots: `tab[t][a] = a' + 1` iff the class of `(a, a')` is `cw[t]`. -/
def tab : List (List Nat) := [
  [1, 2, 3, 4, 5],
  [0, 3, 2, 5, 4],
  [2, 1, 4, 3, 0],
  [0, 4, 1, 0, 3],
  [3, 0, 5, 2, 0],
  [0, 5, 0, 0, 2],
  [4, 0, 0, 1, 0],
  [0, 0, 0, 0, 1],
  [5, 0, 0, 0, 0]]

end GYNIUpperBound.L2
