import GYNIUpper.L8.Params
import GYNIUpper.L8.Phi00
import GYNIUpper.L8.Phi01
import GYNIUpper.L8.Phi10
import GYNIUpper.L8.Phi11

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. The four blocks. -/

namespace GYNIUpperBound.L8

/-- The packed data rows of block `(r, s)`. -/
noncomputable def blk (r s : Nat) : List Nat :=
  if r = 0 then (if s = 0 then phi00 else phi01) else (if s = 0 then phi10 else phi11)

end GYNIUpperBound.L8
