import GYNIUpper.L8.Params
import GYNIUpper.L8.Fac00
import GYNIUpper.L8.Col00

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel check: packed columns of the factor of block `(0, 0)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len00 : fac00.length = nN := by decide +kernel

theorem col_len00 : col00.length = nN := by decide +kernel

theorem col_ok00_0 : colOK bL oL bX fac00 col00 0 17 = true := by decide +kernel

theorem col_ok00_17 : colOK bL oL bX fac00 col00 17 17 = true := by decide +kernel

theorem col_ok00_34 : colOK bL oL bX fac00 col00 34 17 = true := by decide +kernel

theorem col_ok00_51 : colOK bL oL bX fac00 col00 51 17 = true := by decide +kernel

theorem col_ok00_68 : colOK bL oL bX fac00 col00 68 17 = true := by decide +kernel

theorem col_ok00_85 : colOK bL oL bX fac00 col00 85 17 = true := by decide +kernel

theorem col_ok00_102 : colOK bL oL bX fac00 col00 102 17 = true := by decide +kernel

theorem col_ok00_119 : colOK bL oL bX fac00 col00 119 17 = true := by decide +kernel

theorem col_ok00_136 : colOK bL oL bX fac00 col00 136 17 = true := by decide +kernel

theorem col_ok00_153 : colOK bL oL bX fac00 col00 153 17 = true := by decide +kernel

theorem col_ok00_170 : colOK bL oL bX fac00 col00 170 17 = true := by decide +kernel

theorem col_ok00_187 : colOK bL oL bX fac00 col00 187 17 = true := by decide +kernel

theorem col_ok00_204 : colOK bL oL bX fac00 col00 204 17 = true := by decide +kernel

theorem col_ok00_221 : colOK bL oL bX fac00 col00 221 17 = true := by decide +kernel

theorem col_ok00_238 : colOK bL oL bX fac00 col00 238 17 = true := by decide +kernel

theorem col_ok00_255 : colOK bL oL bX fac00 col00 255 17 = true := by decide +kernel

theorem col_ok00_272 : colOK bL oL bX fac00 col00 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
