import GYNIUpper.L8.Params
import GYNIUpper.L8.Fac11
import GYNIUpper.L8.Col11

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel check: packed columns of the factor of block `(1, 1)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len11 : fac11.length = nN := by decide +kernel

theorem col_len11 : col11.length = nN := by decide +kernel

theorem col_ok11_0 : colOK bL oL bX fac11 col11 0 17 = true := by decide +kernel

theorem col_ok11_17 : colOK bL oL bX fac11 col11 17 17 = true := by decide +kernel

theorem col_ok11_34 : colOK bL oL bX fac11 col11 34 17 = true := by decide +kernel

theorem col_ok11_51 : colOK bL oL bX fac11 col11 51 17 = true := by decide +kernel

theorem col_ok11_68 : colOK bL oL bX fac11 col11 68 17 = true := by decide +kernel

theorem col_ok11_85 : colOK bL oL bX fac11 col11 85 17 = true := by decide +kernel

theorem col_ok11_102 : colOK bL oL bX fac11 col11 102 17 = true := by decide +kernel

theorem col_ok11_119 : colOK bL oL bX fac11 col11 119 17 = true := by decide +kernel

theorem col_ok11_136 : colOK bL oL bX fac11 col11 136 17 = true := by decide +kernel

theorem col_ok11_153 : colOK bL oL bX fac11 col11 153 17 = true := by decide +kernel

theorem col_ok11_170 : colOK bL oL bX fac11 col11 170 17 = true := by decide +kernel

theorem col_ok11_187 : colOK bL oL bX fac11 col11 187 17 = true := by decide +kernel

theorem col_ok11_204 : colOK bL oL bX fac11 col11 204 17 = true := by decide +kernel

theorem col_ok11_221 : colOK bL oL bX fac11 col11 221 17 = true := by decide +kernel

theorem col_ok11_238 : colOK bL oL bX fac11 col11 238 17 = true := by decide +kernel

theorem col_ok11_255 : colOK bL oL bX fac11 col11 255 17 = true := by decide +kernel

theorem col_ok11_272 : colOK bL oL bX fac11 col11 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
