import GYNIUpper.L8.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: class sums (CB), register 0 (one theorem per word chunk). -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem cb_0_0 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 0 1 = true := by
  decide +kernel

theorem cb_0_1 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 1 1 = true := by
  decide +kernel

theorem cb_0_2 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 2 1 = true := by
  decide +kernel

theorem cb_0_3 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 3 1 = true := by
  decide +kernel

theorem cb_0_4 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 4 1 = true := by
  decide +kernel

theorem cb_0_5 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 5 1 = true := by
  decide +kernel

theorem cb_0_6 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 6 1 = true := by
  decide +kernel

theorem cb_0_7 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 7 1 = true := by
  decide +kernel

theorem cb_0_8 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 8 1 = true := by
  decide +kernel

theorem cb_0_9 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 9 1 = true := by
  decide +kernel

theorem cb_0_10 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 10 1 = true := by
  decide +kernel

theorem cb_0_11 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 11 1 = true := by
  decide +kernel

theorem cb_0_12 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 12 1 = true := by
  decide +kernel

theorem cb_0_13 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 13 1 = true := by
  decide +kernel

theorem cb_0_14 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 14 1 = true := by
  decide +kernel

theorem cb_0_15 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 15 1 = true := by
  decide +kernel

theorem cb_0_16 : allFrom (fun w => cbRA bA oA nW nC tE tab blk 0 w) 16 1 = true := by
  decide +kernel

end GYNIUpperBound.L8
