import GYNIUpper.L8.Params
import GYNIUpper.L8.Fac01
import GYNIUpper.L8.Col01

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel check: packed columns of the factor of block `(0, 1)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len01 : fac01.length = nN := by decide +kernel

theorem col_len01 : col01.length = nN := by decide +kernel

theorem col_ok01_0 : colOK bL oL bX fac01 col01 0 17 = true := by decide +kernel

theorem col_ok01_17 : colOK bL oL bX fac01 col01 17 17 = true := by decide +kernel

theorem col_ok01_34 : colOK bL oL bX fac01 col01 34 17 = true := by decide +kernel

theorem col_ok01_51 : colOK bL oL bX fac01 col01 51 17 = true := by decide +kernel

theorem col_ok01_68 : colOK bL oL bX fac01 col01 68 17 = true := by decide +kernel

theorem col_ok01_85 : colOK bL oL bX fac01 col01 85 17 = true := by decide +kernel

theorem col_ok01_102 : colOK bL oL bX fac01 col01 102 17 = true := by decide +kernel

theorem col_ok01_119 : colOK bL oL bX fac01 col01 119 17 = true := by decide +kernel

theorem col_ok01_136 : colOK bL oL bX fac01 col01 136 17 = true := by decide +kernel

theorem col_ok01_153 : colOK bL oL bX fac01 col01 153 17 = true := by decide +kernel

theorem col_ok01_170 : colOK bL oL bX fac01 col01 170 17 = true := by decide +kernel

theorem col_ok01_187 : colOK bL oL bX fac01 col01 187 17 = true := by decide +kernel

theorem col_ok01_204 : colOK bL oL bX fac01 col01 204 17 = true := by decide +kernel

theorem col_ok01_221 : colOK bL oL bX fac01 col01 221 17 = true := by decide +kernel

theorem col_ok01_238 : colOK bL oL bX fac01 col01 238 17 = true := by decide +kernel

theorem col_ok01_255 : colOK bL oL bX fac01 col01 255 17 = true := by decide +kernel

theorem col_ok01_272 : colOK bL oL bX fac01 col01 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
