import GYNIUpper.L8.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: class sums (CA), register 1 (one theorem per word chunk). -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem ca_1_0 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 0 1 = true := by
  decide +kernel

theorem ca_1_1 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 1 1 = true := by
  decide +kernel

theorem ca_1_2 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 2 1 = true := by
  decide +kernel

theorem ca_1_3 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 3 1 = true := by
  decide +kernel

theorem ca_1_4 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 4 1 = true := by
  decide +kernel

theorem ca_1_5 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 5 1 = true := by
  decide +kernel

theorem ca_1_6 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 6 1 = true := by
  decide +kernel

theorem ca_1_7 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 7 1 = true := by
  decide +kernel

theorem ca_1_8 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 8 1 = true := by
  decide +kernel

theorem ca_1_9 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 9 1 = true := by
  decide +kernel

theorem ca_1_10 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 10 1 = true := by
  decide +kernel

theorem ca_1_11 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 11 1 = true := by
  decide +kernel

theorem ca_1_12 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 12 1 = true := by
  decide +kernel

theorem ca_1_13 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 13 1 = true := by
  decide +kernel

theorem ca_1_14 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 14 1 = true := by
  decide +kernel

theorem ca_1_15 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 15 1 = true := by
  decide +kernel

theorem ca_1_16 : allFrom (fun w => caSB bA oA nW nC tE tab blk 1 w) 16 1 = true := by
  decide +kernel

end GYNIUpperBound.L8
