import GYNIUpper.L8.Params
import GYNIUpper.L8.Fac10
import GYNIUpper.L8.Col10

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel check: packed columns of the factor of block `(1, 0)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem fac_len10 : fac10.length = nN := by decide +kernel

theorem col_len10 : col10.length = nN := by decide +kernel

theorem col_ok10_0 : colOK bL oL bX fac10 col10 0 17 = true := by decide +kernel

theorem col_ok10_17 : colOK bL oL bX fac10 col10 17 17 = true := by decide +kernel

theorem col_ok10_34 : colOK bL oL bX fac10 col10 34 17 = true := by decide +kernel

theorem col_ok10_51 : colOK bL oL bX fac10 col10 51 17 = true := by decide +kernel

theorem col_ok10_68 : colOK bL oL bX fac10 col10 68 17 = true := by decide +kernel

theorem col_ok10_85 : colOK bL oL bX fac10 col10 85 17 = true := by decide +kernel

theorem col_ok10_102 : colOK bL oL bX fac10 col10 102 17 = true := by decide +kernel

theorem col_ok10_119 : colOK bL oL bX fac10 col10 119 17 = true := by decide +kernel

theorem col_ok10_136 : colOK bL oL bX fac10 col10 136 17 = true := by decide +kernel

theorem col_ok10_153 : colOK bL oL bX fac10 col10 153 17 = true := by decide +kernel

theorem col_ok10_170 : colOK bL oL bX fac10 col10 170 17 = true := by decide +kernel

theorem col_ok10_187 : colOK bL oL bX fac10 col10 187 17 = true := by decide +kernel

theorem col_ok10_204 : colOK bL oL bX fac10 col10 204 17 = true := by decide +kernel

theorem col_ok10_221 : colOK bL oL bX fac10 col10 221 17 = true := by decide +kernel

theorem col_ok10_238 : colOK bL oL bX fac10 col10 238 17 = true := by decide +kernel

theorem col_ok10_255 : colOK bL oL bX fac10 col10 255 17 = true := by decide +kernel

theorem col_ok10_272 : colOK bL oL bX fac10 col10 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
