import GYNIUpper.L8.Params
import GYNIUpper.L8.Phi10
import GYNIUpper.L8.Fac10
import GYNIUpper.L8.Col10

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: rows 0..288 of `c A = L Lᵀ + E`, block `(1, 0)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows10_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 0 17 = true := by decide +kernel

theorem rows10_17 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 17 17 = true := by decide +kernel

theorem rows10_34 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 34 17 = true := by decide +kernel

theorem rows10_51 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 51 17 = true := by decide +kernel

theorem rows10_68 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 68 17 = true := by decide +kernel

theorem rows10_85 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 85 17 = true := by decide +kernel

theorem rows10_102 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 102 17 = true := by decide +kernel

theorem rows10_119 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 119 17 = true := by decide +kernel

theorem rows10_136 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 136 17 = true := by decide +kernel

theorem rows10_153 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 153 17 = true := by decide +kernel

theorem rows10_170 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 170 17 = true := by decide +kernel

theorem rows10_187 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 187 17 = true := by decide +kernel

theorem rows10_204 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 204 17 = true := by decide +kernel

theorem rows10_221 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 221 17 = true := by decide +kernel

theorem rows10_238 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 238 17 = true := by decide +kernel

theorem rows10_255 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 255 17 = true := by decide +kernel

theorem rows10_272 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
