import GYNIUpper.L8.Params
import GYNIUpper.L8.Phi11
import GYNIUpper.L8.Fac11
import GYNIUpper.L8.Col11

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: rows 0..288 of `c A = L Lᵀ + E`, block `(1, 1)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows11_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 0 17 = true := by decide +kernel

theorem rows11_17 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 17 17 = true := by decide +kernel

theorem rows11_34 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 34 17 = true := by decide +kernel

theorem rows11_51 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 51 17 = true := by decide +kernel

theorem rows11_68 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 68 17 = true := by decide +kernel

theorem rows11_85 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 85 17 = true := by decide +kernel

theorem rows11_102 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 102 17 = true := by decide +kernel

theorem rows11_119 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 119 17 = true := by decide +kernel

theorem rows11_136 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 136 17 = true := by decide +kernel

theorem rows11_153 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 153 17 = true := by decide +kernel

theorem rows11_170 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 170 17 = true := by decide +kernel

theorem rows11_187 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 187 17 = true := by decide +kernel

theorem rows11_204 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 204 17 = true := by decide +kernel

theorem rows11_221 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 221 17 = true := by decide +kernel

theorem rows11_238 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 238 17 = true := by decide +kernel

theorem rows11_255 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 255 17 = true := by decide +kernel

theorem rows11_272 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
