import GYNIUpper.L8.Params
import GYNIUpper.L8.Phi01
import GYNIUpper.L8.Fac01
import GYNIUpper.L8.Col01

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: rows 0..288 of `c A = L Lᵀ + E`, block `(0, 1)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows01_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 0 17 = true := by decide +kernel

theorem rows01_17 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 17 17 = true := by decide +kernel

theorem rows01_34 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 34 17 = true := by decide +kernel

theorem rows01_51 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 51 17 = true := by decide +kernel

theorem rows01_68 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 68 17 = true := by decide +kernel

theorem rows01_85 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 85 17 = true := by decide +kernel

theorem rows01_102 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 102 17 = true := by decide +kernel

theorem rows01_119 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 119 17 = true := by decide +kernel

theorem rows01_136 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 136 17 = true := by decide +kernel

theorem rows01_153 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 153 17 = true := by decide +kernel

theorem rows01_170 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 170 17 = true := by decide +kernel

theorem rows01_187 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 187 17 = true := by decide +kernel

theorem rows01_204 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 204 17 = true := by decide +kernel

theorem rows01_221 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 221 17 = true := by decide +kernel

theorem rows01_238 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 238 17 = true := by decide +kernel

theorem rows01_255 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 255 17 = true := by decide +kernel

theorem rows01_272 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
