import GYNIUpper.L8.Params
import GYNIUpper.L8.Phi00
import GYNIUpper.L8.Fac00
import GYNIUpper.L8.Col00

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel checks: rows 0..288 of `c A = L Lᵀ + E`, block `(0, 0)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem rows00_0 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 0 17 = true := by decide +kernel

theorem rows00_17 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 17 17 = true := by decide +kernel

theorem rows00_34 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 34 17 = true := by decide +kernel

theorem rows00_51 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 51 17 = true := by decide +kernel

theorem rows00_68 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 68 17 = true := by decide +kernel

theorem rows00_85 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 85 17 = true := by decide +kernel

theorem rows00_102 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 102 17 = true := by decide +kernel

theorem rows00_119 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 119 17 = true := by decide +kernel

theorem rows00_136 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 136 17 = true := by decide +kernel

theorem rows00_153 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 153 17 = true := by decide +kernel

theorem rows00_170 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 170 17 = true := by decide +kernel

theorem rows00_187 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 187 17 = true := by decide +kernel

theorem rows00_204 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 204 17 = true := by decide +kernel

theorem rows00_221 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 221 17 = true := by decide +kernel

theorem rows00_238 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 238 17 = true := by decide +kernel

theorem rows00_255 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 255 17 = true := by decide +kernel

theorem rows00_272 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 272 17 = true := by decide +kernel

end GYNIUpperBound.L8
