import GYNIUpper.L8.Blocks

/-! Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. Kernel check: symmetry of block `(0, 0)`. -/

namespace GYNIUpperBound.L8

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

theorem sym00 : symOK bA (blk 0 0) [] 0 = true := by decide +kernel

end GYNIUpperBound.L8
