import GYNIUpper.UBLevelMain
import GYNIUpper.UBBridge
import GYNIUpper.L8.ChkTab
import GYNIUpper.L8.ChkCA_0
import GYNIUpper.L8.ChkCA_1
import GYNIUpper.L8.ChkCB_0
import GYNIUpper.L8.ChkCB_1
import GYNIUpper.L8.ChkSym00
import GYNIUpper.L8.ChkCol00
import GYNIUpper.L8.ChkRows00_0
import GYNIUpper.L8.ChkSym01
import GYNIUpper.L8.ChkCol01
import GYNIUpper.L8.ChkRows01_0
import GYNIUpper.L8.ChkSym10
import GYNIUpper.L8.ChkCol10
import GYNIUpper.L8.ChkRows10_0
import GYNIUpper.L8.ChkSym11
import GYNIUpper.L8.ChkCol11
import GYNIUpper.L8.ChkRows11_0

/-!
# The level-8 bound

Generated by `GYNIUpper/tools/export_lean.py` from `avg_L8.pkl`. The certificate gives

  `I_GYNI ≤ 175129158097837 / 2^48 = 0.622183755531001…`

for every Lüders-form strategy (`gyni_le_lueders`) and, with Lemma 1
(`GYNIUpper.lueders_normal_form`), for every strategy (`gyni_upper_bound`).
-/

namespace GYNIUpperBound.L8

open GYNIProof GYNIUpperBound

set_option maxRecDepth 100000

-- the elaborator must never evaluate the checks (only the kernel does, in the check files)
attribute [local irreducible] rowsChk colOK

/-- The factor rows of block `(r, s)`. -/
noncomputable def facF (r s : ℕ) : List ℕ :=
  if r = 0 then (if s = 0 then fac00 else fac01) else (if s = 0 then fac10 else fac11)

/-- The packed factor columns of block `(r, s)`. -/
noncomputable def colF (r s : ℕ) : List ℤ :=
  if r = 0 then (if s = 0 then col00 else col01) else (if s = 0 then col10 else col11)

theorem blocks4 {p : ℕ → ℕ → Prop} (h00 : p 0 0) (h01 : p 0 1) (h10 : p 1 0) (h11 : p 1 1) :
    ∀ r < 2, ∀ s < 2, p r s := by
  intro r hr s hs
  interval_cases r <;> interval_cases s <;> assumption

theorem caok_all : caOK bA oA nW nC tE tab blk = true := by
  have hn : nW = 17 := rfl
  refine allLT_of_forall fun x hx => allLT_of_forall fun w hw => ?_
  interval_cases x
  · exact allFrom_true (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add ca_0_0 ca_0_1) ca_0_2) ca_0_3) ca_0_4) ca_0_5) ca_0_6) ca_0_7) ca_0_8) ca_0_9) ca_0_10) ca_0_11) ca_0_12) ca_0_13) ca_0_14) ca_0_15) ca_0_16) w (Nat.zero_le w) (by omega)
  · exact allFrom_true (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add ca_1_0 ca_1_1) ca_1_2) ca_1_3) ca_1_4) ca_1_5) ca_1_6) ca_1_7) ca_1_8) ca_1_9) ca_1_10) ca_1_11) ca_1_12) ca_1_13) ca_1_14) ca_1_15) ca_1_16) w (Nat.zero_le w) (by omega)

theorem cbok_all : cbOK bA oA nW nC tE tab blk = true := by
  have hn : nW = 17 := rfl
  refine allLT_of_forall fun x hx => allLT_of_forall fun w hw => ?_
  interval_cases x
  · exact allFrom_true (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add cb_0_0 cb_0_1) cb_0_2) cb_0_3) cb_0_4) cb_0_5) cb_0_6) cb_0_7) cb_0_8) cb_0_9) cb_0_10) cb_0_11) cb_0_12) cb_0_13) cb_0_14) cb_0_15) cb_0_16) w (Nat.zero_le w) (by omega)
  · exact allFrom_true (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add (allFrom_add cb_1_0 cb_1_1) cb_1_2) cb_1_3) cb_1_4) cb_1_5) cb_1_6) cb_1_7) cb_1_8) cb_1_9) cb_1_10) cb_1_11) cb_1_12) cb_1_13) cb_1_14) cb_1_15) cb_1_16) w (Nat.zero_le w) (by omega)

theorem rows00 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0)
    col00 phi00 fac00 0 nN = true := by
  have h1 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 34 = true :=
    rowsChk_add (lo := 0) (a := 17) (b := 17) rows00_0 rows00_17
  have h2 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 51 = true :=
    rowsChk_add (lo := 0) (a := 34) (b := 17) h1 rows00_34
  have h3 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 68 = true :=
    rowsChk_add (lo := 0) (a := 51) (b := 17) h2 rows00_51
  have h4 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 85 = true :=
    rowsChk_add (lo := 0) (a := 68) (b := 17) h3 rows00_68
  have h5 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 102 = true :=
    rowsChk_add (lo := 0) (a := 85) (b := 17) h4 rows00_85
  have h6 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 119 = true :=
    rowsChk_add (lo := 0) (a := 102) (b := 17) h5 rows00_102
  have h7 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 136 = true :=
    rowsChk_add (lo := 0) (a := 119) (b := 17) h6 rows00_119
  have h8 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 153 = true :=
    rowsChk_add (lo := 0) (a := 136) (b := 17) h7 rows00_136
  have h9 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 170 = true :=
    rowsChk_add (lo := 0) (a := 153) (b := 17) h8 rows00_153
  have h10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 187 = true :=
    rowsChk_add (lo := 0) (a := 170) (b := 17) h9 rows00_170
  have h11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 204 = true :=
    rowsChk_add (lo := 0) (a := 187) (b := 17) h10 rows00_187
  have h12 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 221 = true :=
    rowsChk_add (lo := 0) (a := 204) (b := 17) h11 rows00_204
  have h13 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 238 = true :=
    rowsChk_add (lo := 0) (a := 221) (b := 17) h12 rows00_221
  have h14 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 255 = true :=
    rowsChk_add (lo := 0) (a := 238) (b := 17) h13 rows00_238
  have h15 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 272 = true :=
    rowsChk_add (lo := 0) (a := 255) (b := 17) h14 rows00_255
  have h16 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 0) col00 phi00 fac00 0 289 = true :=
    rowsChk_add (lo := 0) (a := 272) (b := 17) h15 rows00_272
  exact h16

theorem col_ok00 : colOK bL oL bX fac00 col00 0 nN = true := by
  have h1 : colOK bL oL bX fac00 col00 0 34 = true :=
    colOK_add (lo := 0) (a := 17) (b := 17) col_ok00_0 col_ok00_17
  have h2 : colOK bL oL bX fac00 col00 0 51 = true :=
    colOK_add (lo := 0) (a := 34) (b := 17) h1 col_ok00_34
  have h3 : colOK bL oL bX fac00 col00 0 68 = true :=
    colOK_add (lo := 0) (a := 51) (b := 17) h2 col_ok00_51
  have h4 : colOK bL oL bX fac00 col00 0 85 = true :=
    colOK_add (lo := 0) (a := 68) (b := 17) h3 col_ok00_68
  have h5 : colOK bL oL bX fac00 col00 0 102 = true :=
    colOK_add (lo := 0) (a := 85) (b := 17) h4 col_ok00_85
  have h6 : colOK bL oL bX fac00 col00 0 119 = true :=
    colOK_add (lo := 0) (a := 102) (b := 17) h5 col_ok00_102
  have h7 : colOK bL oL bX fac00 col00 0 136 = true :=
    colOK_add (lo := 0) (a := 119) (b := 17) h6 col_ok00_119
  have h8 : colOK bL oL bX fac00 col00 0 153 = true :=
    colOK_add (lo := 0) (a := 136) (b := 17) h7 col_ok00_136
  have h9 : colOK bL oL bX fac00 col00 0 170 = true :=
    colOK_add (lo := 0) (a := 153) (b := 17) h8 col_ok00_153
  have h10 : colOK bL oL bX fac00 col00 0 187 = true :=
    colOK_add (lo := 0) (a := 170) (b := 17) h9 col_ok00_170
  have h11 : colOK bL oL bX fac00 col00 0 204 = true :=
    colOK_add (lo := 0) (a := 187) (b := 17) h10 col_ok00_187
  have h12 : colOK bL oL bX fac00 col00 0 221 = true :=
    colOK_add (lo := 0) (a := 204) (b := 17) h11 col_ok00_204
  have h13 : colOK bL oL bX fac00 col00 0 238 = true :=
    colOK_add (lo := 0) (a := 221) (b := 17) h12 col_ok00_221
  have h14 : colOK bL oL bX fac00 col00 0 255 = true :=
    colOK_add (lo := 0) (a := 238) (b := 17) h13 col_ok00_238
  have h15 : colOK bL oL bX fac00 col00 0 272 = true :=
    colOK_add (lo := 0) (a := 255) (b := 17) h14 col_ok00_255
  have h16 : colOK bL oL bX fac00 col00 0 289 = true :=
    colOK_add (lo := 0) (a := 272) (b := 17) h15 col_ok00_272
  exact h16

theorem rows01 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1)
    col01 phi01 fac01 0 nN = true := by
  have h1 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 34 = true :=
    rowsChk_add (lo := 0) (a := 17) (b := 17) rows01_0 rows01_17
  have h2 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 51 = true :=
    rowsChk_add (lo := 0) (a := 34) (b := 17) h1 rows01_34
  have h3 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 68 = true :=
    rowsChk_add (lo := 0) (a := 51) (b := 17) h2 rows01_51
  have h4 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 85 = true :=
    rowsChk_add (lo := 0) (a := 68) (b := 17) h3 rows01_68
  have h5 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 102 = true :=
    rowsChk_add (lo := 0) (a := 85) (b := 17) h4 rows01_85
  have h6 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 119 = true :=
    rowsChk_add (lo := 0) (a := 102) (b := 17) h5 rows01_102
  have h7 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 136 = true :=
    rowsChk_add (lo := 0) (a := 119) (b := 17) h6 rows01_119
  have h8 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 153 = true :=
    rowsChk_add (lo := 0) (a := 136) (b := 17) h7 rows01_136
  have h9 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 170 = true :=
    rowsChk_add (lo := 0) (a := 153) (b := 17) h8 rows01_153
  have h10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 187 = true :=
    rowsChk_add (lo := 0) (a := 170) (b := 17) h9 rows01_170
  have h11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 204 = true :=
    rowsChk_add (lo := 0) (a := 187) (b := 17) h10 rows01_187
  have h12 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 221 = true :=
    rowsChk_add (lo := 0) (a := 204) (b := 17) h11 rows01_204
  have h13 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 238 = true :=
    rowsChk_add (lo := 0) (a := 221) (b := 17) h12 rows01_221
  have h14 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 255 = true :=
    rowsChk_add (lo := 0) (a := 238) (b := 17) h13 rows01_238
  have h15 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 272 = true :=
    rowsChk_add (lo := 0) (a := 255) (b := 17) h14 rows01_255
  have h16 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 0 1) col01 phi01 fac01 0 289 = true :=
    rowsChk_add (lo := 0) (a := 272) (b := 17) h15 rows01_272
  exact h16

theorem col_ok01 : colOK bL oL bX fac01 col01 0 nN = true := by
  have h1 : colOK bL oL bX fac01 col01 0 34 = true :=
    colOK_add (lo := 0) (a := 17) (b := 17) col_ok01_0 col_ok01_17
  have h2 : colOK bL oL bX fac01 col01 0 51 = true :=
    colOK_add (lo := 0) (a := 34) (b := 17) h1 col_ok01_34
  have h3 : colOK bL oL bX fac01 col01 0 68 = true :=
    colOK_add (lo := 0) (a := 51) (b := 17) h2 col_ok01_51
  have h4 : colOK bL oL bX fac01 col01 0 85 = true :=
    colOK_add (lo := 0) (a := 68) (b := 17) h3 col_ok01_68
  have h5 : colOK bL oL bX fac01 col01 0 102 = true :=
    colOK_add (lo := 0) (a := 85) (b := 17) h4 col_ok01_85
  have h6 : colOK bL oL bX fac01 col01 0 119 = true :=
    colOK_add (lo := 0) (a := 102) (b := 17) h5 col_ok01_102
  have h7 : colOK bL oL bX fac01 col01 0 136 = true :=
    colOK_add (lo := 0) (a := 119) (b := 17) h6 col_ok01_119
  have h8 : colOK bL oL bX fac01 col01 0 153 = true :=
    colOK_add (lo := 0) (a := 136) (b := 17) h7 col_ok01_136
  have h9 : colOK bL oL bX fac01 col01 0 170 = true :=
    colOK_add (lo := 0) (a := 153) (b := 17) h8 col_ok01_153
  have h10 : colOK bL oL bX fac01 col01 0 187 = true :=
    colOK_add (lo := 0) (a := 170) (b := 17) h9 col_ok01_170
  have h11 : colOK bL oL bX fac01 col01 0 204 = true :=
    colOK_add (lo := 0) (a := 187) (b := 17) h10 col_ok01_187
  have h12 : colOK bL oL bX fac01 col01 0 221 = true :=
    colOK_add (lo := 0) (a := 204) (b := 17) h11 col_ok01_204
  have h13 : colOK bL oL bX fac01 col01 0 238 = true :=
    colOK_add (lo := 0) (a := 221) (b := 17) h12 col_ok01_221
  have h14 : colOK bL oL bX fac01 col01 0 255 = true :=
    colOK_add (lo := 0) (a := 238) (b := 17) h13 col_ok01_238
  have h15 : colOK bL oL bX fac01 col01 0 272 = true :=
    colOK_add (lo := 0) (a := 255) (b := 17) h14 col_ok01_255
  have h16 : colOK bL oL bX fac01 col01 0 289 = true :=
    colOK_add (lo := 0) (a := 272) (b := 17) h15 col_ok01_272
  exact h16

theorem rows10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0)
    col10 phi10 fac10 0 nN = true := by
  have h1 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 34 = true :=
    rowsChk_add (lo := 0) (a := 17) (b := 17) rows10_0 rows10_17
  have h2 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 51 = true :=
    rowsChk_add (lo := 0) (a := 34) (b := 17) h1 rows10_34
  have h3 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 68 = true :=
    rowsChk_add (lo := 0) (a := 51) (b := 17) h2 rows10_51
  have h4 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 85 = true :=
    rowsChk_add (lo := 0) (a := 68) (b := 17) h3 rows10_68
  have h5 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 102 = true :=
    rowsChk_add (lo := 0) (a := 85) (b := 17) h4 rows10_85
  have h6 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 119 = true :=
    rowsChk_add (lo := 0) (a := 102) (b := 17) h5 rows10_102
  have h7 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 136 = true :=
    rowsChk_add (lo := 0) (a := 119) (b := 17) h6 rows10_119
  have h8 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 153 = true :=
    rowsChk_add (lo := 0) (a := 136) (b := 17) h7 rows10_136
  have h9 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 170 = true :=
    rowsChk_add (lo := 0) (a := 153) (b := 17) h8 rows10_153
  have h10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 187 = true :=
    rowsChk_add (lo := 0) (a := 170) (b := 17) h9 rows10_170
  have h11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 204 = true :=
    rowsChk_add (lo := 0) (a := 187) (b := 17) h10 rows10_187
  have h12 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 221 = true :=
    rowsChk_add (lo := 0) (a := 204) (b := 17) h11 rows10_204
  have h13 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 238 = true :=
    rowsChk_add (lo := 0) (a := 221) (b := 17) h12 rows10_221
  have h14 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 255 = true :=
    rowsChk_add (lo := 0) (a := 238) (b := 17) h13 rows10_238
  have h15 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 272 = true :=
    rowsChk_add (lo := 0) (a := 255) (b := 17) h14 rows10_255
  have h16 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 0) col10 phi10 fac10 0 289 = true :=
    rowsChk_add (lo := 0) (a := 272) (b := 17) h15 rows10_272
  exact h16

theorem col_ok10 : colOK bL oL bX fac10 col10 0 nN = true := by
  have h1 : colOK bL oL bX fac10 col10 0 34 = true :=
    colOK_add (lo := 0) (a := 17) (b := 17) col_ok10_0 col_ok10_17
  have h2 : colOK bL oL bX fac10 col10 0 51 = true :=
    colOK_add (lo := 0) (a := 34) (b := 17) h1 col_ok10_34
  have h3 : colOK bL oL bX fac10 col10 0 68 = true :=
    colOK_add (lo := 0) (a := 51) (b := 17) h2 col_ok10_51
  have h4 : colOK bL oL bX fac10 col10 0 85 = true :=
    colOK_add (lo := 0) (a := 68) (b := 17) h3 col_ok10_68
  have h5 : colOK bL oL bX fac10 col10 0 102 = true :=
    colOK_add (lo := 0) (a := 85) (b := 17) h4 col_ok10_85
  have h6 : colOK bL oL bX fac10 col10 0 119 = true :=
    colOK_add (lo := 0) (a := 102) (b := 17) h5 col_ok10_102
  have h7 : colOK bL oL bX fac10 col10 0 136 = true :=
    colOK_add (lo := 0) (a := 119) (b := 17) h6 col_ok10_119
  have h8 : colOK bL oL bX fac10 col10 0 153 = true :=
    colOK_add (lo := 0) (a := 136) (b := 17) h7 col_ok10_136
  have h9 : colOK bL oL bX fac10 col10 0 170 = true :=
    colOK_add (lo := 0) (a := 153) (b := 17) h8 col_ok10_153
  have h10 : colOK bL oL bX fac10 col10 0 187 = true :=
    colOK_add (lo := 0) (a := 170) (b := 17) h9 col_ok10_170
  have h11 : colOK bL oL bX fac10 col10 0 204 = true :=
    colOK_add (lo := 0) (a := 187) (b := 17) h10 col_ok10_187
  have h12 : colOK bL oL bX fac10 col10 0 221 = true :=
    colOK_add (lo := 0) (a := 204) (b := 17) h11 col_ok10_204
  have h13 : colOK bL oL bX fac10 col10 0 238 = true :=
    colOK_add (lo := 0) (a := 221) (b := 17) h12 col_ok10_221
  have h14 : colOK bL oL bX fac10 col10 0 255 = true :=
    colOK_add (lo := 0) (a := 238) (b := 17) h13 col_ok10_238
  have h15 : colOK bL oL bX fac10 col10 0 272 = true :=
    colOK_add (lo := 0) (a := 255) (b := 17) h14 col_ok10_255
  have h16 : colOK bL oL bX fac10 col10 0 289 = true :=
    colOK_add (lo := 0) (a := 272) (b := 17) h15 col_ok10_272
  exact h16

theorem rows11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1)
    col11 phi11 fac11 0 nN = true := by
  have h1 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 34 = true :=
    rowsChk_add (lo := 0) (a := 17) (b := 17) rows11_0 rows11_17
  have h2 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 51 = true :=
    rowsChk_add (lo := 0) (a := 34) (b := 17) h1 rows11_34
  have h3 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 68 = true :=
    rowsChk_add (lo := 0) (a := 51) (b := 17) h2 rows11_51
  have h4 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 85 = true :=
    rowsChk_add (lo := 0) (a := 68) (b := 17) h3 rows11_68
  have h5 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 102 = true :=
    rowsChk_add (lo := 0) (a := 85) (b := 17) h4 rows11_85
  have h6 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 119 = true :=
    rowsChk_add (lo := 0) (a := 102) (b := 17) h5 rows11_102
  have h7 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 136 = true :=
    rowsChk_add (lo := 0) (a := 119) (b := 17) h6 rows11_119
  have h8 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 153 = true :=
    rowsChk_add (lo := 0) (a := 136) (b := 17) h7 rows11_136
  have h9 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 170 = true :=
    rowsChk_add (lo := 0) (a := 153) (b := 17) h8 rows11_153
  have h10 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 187 = true :=
    rowsChk_add (lo := 0) (a := 170) (b := 17) h9 rows11_170
  have h11 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 204 = true :=
    rowsChk_add (lo := 0) (a := 187) (b := 17) h10 rows11_187
  have h12 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 221 = true :=
    rowsChk_add (lo := 0) (a := 204) (b := 17) h11 rows11_204
  have h13 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 238 = true :=
    rowsChk_add (lo := 0) (a := 221) (b := 17) h12 rows11_221
  have h14 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 255 = true :=
    rowsChk_add (lo := 0) (a := 238) (b := 17) h13 rows11_238
  have h15 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 272 = true :=
    rowsChk_add (lo := 0) (a := 255) (b := 17) h14 rows11_255
  have h16 : rowsChk nN bX bA bL oA oL cS eB hX onesX (objE nW lev i1 od 1 1) col11 phi11 fac11 0 289 = true :=
    rowsChk_add (lo := 0) (a := 272) (b := 17) h15 rows11_272
  exact h16

theorem col_ok11 : colOK bL oL bX fac11 col11 0 nN = true := by
  have h1 : colOK bL oL bX fac11 col11 0 34 = true :=
    colOK_add (lo := 0) (a := 17) (b := 17) col_ok11_0 col_ok11_17
  have h2 : colOK bL oL bX fac11 col11 0 51 = true :=
    colOK_add (lo := 0) (a := 34) (b := 17) h1 col_ok11_34
  have h3 : colOK bL oL bX fac11 col11 0 68 = true :=
    colOK_add (lo := 0) (a := 51) (b := 17) h2 col_ok11_51
  have h4 : colOK bL oL bX fac11 col11 0 85 = true :=
    colOK_add (lo := 0) (a := 68) (b := 17) h3 col_ok11_68
  have h5 : colOK bL oL bX fac11 col11 0 102 = true :=
    colOK_add (lo := 0) (a := 85) (b := 17) h4 col_ok11_85
  have h6 : colOK bL oL bX fac11 col11 0 119 = true :=
    colOK_add (lo := 0) (a := 102) (b := 17) h5 col_ok11_102
  have h7 : colOK bL oL bX fac11 col11 0 136 = true :=
    colOK_add (lo := 0) (a := 119) (b := 17) h6 col_ok11_119
  have h8 : colOK bL oL bX fac11 col11 0 153 = true :=
    colOK_add (lo := 0) (a := 136) (b := 17) h7 col_ok11_136
  have h9 : colOK bL oL bX fac11 col11 0 170 = true :=
    colOK_add (lo := 0) (a := 153) (b := 17) h8 col_ok11_153
  have h10 : colOK bL oL bX fac11 col11 0 187 = true :=
    colOK_add (lo := 0) (a := 170) (b := 17) h9 col_ok11_170
  have h11 : colOK bL oL bX fac11 col11 0 204 = true :=
    colOK_add (lo := 0) (a := 187) (b := 17) h10 col_ok11_187
  have h12 : colOK bL oL bX fac11 col11 0 221 = true :=
    colOK_add (lo := 0) (a := 204) (b := 17) h11 col_ok11_204
  have h13 : colOK bL oL bX fac11 col11 0 238 = true :=
    colOK_add (lo := 0) (a := 221) (b := 17) h12 col_ok11_221
  have h14 : colOK bL oL bX fac11 col11 0 255 = true :=
    colOK_add (lo := 0) (a := 238) (b := 17) h13 col_ok11_238
  have h15 : colOK bL oL bX fac11 col11 0 272 = true :=
    colOK_add (lo := 0) (a := 255) (b := 17) h14 col_ok11_255
  have h16 : colOK bL oL bX fac11 col11 0 289 = true :=
    colOK_add (lo := 0) (a := 272) (b := 17) h15 col_ok11_272
  exact h16

/-- The level-8 bound for Lüders-form strategies. -/
theorem gyni_le_lueders {HA HB : Type*} [Fintype HA] [DecidableEq HA] [Fintype HB]
    [DecidableEq HB]
    {W : Matrix ((HA × (HA × Fin 2)) × (HB × (HB × Fin 2)))
      ((HA × (HA × Fin 2)) × (HB × (HB × Fin 2))) ℂ}
    (hW : IsProcess W) {P : Fin 2 → Fin 2 → Matrix HA HA ℂ} {Q : Fin 2 → Fin 2 → Matrix HB HB ℂ}
    (hP : IsProjMeas P) (hQ : IsProjMeas Q) :
    gyniValue W (lChoi P) (lChoi Q) ≤ 175129158097837 / 2 ^ 48 := by
  obtain ⟨hw0, hw1, hw2, hL, hi10, hi11, hN⟩ := words_ok
  have h := gyni_le_level (L := lev) (n := nW) (N := nN) (blk := blk) (fac := facF) (col := colF)
    hN tab_ok cover_ok cw_len cw_te te_lt tab_shape caok_all cbok_all
    (blocks4 len00 len01 len10 len11) (blocks4 sym00 sym01 sym10 sym11) trace_ok params_ok
    ones_ok ⟨hw0, hw1, hw2, hL, hi10, hi11⟩
    (blocks4 fac_len00 fac_len01 fac_len10 fac_len11)
    (blocks4 col_len00 col_len01 col_len10 col_len11)
    (blocks4 col_ok00 col_ok01 col_ok10 col_ok11)
    (blocks4 rows00 rows01 rows10 rows11) hW hP hQ
  have hval : ((betaNum : ℤ) : ℝ) / (den : ℕ) = 175129158097837 / 2 ^ 48 := by
    norm_num [betaNum, den]
  rwa [hval] at h

/-- **The level-8 upper bound on GYNI** for every strategy (finite-dimensional process `W`
and instruments `M`, `N`). -/
theorem gyni_upper_bound {AI AO BI BO : Type*} [Fintype AI] [Fintype AO] [Fintype BI]
    [Fintype BO] [DecidableEq AI] [DecidableEq BI]
    (W : Matrix ((AI × AO) × (BI × BO)) ((AI × AO) × (BI × BO)) ℂ) (hW : IsProcess W)
    (M : Fin 2 → Fin 2 → Matrix (AI × AO) (AI × AO) ℂ) (hM : IsInstrument M)
    (N : Fin 2 → Fin 2 → Matrix (BI × BO) (BI × BO) ℂ) (hN : IsInstrument N) :
    gyniValue W M N ≤ 175129158097837 / 2 ^ 48 := by
  obtain ⟨nA, nB, P, Q, W', hP, hQ, hW', hval⟩ := exists_lueders_form W hW M hM N hN
  rw [← hval]
  exact gyni_le_lueders hW' hP hQ

/-- Decimal form (rounded up) of the level-8 bound. -/
theorem gyni_upper_bound_decimal {AI AO BI BO : Type*} [Fintype AI] [Fintype AO] [Fintype BI]
    [Fintype BO] [DecidableEq AI] [DecidableEq BI]
    (W : Matrix ((AI × AO) × (BI × BO)) ((AI × AO) × (BI × BO)) ℂ) (hW : IsProcess W)
    (M : Fin 2 → Fin 2 → Matrix (AI × AO) (AI × AO) ℂ) (hM : IsInstrument M)
    (N : Fin 2 → Fin 2 → Matrix (BI × BO) (BI × BO) ℂ) (hN : IsInstrument N) :
    gyniValue W M N ≤ 0.622183755532 := by
  refine (gyni_upper_bound W hW M hM N hN).trans ?_
  norm_num

end GYNIUpperBound.L8
